package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosInicio(
    val tituloJuega: String,
    val miPerfil: String,
    val tituloJugadores: String,
    val descJugadores: String,
    val tituloPausa: String,
    val tituloRecientes: String,
    val tituloPredeterminadas: String,
    val tituloColaboraciones: String,
    val tituloDescargas: String,
    val pulsaEmpezar: String,
    val creaLista: String,
    val descCreaLista: String,
    val btnCrearLista: String,
    val btnCrearAhora: String,
    val dialogoBorrarTitulo: String,
    val dialogoBorrarDesc1: String,
    val dialogoBorrarDesc2: String,
    val btnBorrar: String,
    val btnCancelar: String,
    val buscarPalabra: String,
    val contiene: String,
    val palabras: String,
    val por: String,
    val anonimo: String,
    val porMi: String,
    val unmaskOficial: String,
    val pal: String,
    val palUsadas: String,
    val btnJugar: String,
    val btnContinuar: String,
    val lista: String
)

fun obtenerTextosInicio(idioma: IdiomaSoportado): TextosInicio {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosInicio(
            tituloJuega = "¡Juega con Unmask!",
            miPerfil = "Mi Perfil",
            tituloJugadores = "Los jugadores de hoy",
            descJugadores = "Configura tu grupo antes de jugar",
            tituloPausa = "Partidas en Pausa",
            tituloRecientes = "Creaciones Recientes",
            tituloPredeterminadas = "Colecciones Predeterminadas",
            tituloColaboraciones = "Colaboraciones",
            tituloDescargas = "Listas Descargadas",
            pulsaEmpezar = "¡PULSA AQUÍ PARA EMPEZAR!",
            creaLista = "Crea tu propia lista",
            descCreaLista = "Añade tus palabras favoritas y compártelas con la comunidad.",
            btnCrearLista = "CREAR LISTA",
            btnCrearAhora = "CREAR AHORA",
            dialogoBorrarTitulo = "¿Finalizar y borrar?",
            dialogoBorrarDesc1 = "¿Seguro que quieres borrar",
            dialogoBorrarDesc2 = "?",
            btnBorrar = "BORRAR",
            btnCancelar = "CANCELAR",
            buscarPalabra = "Buscar palabra...",
            contiene = "Contiene",
            palabras = "palabras",
            por = "Por",
            anonimo = "Anónimo",
            porMi = "Por Mí",
            unmaskOficial = "Unmask Oficial",
            pal = "pal.",
            palUsadas = "pal. usadas",
            btnJugar = "JUGAR",
            btnContinuar = "CONTINUAR",
            lista = "Lista:"
        )
        IdiomaSoportado.FRANCES -> TextosInicio(
            tituloJuega = "Jouez avec Unmask !",
            miPerfil = "Mon Profil",
            tituloJugadores = "Les joueurs d'aujourd'hui",
            descJugadores = "Configurez votre groupe avant de jouer",
            tituloPausa = "Parties en Pause",
            tituloRecientes = "Créations Récentes",
            tituloPredeterminadas = "Collections par Défaut",
            tituloColaboraciones = "Collaborations",
            tituloDescargas = "Listes Téléchargées",
            pulsaEmpezar = "CLIQUEZ ICI POUR COMMENCER !",
            creaLista = "Créez votre propre liste",
            descCreaLista = "Ajoutez vos mots préférés et partagez-les avec la communauté.",
            btnCrearLista = "CRÉER UNE LISTE",
            btnCrearAhora = "CRÉER MAINTENANT",
            dialogoBorrarTitulo = "Terminer et supprimer ?",
            dialogoBorrarDesc1 = "Voulez-vous vraiment supprimer",
            dialogoBorrarDesc2 = " ?",
            btnBorrar = "SUPPRIMER",
            btnCancelar = "ANNULER",
            buscarPalabra = "Chercher un mot...",
            contiene = "Contient",
            palabras = "mots",
            por = "Par",
            anonimo = "Anonyme",
            porMi = "Par Moi",
            unmaskOficial = "Unmask Officiel",
            pal = "mots",
            palUsadas = "mots utilisés",
            btnJugar = "JOUER",
            btnContinuar = "CONTINUER",
            lista = "Liste :"
        )
        IdiomaSoportado.ITALIANO -> TextosInicio(
            tituloJuega = "Gioca con Unmask!",
            miPerfil = "Il Mio Profilo",
            tituloJugadores = "I giocatori di oggi",
            descJugadores = "Configura il tuo gruppo prima di giocare",
            tituloPausa = "Partite in Pausa",
            tituloRecientes = "Creazioni Recenti",
            tituloPredeterminadas = "Collezioni Predefinite",
            tituloColaboraciones = "Collaborazioni",
            tituloDescargas = "Liste Scaricate",
            pulsaEmpezar = "PREMI QUI PER INIZIARE!",
            creaLista = "Crea la tua lista",
            descCreaLista = "Aggiungi le tue parole preferite e condividile con la community.",
            btnCrearLista = "CREA LISTA",
            btnCrearAhora = "CREA ORA",
            dialogoBorrarTitulo = "Terminare ed eliminare?",
            dialogoBorrarDesc1 = "Sei sicuro di voler eliminare",
            dialogoBorrarDesc2 = "?",
            btnBorrar = "ELIMINA",
            btnCancelar = "ANNULLA",
            buscarPalabra = "Cerca parola...",
            contiene = "Contiene",
            palabras = "parole",
            por = "Di",
            anonimo = "Anonimo",
            porMi = "Da Me",
            unmaskOficial = "Unmask Ufficiale",
            pal = "par.",
            palUsadas = "par. usate",
            btnJugar = "GIOCA",
            btnContinuar = "CONTINUA",
            lista = "Lista:"
        )
        IdiomaSoportado.ALEMAN -> TextosInicio(
            tituloJuega = "Spiele Unmask!",
            miPerfil = "Mein Profil",
            tituloJugadores = "Die heutigen Spieler",
            descJugadores = "Richte deine Gruppe vor dem Spielen ein",
            tituloPausa = "Pausierte Spiele",
            tituloRecientes = "Aktuelle Kreationen",
            tituloPredeterminadas = "Standard-Sammlungen",
            tituloColaboraciones = "Kollaborationen",
            tituloDescargas = "Heruntergeladene Listen",
            pulsaEmpezar = "HIER KLICKEN, UM ZU STARTEN!",
            creaLista = "Erstelle deine eigene Liste",
            descCreaLista = "Füge deine Lieblingswörter hinzu und teile sie mit der Community.",
            btnCrearLista = "LISTE ERSTELLEN",
            btnCrearAhora = "JETZT ERSTELLEN",
            dialogoBorrarTitulo = "Beenden und löschen?",
            dialogoBorrarDesc1 = "Bist du sicher, dass du",
            dialogoBorrarDesc2 = "löschen möchtest?",
            btnBorrar = "LÖSCHEN",
            btnCancelar = "ABBRECHEN",
            buscarPalabra = "Wort suchen...",
            contiene = "Enthält",
            palabras = "Wörter",
            por = "Von",
            anonimo = "Anonym",
            porMi = "Von Mir",
            unmaskOficial = "Unmask Offiziell",
            pal = "Wört.",
            palUsadas = "Wört. benutzt",
            btnJugar = "SPIELEN",
            btnContinuar = "WEITER",
            lista = "Liste:"
        )
        IdiomaSoportado.CHINO -> TextosInicio(
            tituloJuega = "玩 Unmask！",
            miPerfil = "我的个人资料",
            tituloJugadores = "今天的玩家",
            descJugadores = "在开始游戏前设置您的群组",
            tituloPausa = "暂停的游戏",
            tituloRecientes = "最近的创作",
            tituloPredeterminadas = "默认集合",
            tituloColaboraciones = "合作",
            tituloDescargas = "下载的列表",
            pulsaEmpezar = "点击这里开始！",
            creaLista = "创建您自己的列表",
            descCreaLista = "添加您喜欢的单词并与社区分享。",
            btnCrearLista = "创建列表",
            btnCrearAhora = "立即创建",
            dialogoBorrarTitulo = "完成并删除？",
            dialogoBorrarDesc1 = "您确定要删除",
            dialogoBorrarDesc2 = "吗？",
            btnBorrar = "删除",
            btnCancelar = "取消",
            buscarPalabra = "搜索单词...",
            contiene = "包含",
            palabras = "个单词",
            por = "由",
            anonimo = "匿名",
            porMi = "由我",
            unmaskOficial = "Unmask 官方",
            pal = "词",
            palUsadas = "已用词",
            btnJugar = "开始游戏",
            btnContinuar = "继续",
            lista = "列表："
        )
        IdiomaSoportado.JAPONES -> TextosInicio(
            tituloJuega = "Unmaskをプレイ！",
            miPerfil = "マイプロフィール",
            tituloJugadores = "今日のプレイヤー",
            descJugadores = "プレイする前にグループを設定する",
            tituloPausa = "一時停止中のゲーム",
            tituloRecientes = "最近の作成",
            tituloPredeterminadas = "デフォルトのコレクション",
            tituloColaboraciones = "コラボ",
            tituloDescargas = "ダウンロードしたリスト",
            pulsaEmpezar = "ここを押して開始！",
            creaLista = "独自のリストを作成",
            descCreaLista = "好きな単語を追加してコミュニティと共有しましょう。",
            btnCrearLista = "リストを作成",
            btnCrearAhora = "今すぐ作成",
            dialogoBorrarTitulo = "終了して削除しますか？",
            dialogoBorrarDesc1 = "本当に",
            dialogoBorrarDesc2 = "を削除しますか？",
            btnBorrar = "削除",
            btnCancelar = "キャンセル",
            buscarPalabra = "単語を検索...",
            contiene = "含む",
            palabras = "単語",
            por = "作成者",
            anonimo = "匿名",
            porMi = "自分",
            unmaskOficial = "Unmask 公式",
            pal = "単語",
            palUsadas = "使用済みの単語",
            btnJugar = "プレイ",
            btnContinuar = "続ける",
            lista = "リスト："
        )
        // INGLÉS (Por Defecto)
        else -> TextosInicio(
            tituloJuega = "Play Unmask!",
            miPerfil = "My Profile",
            tituloJugadores = "Today's players",
            descJugadores = "Set up your group before playing",
            tituloPausa = "Paused Games",
            tituloRecientes = "Recent Creations",
            tituloPredeterminadas = "Default Collections",
            tituloColaboraciones = "Collaborations",
            tituloDescargas = "Downloaded Lists",
            pulsaEmpezar = "CLICK HERE TO START!",
            creaLista = "Create your own list",
            descCreaLista = "Add your favorite words and share them with the community.",
            btnCrearLista = "CREATE LIST",
            btnCrearAhora = "CREATE NOW",
            dialogoBorrarTitulo = "Finish and delete?",
            dialogoBorrarDesc1 = "Are you sure you want to delete",
            dialogoBorrarDesc2 = "?",
            btnBorrar = "DELETE",
            btnCancelar = "CANCEL",
            buscarPalabra = "Search word...",
            contiene = "Contains",
            palabras = "words",
            por = "By",
            anonimo = "Anonymous",
            porMi = "By Me",
            unmaskOficial = "Official Unmask",
            pal = "wds.",
            palUsadas = "wds. used",
            btnJugar = "PLAY",
            btnContinuar = "CONTINUE",
            lista = "List:"
        )
    }
}