package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosExplorar(
    val tituloExplorar: String,
    val tituloPerfil: String,
    val filtroListas: String,
    val filtroUsuarios: String,
    val buscarListas: String,
    val buscarUsuarios: String,
    val escribeNombreBuscar: String,
    val noInvestigadores: String,
    val filtroNuevas: String,
    val filtroPopulares: String,
    val filtroMasPalabras: String,
    val verTodo: String,
    val resultadosPara: String,
    val noListasComunidad: String,
    val noListasBusqueda: String,
    val tituloExploraComunidad: String,
    val descExploraComunidad: String,
    val btnIrPerfil: String,
    val listasPublicas: String,
    val seguidores: String,
    val siguiendo: String,
    val btnSiguiendo: String,
    val btnSeguir: String,
    val sinListasPublicas: String,
    val por: String,
    val pal: String,
    val btnJugar: String,
    val msgGuardada: String,
    val msgEliminada: String,
    val msgErrorSeguir: String,
    val dialogoEliminarDescargaTitulo: String,
    val dialogoEliminarDescargaDesc1: String,
    val dialogoEliminarDescargaDesc2: String,
    val btnEliminar: String,
    val btnCancelar: String,
    val buscarPalabraLista: String,
    val palabrasTotales: String,
    val msgAvisoTutorialVolver: String,
    val msgAvisoTutorialPerfil: String
)

fun obtenerTextosExplorar(idioma: IdiomaSoportado): TextosExplorar {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosExplorar(
            tituloExplorar = "Explorar", tituloPerfil = "Perfil",
            filtroListas = "Listas", filtroUsuarios = "Usuarios",
            buscarListas = "Buscar listas...", buscarUsuarios = "Buscar investigadores...",
            escribeNombreBuscar = "Escribe un nombre para buscar investigadores.",
            noInvestigadores = "No se encontraron investigadores",
            filtroNuevas = "Nuevas", filtroPopulares = "Populares", filtroMasPalabras = "Más palabras",
            verTodo = "Ver todo", resultadosPara = "Resultados para",
            noListasComunidad = "No hay listas públicas en la comunidad aún.",
            noListasBusqueda = "No hay listas que coincidan con tu búsqueda.",
            tituloExploraComunidad = "Explora la comunidad",
            descExploraComunidad = "Inicia sesión para buscar amigos, descargar listas y jugar las creaciones de otros investigadores.",
            btnIrPerfil = "IR A MI PERFIL", listasPublicas = "listas públicas",
            seguidores = "Seguidores", siguiendo = "Siguiendo",
            btnSiguiendo = "Siguiendo", btnSeguir = "Seguir",
            sinListasPublicas = "Este usuario no tiene listas públicas.",
            por = "Por", pal = "pal.", btnJugar = "JUGAR",
            msgGuardada = "Guardada en tu biblioteca online",
            msgEliminada = "Eliminada de tu biblioteca",
            msgErrorSeguir = "Error al actualizar seguimiento",
            dialogoEliminarDescargaTitulo = "¿Eliminar descarga?",
            dialogoEliminarDescargaDesc1 = "Ya tienes la lista '", dialogoEliminarDescargaDesc2 = "' guardada en tu biblioteca. ¿Deseas eliminarla?",
            btnEliminar = "ELIMINAR", btnCancelar = "CANCELAR",
            buscarPalabraLista = "Buscar palabra en esta lista...", palabrasTotales = "palabras totales",
            msgAvisoTutorialVolver = "¡Pulsa FINALIZAR en el mensaje para terminar el tutorial!",
            msgAvisoTutorialPerfil = "¡Termina el tutorial primero para iniciar sesión!"
        )
        IdiomaSoportado.FRANCES -> TextosExplorar(
            tituloExplorar = "Explorer", tituloPerfil = "Profil",
            filtroListas = "Listes", filtroUsuarios = "Utilisateurs",
            buscarListas = "Rechercher des listes...", buscarUsuarios = "Rechercher des enquêteurs...",
            escribeNombreBuscar = "Tapez un nom pour rechercher des enquêteurs.",
            noInvestigadores = "Aucun enquêteur trouvé",
            filtroNuevas = "Nouvelles", filtroPopulares = "Populaires", filtroMasPalabras = "Plus de mots",
            verTodo = "Voir tout", resultadosPara = "Résultats pour",
            noListasComunidad = "Aucune liste publique dans la communauté pour le moment.",
            noListasBusqueda = "Aucune liste ne correspond à votre recherche.",
            tituloExploraComunidad = "Explorez la communauté",
            descExploraComunidad = "Connectez-vous pour trouver des amis, télécharger des listes et jouer aux créations d'autres enquêteurs.",
            btnIrPerfil = "ALLER À MON PROFIL", listasPublicas = "listes publiques",
            seguidores = "Abonnés", siguiendo = "Abonnements",
            btnSiguiendo = "Abonné", btnSeguir = "Suivre",
            sinListasPublicas = "Cet utilisateur n'a pas de listes publiques.",
            por = "Par", pal = "mots", btnJugar = "JOUER",
            msgGuardada = "Enregistrée dans votre bibliothèque en ligne",
            msgEliminada = "Supprimée de votre bibliothèque",
            msgErrorSeguir = "Erreur de mise à jour du suivi",
            dialogoEliminarDescargaTitulo = "Supprimer le téléchargement ?",
            dialogoEliminarDescargaDesc1 = "Vous avez déjà la liste '", dialogoEliminarDescargaDesc2 = "' dans votre bibliothèque. Voulez-vous la supprimer ?",
            btnEliminar = "SUPPRIMER", btnCancelar = "ANNULER",
            buscarPalabraLista = "Chercher un mot dans cette liste...", palabrasTotales = "mots au total",
            msgAvisoTutorialVolver = "Appuyez sur TERMINER sur le message pour finir le tutoriel !",
            msgAvisoTutorialPerfil = "Terminez le tutoriel d'abord pour vous connecter !"
        )
        IdiomaSoportado.ITALIANO -> TextosExplorar(
            tituloExplorar = "Esplora", tituloPerfil = "Profilo",
            filtroListas = "Liste", filtroUsuarios = "Utenti",
            buscarListas = "Cerca liste...", buscarUsuarios = "Cerca investigatori...",
            escribeNombreBuscar = "Digita un nome per cercare investigatori.",
            noInvestigadores = "Nessun investigatore trovato",
            filtroNuevas = "Nuove", filtroPopulares = "Popolari", filtroMasPalabras = "Più parole",
            verTodo = "Vedi tutto", resultadosPara = "Risultati per",
            noListasComunidad = "Nessuna lista pubblica nella community per ora.",
            noListasBusqueda = "Nessuna lista corrisponde alla tua ricerca.",
            tituloExploraComunidad = "Esplora la community",
            descExploraComunidad = "Accedi per trovare amici, scaricare liste e giocare alle creazioni di altri investigatori.",
            btnIrPerfil = "VAI AL MIO PROFILO", listasPublicas = "liste pubbliche",
            seguidores = "Follower", siguiendo = "Seguiti",
            btnSiguiendo = "Segui già", btnSeguir = "Segui",
            sinListasPublicas = "Questo utente non ha liste pubbliche.",
            por = "Di", pal = "par.", btnJugar = "GIOCA",
            msgGuardada = "Salvata nella tua libreria online",
            msgEliminada = "Rossa dalla tua libreria",
            msgErrorSeguir = "Errore durante l'aggiornamento del follow",
            dialogoEliminarDescargaTitulo = "Eliminare il download?",
            dialogoEliminarDescargaDesc1 = "Hai già la lista '", dialogoEliminarDescargaDesc2 = "' nella tua libreria. Vuoi eliminarla?",
            btnEliminar = "ELIMINA", btnCancelar = "ANNULLA",
            buscarPalabraLista = "Cerca parola in questa lista...", palabrasTotales = "parole in totale",
            msgAvisoTutorialVolver = "Premi FINE sul messaggio per terminare il tutorial!",
            msgAvisoTutorialPerfil = "Termina prima il tutorial per accedere!"
        )
        IdiomaSoportado.ALEMAN -> TextosExplorar(
            tituloExplorar = "Entdecken", tituloPerfil = "Profil",
            filtroListas = "Listen", filtroUsuarios = "Benutzer",
            buscarListas = "Listen suchen...", buscarUsuarios = "Ermittler suchen...",
            escribeNombreBuscar = "Geben Sie einen Namen ein, um Ermittler zu suchen.",
            noInvestigadores = "Keine Ermittler gefunden",
            filtroNuevas = "Neu", filtroPopulares = "Beliebt", filtroMasPalabras = "Mehr Wörter",
            verTodo = "Alle ansehen", resultadosPara = "Ergebnisse für",
            noListasComunidad = "Noch keine öffentlichen Listen in der Community.",
            noListasBusqueda = "Keine Listen entsprechen Ihrer Suche.",
            tituloExploraComunidad = "Entdecke die Community",
            descExploraComunidad = "Melde dich an, um Freunde zu finden, Listen herunterzuladen und Kreationen anderer Ermittler zu spielen.",
            btnIrPerfil = "ZU MEINEM PROFIL", listasPublicas = "öffentliche Listen",
            seguidores = "Follower", siguiendo = "Folge ich",
            btnSiguiendo = "Folge ich", btnSeguir = "Folgen",
            sinListasPublicas = "Dieser Benutzer hat keine öffentlichen Listen.",
            por = "Von", pal = "Wört.", btnJugar = "SPIELEN",
            msgGuardada = "In deiner Online-Bibliothek gespeichert",
            msgEliminada = "Aus deiner Bibliothek entfernt",
            msgErrorSeguir = "Fehler beim Aktualisieren",
            dialogoEliminarDescargaTitulo = "Download löschen?",
            dialogoEliminarDescargaDesc1 = "Du hast die Liste '", dialogoEliminarDescargaDesc2 = "' bereits. Möchtest du sie löschen?",
            btnEliminar = "LÖSCHEN", btnCancelar = "ABBRECHEN",
            buscarPalabraLista = "Wort in dieser Liste suchen...", palabrasTotales = "Wörter insgesamt",
            msgAvisoTutorialVolver = "Drücke auf BEENDEN auf der Nachricht, um das Tutorial zu beenden!",
            msgAvisoTutorialPerfil = "Beende zuerst das Tutorial, um dich anzumelden!"
        )
        IdiomaSoportado.CHINO -> TextosExplorar(
            tituloExplorar = "探索", tituloPerfil = "个人资料",
            filtroListas = "列表", filtroUsuarios = "用户",
            buscarListas = "搜索列表...", buscarUsuarios = "搜索调查员...",
            escribeNombreBuscar = "输入名称以搜索调查员。",
            noInvestigadores = "未找到调查员",
            filtroNuevas = "最新", filtroPopulares = "热门", filtroMasPalabras = "更多词",
            verTodo = "查看全部", resultadosPara = "结果：",
            noListasComunidad = "社区中还没有公开列表。",
            noListasBusqueda = "没有符合您搜索的列表。",
            tituloExploraComunidad = "探索社区",
            descExploraComunidad = "登录以寻找朋友、下载列表并游玩其他调查员的作品。",
            btnIrPerfil = "前往我的个人资料", listasPublicas = "公开列表",
            seguidores = "粉丝", siguiendo = "关注中",
            btnSiguiendo = "已关注", btnSeguir = "关注",
            sinListasPublicas = "此用户没有公开列表。",
            por = "由", pal = "词", btnJugar = "开始游戏",
            msgGuardada = "已保存到您的在线图书馆",
            msgEliminada = "已从您的图书馆中删除",
            msgErrorSeguir = "更新关注状态时出错",
            dialogoEliminarDescargaTitulo = "删除下载？",
            dialogoEliminarDescargaDesc1 = "您的图书馆中已有列表 '", dialogoEliminarDescargaDesc2 = "' 。您要删除它吗？",
            btnEliminar = "删除", btnCancelar = "取消",
            buscarPalabraLista = "在此列表中搜索单词...", palabrasTotales = "总词数",
            msgAvisoTutorialVolver = "在消息上按“完成”以结束教程！",
            msgAvisoTutorialPerfil = "请先完成教程再登录！"
        )
        IdiomaSoportado.JAPONES -> TextosExplorar(
            tituloExplorar = "探索する", tituloPerfil = "プロフィール",
            filtroListas = "リスト", filtroUsuarios = "ユーザー",
            buscarListas = "リストを検索...", buscarUsuarios = "調査員を検索...",
            escribeNombreBuscar = "名前を入力して調査員を検索します。",
            noInvestigadores = "調査員が見つかりませんでした",
            filtroNuevas = "新着", filtroPopulares = "人気", filtroMasPalabras = "単語が多い",
            verTodo = "すべて見る", resultadosPara = "の検索結果",
            noListasComunidad = "コミュニティにはまだ公開リストがありません。",
            noListasBusqueda = "検索条件に一致するリストはありません。",
            tituloExploraComunidad = "コミュニティを探索する",
            descExploraComunidad = "ログインして友達を見つけ、リストをダウンロードし、他の調査員の作品をプレイしましょう。",
            btnIrPerfil = "マイプロフィールへ", listasPublicas = "公開リスト",
            seguidores = "フォロワー", siguiendo = "フォロー中",
            btnSiguiendo = "フォロー中", btnSeguir = "フォローする",
            sinListasPublicas = "このユーザーには公開リストがありません。",
            por = "作成者", pal = "単語", btnJugar = "プレイ",
            msgGuardada = "オンラインライブラリに保存されました",
            msgEliminada = "ライブラリから削除されました",
            msgErrorSeguir = "フォローの更新中にエラーが発生しました",
            dialogoEliminarDescargaTitulo = "ダウンロードを削除しますか？",
            dialogoEliminarDescargaDesc1 = "リスト '", dialogoEliminarDescargaDesc2 = "' はすでにライブラリにあります。削除しますか？",
            btnEliminar = "削除", btnCancelar = "キャンセル",
            buscarPalabraLista = "このリスト内の単語を検索...", palabrasTotales = "合計単語数",
            msgAvisoTutorialVolver = "メッセージの「完了」を押してチュートリアルを終了してください！",
            msgAvisoTutorialPerfil = "ログインするには、まずチュートリアルを完了してください！"
        )
        // INGLÉS POR DEFECTO
        else -> TextosExplorar(
            tituloExplorar = "Explore", tituloPerfil = "Profile",
            filtroListas = "Lists", filtroUsuarios = "Users",
            buscarListas = "Search lists...", buscarUsuarios = "Search investigators...",
            escribeNombreBuscar = "Type a name to search for investigators.",
            noInvestigadores = "No investigators found",
            filtroNuevas = "New", filtroPopulares = "Popular", filtroMasPalabras = "More words",
            verTodo = "See all", resultadosPara = "Results for",
            noListasComunidad = "No public lists in the community yet.",
            noListasBusqueda = "No lists match your search.",
            tituloExploraComunidad = "Explore the community",
            descExploraComunidad = "Log in to find friends, download lists, and play creations from other investigators.",
            btnIrPerfil = "GO TO MY PROFILE", listasPublicas = "public lists",
            seguidores = "Followers", siguiendo = "Following",
            btnSiguiendo = "Following", btnSeguir = "Follow",
            sinListasPublicas = "This user has no public lists.",
            por = "By", pal = "wds.", btnJugar = "PLAY",
            msgGuardada = "Saved to your online library",
            msgEliminada = "Removed from your library",
            msgErrorSeguir = "Error updating follow status",
            dialogoEliminarDescargaTitulo = "Delete download?",
            dialogoEliminarDescargaDesc1 = "You already have the list '", dialogoEliminarDescargaDesc2 = "' saved in your library. Do you want to delete it?",
            btnEliminar = "DELETE", btnCancelar = "CANCEL",
            buscarPalabraLista = "Search word in this list...", palabrasTotales = "total words",
            msgAvisoTutorialVolver = "Press FINISH on the message to end the tutorial!",
            msgAvisoTutorialPerfil = "Finish the tutorial first to log in!"
        )
    }
}