package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosConfiguracion(
    val tituloConfiguracion: String,
    val tituloJugadores: String,
    val descJugadores: String,
    val errorMinJugadores: String,
    val tituloImpostores: String,
    val descImpostores: String,
    val tituloPista: String,
    val descPista: String,
    val tituloNoRepetir: String,
    val descNoRepetir: String,
    val restantes: String,
    val btnCargar: String,
    val btnGuardar: String,
    val checkpointActivo: String,
    val errorNoPalabras: String,
    val tituloRondas: String,
    val txtRondas: String,
    val txtIndefinido: String,
    val tituloTiempo: String,
    val txtMinutos: String,
    val txtSinLimite: String,
    val btnIniciarPartida: String,
    val btnIniciaAqui: String,
    val msgTutorialJugar: String,
    val dialogoSalirTitulo: String,
    val dialogoSalirDesc: String,
    val btnGuardarPrimero: String,
    val btnIgnorarSalir: String,
    val btnCancelar: String,
    val dialogoGestionTitulo: String,
    val dialogoGestionDesc: String,
    val btnCargarPartida: String,
    val btnEmpezarCero: String,
    val dialogoIncompatibleTitulo: String,
    val dialogoIncompatibleDesc: String,
    val btnGuardarProgreso: String,
    val btnDescartarDesactivar: String,
    val dialogoGuardarCpTitulo: String,
    val labelNombreCp: String,
    val txtActualizaExistente: String,
    val txtActualizar: String,
    val msgCpActualizado: String,
    val btnCrearNuevo: String,
    val msgCpGuardado: String,
    val dialogoCargarCpTitulo: String,
    val txtNoCps: String,
    val msgProgresoCargado: String,
    val msgCargadoExito: String,
    val btnCerrar: String
)

fun obtenerTextosConfiguracion(idioma: IdiomaSoportado): TextosConfiguracion {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosConfiguracion(
            tituloConfiguracion = "Configuración", tituloJugadores = "Jugadores", descJugadores = "añadidos (Mínimo 3)",
            errorMinJugadores = "Faltan jugadores. Necesitas mínimo 3.", tituloImpostores = "Impostores", descImpostores = "Máximo 1 por cada 3 jugadores",
            tituloPista = "Pista para Impostor", descPista = "Recibirá una pista vaga de la palabra", tituloNoRepetir = "No repetir palabras",
            descNoRepetir = "Evita que salgan palabras de partidas anteriores", restantes = "Restantes:", btnCargar = "Cargar", btnGuardar = "Guardar",
            checkpointActivo = "Checkpoint activo:", errorNoPalabras = "No quedan palabras nuevas. Apaga y enciende la opción o carga otro checkpoint.",
            tituloRondas = "Límite de Rondas", txtRondas = "rondas", txtIndefinido = "Indefinido", tituloTiempo = "Límite de Tiempo",
            txtMinutos = "minutos", txtSinLimite = "Sin límite", btnIniciarPartida = "INICIAR PARTIDA", btnIniciaAqui = "¡INICIA LA PARTIDA AQUÍ!",
            msgTutorialJugar = "Inicia la partida para continuar el tutorial o pulsa Omitir arriba.", dialogoSalirTitulo = "¿Salir sin guardar?",
            dialogoSalirDesc = "Has realizado cambios en la configuración o tienes progreso de palabras sin guardar. Si sales ahora, se perderán.",
            btnGuardarPrimero = "GUARDAR PRIMERO", btnIgnorarSalir = "IGNORAR Y SALIR", btnCancelar = "CANCELAR",
            dialogoGestionTitulo = "Gestión de Progreso", dialogoGestionDesc = "¿Quieres retomar una partida anterior o empezar una ruta de palabras nueva?",
            btnCargarPartida = "CARGAR PARTIDA", btnEmpezarCero = "EMPEZAR DE CERO", dialogoIncompatibleTitulo = "Checkpoint Incompatible",
            dialogoIncompatibleDesc = "No puedes desactivar esta opción mientras usas un checkpoint. ¿Quieres guardar el progreso actual primero?",
            btnGuardarProgreso = "GUARDAR PROGRESO", btnDescartarDesactivar = "DESCARTAR Y DESACTIVAR", dialogoGuardarCpTitulo = "Guardar Checkpoint",
            labelNombreCp = "Nombre para este Checkpoint", txtActualizaExistente = "O actualiza uno existente:", txtActualizar = "Actualizar:",
            msgCpActualizado = "Checkpoint actualizado en la nube", btnCrearNuevo = "CREAR NUEVO", msgCpGuardado = "Nuevo checkpoint guardado en la nube",
            dialogoCargarCpTitulo = "Cargar Checkpoint", txtNoCps = "No tienes checkpoints guardados para esta lista.", msgProgresoCargado = "Progreso de",
            msgCargadoExito = "cargado", btnCerrar = "CERRAR"
        )
        IdiomaSoportado.FRANCES -> TextosConfiguracion(
            tituloConfiguracion = "Configuration", tituloJugadores = "Joueurs", descJugadores = "ajoutés (Min 3)",
            errorMinJugadores = "Il manque des joueurs. Minimum 3.", tituloImpostores = "Imposteurs", descImpostores = "Max 1 pour 3 joueurs",
            tituloPista = "Indice pour l'imposteur", descPista = "Il recevra un vague indice", tituloNoRepetir = "Ne pas répéter les mots",
            descNoRepetir = "Évite les mots des parties précédentes", restantes = "Restants :", btnCargar = "Charger", btnGuardar = "Sauver",
            checkpointActivo = "Checkpoint actif :", errorNoPalabras = "Plus de mots nouveaux. Changez l'option ou chargez un autre checkpoint.",
            tituloRondas = "Limite de manches", txtRondas = "manches", txtIndefinido = "Indéfini", tituloTiempo = "Limite de temps",
            txtMinutos = "minutes", txtSinLimite = "Sans limite", btnIniciarPartida = "COMMENCER LA PARTIE", btnIniciaAqui = "COMMENCEZ ICI !",
            msgTutorialJugar = "Lancez la partie pour continuer le tuto ou passez-le.", dialogoSalirTitulo = "Quitter sans sauvegarder ?",
            dialogoSalirDesc = "Des modifications non sauvegardées seront perdues.",
            btnGuardarPrimero = "SAUVEGARDER D'ABORD", btnIgnorarSalir = "IGNORER ET QUITTER", btnCancelar = "ANNULER",
            dialogoGestionTitulo = "Gestion de progression", dialogoGestionDesc = "Reprendre une ancienne partie ou en commencer une nouvelle ?",
            btnCargarPartida = "CHARGER PARTIE", btnEmpezarCero = "RECOMMENCER", dialogoIncompatibleTitulo = "Checkpoint Incompatible",
            dialogoIncompatibleDesc = "Désactivation impossible pendant l'utilisation d'un checkpoint. Sauvegarder d'abord ?",
            btnGuardarProgreso = "SAUVEGARDER PROGRÈS", btnDescartarDesactivar = "IGNORER ET DÉSACTIVER", dialogoGuardarCpTitulo = "Sauver Checkpoint",
            labelNombreCp = "Nom du Checkpoint", txtActualizaExistente = "Ou mettre à jour un existant :", txtActualizar = "Mettre à jour :",
            msgCpActualizado = "Checkpoint mis à jour", btnCrearNuevo = "CRÉER NOUVEAU", msgCpGuardado = "Nouveau checkpoint sauvegardé",
            dialogoCargarCpTitulo = "Charger Checkpoint", txtNoCps = "Aucun checkpoint pour cette liste.", msgProgresoCargado = "Progrès de",
            msgCargadoExito = "chargé", btnCerrar = "FERMER"
        )
        IdiomaSoportado.ITALIANO -> TextosConfiguracion(
            tituloConfiguracion = "Impostazioni", tituloJugadores = "Giocatori", descJugadores = "aggiunti (Min 3)",
            errorMinJugadores = "Mancano giocatori. Minimo 3.", tituloImpostores = "Impostori", descImpostores = "Max 1 ogni 3 giocatori",
            tituloPista = "Indizio per Impostore", descPista = "Riceverà un indizio vago", tituloNoRepetir = "Non ripetere parole",
            descNoRepetir = "Evita parole di partite precedenti", restantes = "Rimanenti:", btnCargar = "Carica", btnGuardar = "Salva",
            checkpointActivo = "Checkpoint attivo:", errorNoPalabras = "Nessuna parola nuova. Cambia opzione o carica altro checkpoint.",
            tituloRondas = "Limite di Round", txtRondas = "round", txtIndefinido = "Indefinito", tituloTiempo = "Limite di Tempo",
            txtMinutos = "minuti", txtSinLimite = "Nessun limite", btnIniciarPartida = "INIZIA PARTITA", btnIniciaAqui = "INIZIA QUI!",
            msgTutorialJugar = "Inizia la partita per continuare il tutorial o salta.", dialogoSalirTitulo = "Uscire senza salvare?",
            dialogoSalirDesc = "Le modifiche non salvate andranno perse.",
            btnGuardarPrimero = "SALVA PRIMA", btnIgnorarSalir = "IGNORA E ESCI", btnCancelar = "ANNULLA",
            dialogoGestionTitulo = "Gestione Progressi", dialogoGestionDesc = "Vuoi riprendere una partita o iniziarne una nuova?",
            btnCargarPartida = "CARICA PARTITA", btnEmpezarCero = "INIZIA DA ZERO", dialogoIncompatibleTitulo = "Checkpoint Incompatibile",
            dialogoIncompatibleDesc = "Impossibile disattivare usando un checkpoint. Salvare prima?",
            btnGuardarProgreso = "SALVA PROGRESSO", btnDescartarDesactivar = "SCARTA E DISATTIVA", dialogoGuardarCpTitulo = "Salva Checkpoint",
            labelNombreCp = "Nome del Checkpoint", txtActualizaExistente = "O aggiornane uno esistente:", txtActualizar = "Aggiorna:",
            msgCpActualizado = "Checkpoint aggiornato", btnCrearNuevo = "CREA NUOVO", msgCpGuardado = "Nuovo checkpoint salvato",
            dialogoCargarCpTitulo = "Carica Checkpoint", txtNoCps = "Nessun checkpoint per questa lista.", msgProgresoCargado = "Progresso di",
            msgCargadoExito = "caricato", btnCerrar = "CHIUDI"
        )
        IdiomaSoportado.ALEMAN -> TextosConfiguracion(
            tituloConfiguracion = "Einstellungen", tituloJugadores = "Spieler", descJugadores = "hinzugefügt (Min. 3)",
            errorMinJugadores = "Nicht genug Spieler. Mindestens 3.", tituloImpostores = "Impostors", descImpostores = "Max. 1 pro 3 Spieler",
            tituloPista = "Hinweis für Impostor", descPista = "Erhält einen vagen Hinweis", tituloNoRepetir = "Wörter nicht wiederholen",
            descNoRepetir = "Vermeidet Wörter aus vorherigen Spielen", restantes = "Übrig:", btnCargar = "Laden", btnGuardar = "Speichern",
            checkpointActivo = "Aktiver Checkpoint:", errorNoPalabras = "Keine neuen Wörter mehr. Option ändern oder Checkpoint laden.",
            tituloRondas = "Rundenlimit", txtRondas = "Runden", txtIndefinido = "Unbegrenzt", tituloTiempo = "Zeitlimit",
            txtMinutos = "Minuten", txtSinLimite = "Kein Limit", btnIniciarPartida = "SPIEL STARTEN", btnIniciaAqui = "STARTEN SIE HIER!",
            msgTutorialJugar = "Starte das Spiel, um fortzufahren, oder überspringe.", dialogoSalirTitulo = "Ohne Speichern beenden?",
            dialogoSalirDesc = "Nicht gespeicherte Änderungen gehen verloren.",
            btnGuardarPrimero = "ZUERST SPEICHERN", btnIgnorarSalir = "IGNORIEREN UND BEENDEN", btnCancelar = "ABBRECHEN",
            dialogoGestionTitulo = "Fortschrittsverwaltung", dialogoGestionDesc = "Möchten Sie ein Spiel fortsetzen oder neu beginnen?",
            btnCargarPartida = "SPIEL LADEN", btnEmpezarCero = "NEU STARTEN", dialogoIncompatibleTitulo = "Inkompatibler Checkpoint",
            dialogoIncompatibleDesc = "Deaktivieren mit aktivem Checkpoint nicht möglich. Zuerst speichern?",
            btnGuardarProgreso = "FORTSCHRITT SPEICHERN", btnDescartarDesactivar = "VERWERFEN UND DEAKTIVIEREN", dialogoGuardarCpTitulo = "Checkpoint speichern",
            labelNombreCp = "Name des Checkpoints", txtActualizaExistente = "Oder existierenden aktualisieren:", txtActualizar = "Aktualisieren:",
            msgCpActualizado = "Checkpoint aktualisiert", btnCrearNuevo = "NEU ERSTELLEN", msgCpGuardado = "Neuer Checkpoint gespeichert",
            dialogoCargarCpTitulo = "Checkpoint laden", txtNoCps = "Keine Checkpoints für diese Liste.", msgProgresoCargado = "Fortschritt von",
            msgCargadoExito = "geladen", btnCerrar = "SCHLIESSEN"
        )
        IdiomaSoportado.CHINO -> TextosConfiguracion(
            tituloConfiguracion = "设置", tituloJugadores = "玩家", descJugadores = "已添加（至少 3 人）",
            errorMinJugadores = "玩家不足。至少需要 3 人。", tituloImpostores = "卧底", descImpostores = "每 3 名玩家最多 1 名",
            tituloPista = "卧底线索", descPista = "将收到一个模糊的线索", tituloNoRepetir = "不重复单词",
            descNoRepetir = "避免出现以前游戏中的单词", restantes = "剩余：", btnCargar = "加载", btnGuardar = "保存",
            checkpointActivo = "当前存档：", errorNoPalabras = "没有新词了。更改选项或加载其他存档。",
            tituloRondas = "回合限制", txtRondas = "回合", txtIndefinido = "无限制", tituloTiempo = "时间限制",
            txtMinutos = "分钟", txtSinLimite = "无限制", btnIniciarPartida = "开始游戏", btnIniciaAqui = "从这里开始！",
            msgTutorialJugar = "开始游戏以继续教程或跳过。", dialogoSalirTitulo = "不保存并退出？",
            dialogoSalirDesc = "未保存的更改将丢失。",
            btnGuardarPrimero = "先保存", btnIgnorarSalir = "忽略并退出", btnCancelar = "取消",
            dialogoGestionTitulo = "进度管理", dialogoGestionDesc = "您想恢复以前的游戏还是重新开始？",
            btnCargarPartida = "加载游戏", btnEmpezarCero = "重新开始", dialogoIncompatibleTitulo = "不兼容的存档",
            dialogoIncompatibleDesc = "使用存档时无法禁用。是否先保存当前进度？",
            btnGuardarProgreso = "保存进度", btnDescartarDesactivar = "放弃并禁用", dialogoGuardarCpTitulo = "保存存档",
            labelNombreCp = "存档名称", txtActualizaExistente = "或更新现有存档：", txtActualizar = "更新：",
            msgCpActualizado = "存档已更新", btnCrearNuevo = "创建新存档", msgCpGuardado = "新存档已保存",
            dialogoCargarCpTitulo = "加载存档", txtNoCps = "此列表没有存档。", msgProgresoCargado = "",
            msgCargadoExito = "的进度已加载", btnCerrar = "关闭"
        )
        IdiomaSoportado.JAPONES -> TextosConfiguracion(
            tituloConfiguracion = "設定", tituloJugadores = "プレイヤー", descJugadores = "追加済み（最低3人）",
            errorMinJugadores = "プレイヤーが足りません。最低3人必要です。", tituloImpostores = "インポスター", descImpostores = "プレイヤー3人につき最大1人",
            tituloPista = "インポスターへのヒント", descPista = "曖昧なヒントを受け取ります", tituloNoRepetir = "単語を繰り返さない",
            descNoRepetir = "以前のゲームの単語を避けます", restantes = "残り:", btnCargar = "ロード", btnGuardar = "保存",
            checkpointActivo = "アクティブなチェックポイント:", errorNoPalabras = "新しい単語がありません。オプションを変更するかチェックポイントをロードしてください。",
            tituloRondas = "ラウンド制限", txtRondas = "ラウンド", txtIndefinido = "無制限", tituloTiempo = "時間制限",
            txtMinutos = "分", txtSinLimite = "制限なし", btnIniciarPartida = "ゲーム開始", btnIniciaAqui = "ここから開始！",
            msgTutorialJugar = "ゲームを開始してチュートリアルを続けるか、スキップしてください。", dialogoSalirTitulo = "保存せずに終了しますか？",
            dialogoSalirDesc = "保存されていない変更は失われます。",
            btnGuardarPrimero = "先に保存する", btnIgnorarSalir = "無視して終了", btnCancelar = "キャンセル",
            dialogoGestionTitulo = "進行状況の管理", dialogoGestionDesc = "以前のゲームを再開しますか、それとも最初から始めますか？",
            btnCargarPartida = "ゲームをロード", btnEmpezarCero = "最初から始める", dialogoIncompatibleTitulo = "互換性のないチェックポイント",
            dialogoIncompatibleDesc = "チェックポイント使用中は無効にできません。先に進行状況を保存しますか？",
            btnGuardarProgreso = "進行状況を保存", btnDescartarDesactivar = "破棄して無効にする", dialogoGuardarCpTitulo = "チェックポイントを保存",
            labelNombreCp = "チェックポイント名", txtActualizaExistente = "または既存のものを更新:", txtActualizar = "更新:",
            msgCpActualizado = "チェックポイントが更新されました", btnCrearNuevo = "新規作成", msgCpGuardado = "新しいチェックポイントが保存されました",
            dialogoCargarCpTitulo = "チェックポイントをロード", txtNoCps = "このリストのチェックポイントはありません。", msgProgresoCargado = "",
            msgCargadoExito = "の進行状況をロードしました", btnCerrar = "閉じる"
        )
        // INGLÉS POR DEFECTO
        else -> TextosConfiguracion(
            tituloConfiguracion = "Settings", tituloJugadores = "Players", descJugadores = "added (Min 3)",
            errorMinJugadores = "Not enough players. Minimum 3.", tituloImpostores = "Impostors", descImpostores = "Max 1 per 3 players",
            tituloPista = "Clue for Impostor", descPista = "Will receive a vague clue", tituloNoRepetir = "Don't repeat words",
            descNoRepetir = "Avoids words from previous games", restantes = "Remaining:", btnCargar = "Load", btnGuardar = "Save",
            checkpointActivo = "Active checkpoint:", errorNoPalabras = "No new words left. Change option or load another checkpoint.",
            tituloRondas = "Round Limit", txtRondas = "rounds", txtIndefinido = "Unlimited", tituloTiempo = "Time Limit",
            txtMinutos = "minutes", txtSinLimite = "No limit", btnIniciarPartida = "START GAME", btnIniciaAqui = "START HERE!",
            msgTutorialJugar = "Start the game to continue the tutorial or skip it.", dialogoSalirTitulo = "Exit without saving?",
            dialogoSalirDesc = "Unsaved changes will be lost.",
            btnGuardarPrimero = "SAVE FIRST", btnIgnorarSalir = "IGNORE AND EXIT", btnCancelar = "CANCEL",
            dialogoGestionTitulo = "Progress Management", dialogoGestionDesc = "Do you want to resume a game or start a new one?",
            btnCargarPartida = "LOAD GAME", btnEmpezarCero = "START FROM SCRATCH", dialogoIncompatibleTitulo = "Incompatible Checkpoint",
            dialogoIncompatibleDesc = "Cannot disable while using a checkpoint. Save progress first?",
            btnGuardarProgreso = "SAVE PROGRESS", btnDescartarDesactivar = "DISCARD AND DISABLE", dialogoGuardarCpTitulo = "Save Checkpoint",
            labelNombreCp = "Checkpoint Name", txtActualizaExistente = "Or update an existing one:", txtActualizar = "Update:",
            msgCpActualizado = "Checkpoint updated in the cloud", btnCrearNuevo = "CREATE NEW", msgCpGuardado = "New checkpoint saved",
            dialogoCargarCpTitulo = "Load Checkpoint", txtNoCps = "No checkpoints for this list.", msgProgresoCargado = "Progress of",
            msgCargadoExito = "loaded", btnCerrar = "CLOSE"
        )
    }
}