package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosJuego(
    val txtDesliza: String,
    val txtTema: String,
    val rolImpostor: String,
    val rolCivil: String,
    val txtPista: String,
    val txtNoTeDescubras: String,
    val txtPalabra: String,
    val btnMiraRol: String,
    val btnComenzar: String,
    val btnSiguiente: String,
    val txtTurnoHablar: String,
    val btnSiguienteHablante: String,
    val btnVotarImpostor: String,
    val msgTiempoAgotadoDebate: String,
    val msgLimiteRondas: String,
    val tituloDescubierto: String,
    val descDescubierto: String,
    val btnIntentarAdivinar: String,
    val txtCuidado15s: String,
    val btnRendirse: String,
    val msgRendido: String,
    val txtRapido: String,
    val placeholderBuscar: String,
    val msgTiempoAgotadoAdivinar: String,
    val msgImpostorAdivina1: String,
    val msgImpostorAdivina2: String,
    val msgImpostorFalla1: String,
    val msgImpostorFalla2: String,
    val txtVictoriaPara: String,
    val txtVictoriaCiviles: String,
    val txtVictoriaImpostores: String,
    val txtPalabraSecreta: String,
    val txtImpostores: String,
    val btnFinalizarPrueba: String,
    val btnVolverMenu: String,
    val msgAtrapado: String,
    val msgErrorInocente1: String,
    val msgErrorInocente2: String,
    val tituloVotar: String,
    val descVotar: String,
    val btnVolver: String,
    val btnRevelar: String,
    val dialogoSalirTutTitulo: String,
    val dialogoSalirTutDesc: String,
    val btnEntendido: String,
    val txtRonda: String,
    val btnPartidaInvalida: String,
    val tituloConfirmarSalir: String,
    val descConfirmarSalir: String,
    val tituloConfirmarAnular: String,
    val descConfirmarAnular: String,
    val btnConfirmar: String,
    val btnCancelar: String
)

fun obtenerTextosJuego(idioma: IdiomaSoportado): TextosJuego {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosJuego(
            txtDesliza = "Desliza para ver tu rol", txtTema = "TEMA:", rolImpostor = "IMPOSTOR", rolCivil = "CIVIL",
            txtPista = "Pista:", txtNoTeDescubras = "¡No te descubras!", txtPalabra = "Palabra:",
            btnMiraRol = "MIRA TU ROL", btnComenzar = "COMENZAR", btnSiguiente = "SIGUIENTE",
            txtTurnoHablar = "Turno de hablar:", btnSiguienteHablante = "SIGUIENTE HABLANTE", btnVotarImpostor = "VOTAR IMPOSTOR",
            msgTiempoAgotadoDebate = "¡Se agotó el tiempo! Los impostores han ganado por sigilo.", msgLimiteRondas = "¡Límite de rondas alcanzado! Los impostores ganan.",
            tituloDescubierto = "¡IMPOSTOR DESCUBIERTO!", descDescubierto = "Pero espera... El impostor tiene una última oportunidad para robar la victoria si adivina la palabra secreta.",
            btnIntentarAdivinar = "INTENTAR ADIVINAR", txtCuidado15s = "¡Cuidado! Solo tendrás 15 segundos",
            btnRendirse = "RENDIRSE", msgRendido = "El impostor se ha rendido. ¡Victoria total para los civiles!",
            txtRapido = "¡RÁPIDO!", placeholderBuscar = "Buscar palabra...", msgTiempoAgotadoAdivinar = "¡Se agotó el tiempo! El impostor no logró adivinar la palabra.",
            msgImpostorAdivina1 = "¡Increíble! El impostor adivinó la palabra (", msgImpostorAdivina2 = ") y ha robado la victoria.",
            msgImpostorFalla1 = "El impostor pensó que era '", msgImpostorFalla2 = "' y falló. ¡Los civiles ganan!",
            txtVictoriaPara = "VICTORIA PARA", txtVictoriaCiviles = "CIVILES", txtVictoriaImpostores = "IMPOSTORES",
            txtPalabraSecreta = "Palabra secreta:\n", txtImpostores = "Impostores:\n",
            btnFinalizarPrueba = "FINALIZAR PARTIDA DE PRUEBA", btnVolverMenu = "VOLVER AL MENÚ",
            msgAtrapado = "Habéis atrapado a ", msgErrorInocente1 = "¡ERROR! ", msgErrorInocente2 = " era inocente. Los impostores ganan por votación errónea.",
            tituloVotar = "¿Quién es el impostor?", descVotar = "Si falláis, perderéis la partida.", btnVolver = "VOLVER", btnRevelar = "REVELAR",
            dialogoSalirTutTitulo = "¡Termina la partida!", dialogoSalirTutDesc = "Estás en la recta final del tutorial. Termina la partida de prueba para ver cómo funciona todo el ciclo, o pulsa 'OMITIR TUTORIAL' arriba.",
            btnEntendido = "ENTENDIDO", txtRonda = "Ronda",
            btnPartidaInvalida = "PARTIDA NO VÁLIDA", tituloConfirmarSalir = "¿Salir de la partida?",
            descConfirmarSalir = "¿Estás seguro de que quieres salir y volver a la configuración de la partida?",
            tituloConfirmarAnular = "¿Anular esta partida?",
            descConfirmarAnular = "Esta partida no contará y la palabra secreta volverá a estar disponible en la biblioteca sin gastarse. ¿Deseas continuar?",
            btnConfirmar = "CONFIRMAR", btnCancelar = "CANCELAR"
        )
        IdiomaSoportado.FRANCES -> TextosJuego(
            txtDesliza = "Glissez pour voir votre rôle", txtTema = "THÈME :", rolImpostor = "IMPOSTEUR", rolCivil = "CIVIL",
            txtPista = "Indice :", txtNoTeDescubras = "Ne vous faites pas démasquer !", txtPalabra = "Mot :",
            btnMiraRol = "VOIR LE RÔLE", btnComenzar = "COMMENCER", btnSiguiente = "SUIVANT",
            txtTurnoHablar = "Au tour de :", btnSiguienteHablante = "ORATEUR SUIVANT", btnVotarImpostor = "VOTER L'IMPOSTEUR",
            msgTiempoAgotadoDebate = "Temps écoulé ! Les imposteurs ont gagné par furtivité.", msgLimiteRondas = "Limite de manches atteinte ! Les imposteurs gagnent.",
            tituloDescubierto = "IMPOSTEUR DÉCOUVERT !", descDescubierto = "Attendez... L'imposteur a une dernière chance de voler la victoire en devinant le mot secret.",
            btnIntentarAdivinar = "TENTER DE DEVINER", txtCuidado15s = "Attention ! Vous n'avez que 15 secondes",
            btnRendirse = "SE RENDRE", msgRendido = "L'imposteur a abandonné. Victoire totale des civils !",
            txtRapido = "VITE !", placeholderBuscar = "Chercher un mot...", msgTiempoAgotadoAdivinar = "Temps écoulé ! L'imposteur n'a pas trouvé le mot.",
            msgImpostorAdivina1 = "Incroyable ! L'imposteur a deviné le mot (", msgImpostorAdivina2 = ") et a volé la victoire.",
            msgImpostorFalla1 = "L'imposteur pensait que c'était '", msgImpostorFalla2 = "' et a échoué. Les civils gagnent !",
            txtVictoriaPara = "VICTOIRE DES", txtVictoriaCiviles = "CIVILS", txtVictoriaImpostores = "IMPOSTEURS",
            txtPalabraSecreta = "Mot secret :\n", txtImpostores = "Imposteurs :\n",
            btnFinalizarPrueba = "TERMINER LE TEST", btnVolverMenu = "RETOUR AU MENU",
            msgAtrapado = "Vous avez attrapé ", msgErrorInocente1 = "ERREUR ! ", msgErrorInocente2 = " était innocent. Les imposteurs gagnent par erreur de vote.",
            tituloVotar = "Qui est l'imposteur ?", descVotar = "Si vous vous trompez, vous perdez.", btnVolver = "RETOUR", btnRevelar = "RÉVÉLER",
            dialogoSalirTutTitulo = "Terminez la partie !", dialogoSalirTutDesc = "Vous êtes à la fin du tutoriel. Finissez pour voir tout le cycle, ou passez-le.",
            btnEntendido = "COMPRIS", txtRonda = "Manche",
            btnPartidaInvalida = "MATCH INVALIDE", tituloConfirmarSalir = "Quitter la partie ?",
            descConfirmarSalir = "Êtes-vous sûr de vouloir quitter et revenir à la configuration du jeu ?",
            tituloConfirmarAnular = "Annuler la partie ?",
            descConfirmarAnular = "Ce match ne comptera pas et le mot secret sera à nouveau disponible. Voulez-vous continuer ?",
            btnConfirmar = "CONFIRMER", btnCancelar = "ANNULER"
        )
        IdiomaSoportado.ITALIANO -> TextosJuego(
            txtDesliza = "Scorri per vedere il tuo ruolo", txtTema = "TEMA:", rolImpostor = "IMPOSTORE", rolCivil = "CIVILE",
            txtPista = "Indizio:", txtNoTeDescubras = "Non farti scoprire!", txtPalabra = "Parola:",
            btnMiraRol = "VEDI RUOLO", btnComenzar = "INIZIA", btnSiguiente = "AVANTI",
            txtTurnoHablar = "Turno di:", btnSiguienteHablante = "PROSSIMO GIOCATORE", btnVotarImpostor = "VOTA L'IMPOSTORE",
            msgTiempoAgotadoDebate = "Tempo scaduto! Gli impostori vincono nascondendosi.", msgLimiteRondas = "Limite round raggiunto! Gli impostori vincono.",
            tituloDescubierto = "IMPOSTORE SCOPERTO!", descDescubierto = "Ma aspetta... L'impostore ha un'ultima possibilità per vincere indovinando la parola segreta.",
            btnIntentarAdivinar = "TENTA DI INDOVINARE", txtCuidado15s = "Attenzione! Hai solo 15 secondi",
            btnRendirse = "ARRENDITI", msgRendido = "L'impostore si è arreso. Vittoria totale per i civili!",
            txtRapido = "PRESTO!", placeholderBuscar = "Cerca parola...", msgTiempoAgotadoAdivinar = "Tempo scaduto! L'impostore non ha indovinato.",
            msgImpostorAdivina1 = "Incredibile! L'impostore ha indovinato (", msgImpostorAdivina2 = ") e ha rubato la vittoria.",
            msgImpostorFalla1 = "L'impostore pensava fosse '", msgImpostorFalla2 = "' e ha sbagliato. I civili vincono!",
            txtVictoriaPara = "VITTORIA DEI", txtVictoriaCiviles = "CIVILI", txtVictoriaImpostores = "IMPOSTORI",
            txtPalabraSecreta = "Parola segreta:\n", txtImpostores = "Impostori:\n",
            btnFinalizarPrueba = "TERMINA PARTITA PROVA", btnVolverMenu = "TORNA AL MENU",
            msgAtrapado = "Avete catturato ", msgErrorInocente1 = "ERRORE! ", msgErrorInocente2 = " era inocente. Gli impostori vincono per voto errato.",
            tituloVotar = "Chi è l'impostore?", descVotar = "Se sbagliate, perdete la partita.", btnVolver = "INDIETRO", btnRevelar = "RIVELA",
            dialogoSalirTutTitulo = "Finisci la partita!", dialogoSalirTutDesc = "Sei alla fine del tutorial. Concludi la partita per vedere il ciclo completo o saltalo.",
            btnEntendido = "CAPITO", txtRonda = "Round",
            btnPartidaInvalida = "PARTITA NON VALIDA", tituloConfirmarSalir = "Uscire dalla partita?",
            descConfirmarSalir = "Sei sicuro di voler uscire e tornare alla configurazione del gioco?",
            tituloConfirmarAnular = "Annullare la partita?",
            descConfirmarAnular = "Questa partita non conterà e la parola segreta sarà di nuovo disponible. Vuoi continuare?",
            btnConfirmar = "CONFERMA", btnCancelar = "ANNULER"
        )
        IdiomaSoportado.ALEMAN -> TextosJuego(
            txtDesliza = "Wische, um deine Rolle zu sehen", txtTema = "THEMA:", rolImpostor = "IMPOSTOR", rolCivil = "ZIVILIST",
            txtPista = "Hinweis:", txtNoTeDescubras = "Lass dich nicht erwischen!", txtPalabra = "Wort:",
            btnMiraRol = "ROLLE ANSEHEN", btnComenzar = "START", btnSiguiente = "WEITER",
            txtTurnoHablar = "Am Zug:", btnSiguienteHablante = "NÄCHSTER REDNER", btnVotarImpostor = "IMPOSTOR WÄHLEN",
            msgTiempoAgotadoDebate = "Zeit abgelaufen! Die Impostors haben unbemerkt gewonnen.", msgLimiteRondas = "Rundenlimit erreicht! Die Impostors gewinnen.",
            tituloDescubierto = "IMPOSTOR ENTLARVT!", descDescubierto = "Aber warte... Der Impostor hat eine letzte Chance zu gewinnen, wenn er das geheime Wort errät.",
            btnIntentarAdivinar = "VERSUCHEN ZU ERRATEN", txtCuidado15s = "Achtung! Du hast nur 15 Sekunden",
            btnRendirse = "AUFGEBEN", msgRendido = "Der Impostor hat aufgegeben. Totaler Sieg für die Zivilisten!",
            txtRapido = "SCHNELL!", placeholderBuscar = "Wort suchen...", msgTiempoAgotadoAdivinar = "Zeit abgelaufen! Der Impostor konnte das Wort nicht erraten.",
            msgImpostorAdivina1 = "Unglaublich! Der Impostor hat das Wort (", msgImpostorAdivina2 = ") erraten und den Sieg gestohlen.",
            msgImpostorFalla1 = "Der Impostor dachte es sei '", msgImpostorFalla2 = "' und lag falsch. Die Zivilisten gewinnen!",
            txtVictoriaPara = "SIEG FÜR", txtVictoriaCiviles = "ZIVILISTEN", txtVictoriaImpostores = "IMPOSTORS",
            txtPalabraSecreta = "Geheimes Wort:\n", txtImpostores = "Impostors:\n",
            btnFinalizarPrueba = "TESTSPIEL BEENDEN", btnVolverMenu = "ZURÜCK ZUM MENÜ",
            msgAtrapado = "Ihr habt gefangen: ", msgErrorInocente1 = "FEHLER! ", msgErrorInocente2 = " war unschuldig. Die Impostors gewinnen durch falsche Wahl.",
            tituloVotar = "Wer ist der Impostor?", descVotar = "Wenn ihr falsch liegt, verliert ihr.", btnVolver = "ZURÜCK", btnRevelar = "ENTHÜLLEN",
            dialogoSalirTutTitulo = "Beende das Spiel!", dialogoSalirTutDesc = "Du bist am Ende des Tutorials. Beende das Testspiel oder überspringe es.",
            btnEntendido = "VERSTANDEN", txtRonda = "Runde",
            btnPartidaInvalida = "UNGÜLTIGES SPIEL", tituloConfirmarSalir = "Spiel verlassen?",
            descConfirmarSalir = "Bist du sicher, dass du das Spiel verlassen und zur Konfiguration zurückkehren möchtest?",
            tituloConfirmarAnular = "Spiel annullieren?",
            descConfirmarAnular = "Dieses Spiel wird nicht gezählt und das geheime Wort ist wieder verfügbar. Möchtest du fortfahren?",
            btnConfirmar = "BESTÄTIGEN", btnCancelar = "ABBRECHEN"
        )
        IdiomaSoportado.CHINO -> TextosJuego(
            txtDesliza = "滑动查看您的角色", txtTema = "主题：", rolImpostor = "卧底", rolCivil = "平民",
            txtPista = "线索：", txtNoTeDescubras = "不要暴露自己！", txtPalabra = "单词：",
            btnMiraRol = "查看角色", btnComenzar = "开始", btnSiguiente = "下一个",
            txtTurnoHablar = "轮到：", btnSiguienteHablante = "下一个发言者", btnVotarImpostor = "投票选出卧底",
            msgTiempoAgotadoDebate = "时间到！卧底隐蔽地赢得了比赛。", msgLimiteRondas = "达到回合限制！卧底获胜。",
            tituloDescubierto = "卧底被发现了！", descDescubierto = "但是等等……如果卧底猜出秘密单词，他们还有最后一次窃取胜利的机会。",
            btnIntentarAdivinar = "尝试猜测", txtCuidado15s = "小心！您只有15秒的时间",
            btnRendirse = "投降", msgRendido = "卧底已经投降。平民大获全胜！",
            txtRapido = "快点！", placeholderBuscar = "搜索单词...", msgTiempoAgotadoAdivinar = "时间到！卧底未能猜出单词。",
            msgImpostorAdivina1 = "难以置信！卧底猜出了单词 (", msgImpostorAdivina2 = ") 并窃取了胜利。",
            msgImpostorFalla1 = "卧底以为是 '", msgImpostorFalla2 = "'，但猜错了。平民获胜！",
            txtVictoriaPara = "胜利者：", txtVictoriaCiviles = "平民", txtVictoriaImpostores = "卧底",
            txtPalabraSecreta = "秘密单词：\n", txtImpostores = "卧底：\n",
            btnFinalizarPrueba = "结束测试游戏", btnVolverMenu = "返回菜单",
            msgAtrapado = "你们抓住了 ", msgErrorInocente1 = "错误！", msgErrorInocente2 = " 是无辜的。卧底因错误投票而获胜。",
            tituloVotar = "谁是卧底？", descVotar = "如果失败，你们将输掉比赛。", btnVolver = "返回", btnRevelar = "揭晓",
            dialogoSalirTutTitulo = "结束游戏！", dialogoSalirTutDesc = "您正处于教程的最后阶段。完成测试游戏以了解其运作方式，或点击上面的跳过。",
            btnEntendido = "明白了", txtRonda = "回合",
            btnPartidaInvalida = "无效对局", tituloConfirmarSalir = "退出游戏？",
            descConfirmarSalir = "您确定要退出并返回配置界面吗？",
            tituloConfirmarAnular = "取消本局？",
            descConfirmarAnular = "本局将不计入统计，秘密单词将重新放回牌堆。是否继续？",
            btnConfirmar = "确认", btnCancelar = "取消"
        )
        IdiomaSoportado.JAPONES -> TextosJuego(
            txtDesliza = "スワイプして役割を確認", txtTema = "テーマ:", rolImpostor = "インポスター", rolCivil = "市民",
            txtPista = "ヒント:", txtNoTeDescubras = "正体を隠せ！", txtPalabra = "単語:",
            btnMiraRol = "役割を見る", btnComenzar = "開始", btnSiguiente = "次へ",
            txtTurnoHablar = "発言の順番:", btnSiguienteHablante = "次の発言者", btnVotarImpostor = "インポスターに投票",
            msgTiempoAgotadoDebate = "時間切れ！インポスターが密かに勝利しました。", msgLimiteRondas = "ラウンド制限に達しました！インポスターの勝利です。",
            tituloDescubierto = "インポスター発見！", descDescubierto = "待って... インポスターが秘密の単語を当てれば逆転勝利のチャンスがあります。",
            btnIntentarAdivinar = "推測に挑戦", txtCuidado15s = "注意！15秒しかありません",
            btnRendirse = "降参する", msgRendido = "インポスターが降参しました。市民の完全勝利です！",
            txtRapido = "急いで！", placeholderBuscar = "単語を検索...", msgTiempoAgotadoAdivinar = "時間切れ！インポスターは単語を当てられませんでした。",
            msgImpostorAdivina1 = "信じられない！インポスターは単語 (", msgImpostorAdivina2 = ") を当てて勝利を奪いました。",
            msgImpostorFalla1 = "インポスターは「", msgImpostorFalla2 = "」だと思いましたが外れました。市民の勝利！",
            txtVictoriaPara = "勝利:", txtVictoriaCiviles = "市民", txtVictoriaImpostores = "インポスター",
            txtPalabraSecreta = "秘密の単語:\n", txtImpostores = "インポスター:\n",
            btnFinalizarPrueba = "テストゲームを終了", btnVolverMenu = "メニューに戻る",
            msgAtrapado = "捕まえたのは: ", msgErrorInocente1 = "エラー！", msgErrorInocente2 = " は無実でした。誤った投票によりインポスターの勝利です。",
            tituloVotar = "インポスターは誰ですか？", descVotar = "間違えるとゲームに負けます。", btnVolver = "戻る", btnRevelar = "公開する",
            dialogoSalirTutTitulo = "ゲームを完了してください！", dialogoSalirTutDesc = "チュートリアルの最終段階です。テストゲームを完了するか、スキップしてください。",
            btnEntendido = "了解", txtRonda = "ラウンド",
            btnPartidaInvalida = "試合を無効にする", tituloConfirmarSalir = "ゲームを終了しますか？",
            descConfirmarSalir = "終了して設定画面に戻ってもよろしいですか？",
            tituloConfirmarAnular = "試合を無効にしますか？",
            descConfirmarAnular = "この試合はカウントされず、秘密の単語は再び利用可能になります。続行しますか？",
            btnConfirmar = "確認", btnCancelar = "キャンセル"
        )
        else -> TextosJuego(
            txtDesliza = "Swipe to see your role", txtTema = "THEME:", rolImpostor = "IMPOSTOR", rolCivil = "CIVILIAN",
            txtPista = "Clue:", txtNoTeDescubras = "Don't blow your cover!", txtPalabra = "Word:",
            btnMiraRol = "VIEW ROLE", btnComenzar = "START", btnSiguiente = "NEXT",
            txtTurnoHablar = "Turn to speak:", btnSiguienteHablante = "NEXT SPEAKER", btnVotarImpostor = "VOTE IMPOSTOR",
            msgTiempoAgotadoDebate = "Time's up! The impostors won by stealth.", msgLimiteRondas = "Round limit reached! The impostors win.",
            tituloDescubierto = "IMPOSTOR DISCOVERED!", descDescubierto = "But wait... The impostor has one last chance to steal the win by guessing the secret word.",
            btnIntentarAdivinar = "TRY TO GUESS", txtCuidado15s = "Careful! You only have 15 seconds",
            btnRendirse = "SURRENDER", msgRendido = "The impostor surrendered. Total victory for civilians!",
            txtRapido = "QUICK!", placeholderBuscar = "Search word...", msgTiempoAgotadoAdivinar = "Time's up! The impostor failed to guess the word.",
            msgImpostorAdivina1 = "Incredible! The impostor guessed the word (", msgImpostorAdivina2 = ") and stole the victory.",
            msgImpostorFalla1 = "The impostor thought it was '", msgImpostorFalla2 = "' and failed. Civilians win!",
            txtVictoriaPara = "VICTORY FOR", txtVictoriaCiviles = "CIVILIANS", txtVictoriaImpostores = "IMPOSTORS",
            txtPalabraSecreta = "Secret word:\n", txtImpostores = "Impostors:\n",
            btnFinalizarPrueba = "FINISH TEST GAME", btnVolverMenu = "RETURN TO MENU",
            msgAtrapado = "You caught ", msgErrorInocente1 = "ERROR! ", msgErrorInocente2 = " was innocent. Impostors win by wrong vote.",
            tituloVotar = "Who is the impostor?", descVotar = "If you fail, you lose the game.", btnVolver = "BACK", btnRevelar = "REVEAL",
            dialogoSalirTutTitulo = "Finish the game!", dialogoSalirTutDesc = "You are in the final stretch of the tutorial. Finish the test game to see how it works, or tap SKIP TUTORIAL.",
            btnEntendido = "GOT IT", txtRonda = "Round",
            btnPartidaInvalida = "INVALID MATCH", tituloConfirmarSalir = "Exit game?",
            descConfirmarSalir = "Are you sure you want to exit and return to configuration?",
            tituloConfirmarAnular = "Void this match?",
            descConfirmarAnular = "This match won't count and the secret word will be available again without being spent. Do you want to continue?",
            btnConfirmar = "CONFIRM", btnCancelar = "CANCEL"
        )
    }
}