package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosPerfil(
    val tituloMiPerfil: String,
    val btnCerrarSesion: String,
    val btnEliminarCuenta: String,
    val tituloSincroniza: String,
    val descSincroniza: String,
    val btnIniciarSesion: String,
    val anadirDescripcion: String,
    val seguidores: String,
    val siguiendo: String,
    val misCreaciones: String,
    val sinListas: String,
    val buscarListas: String,
    val filtroNuevas: String,
    val filtroPopulares: String,
    val filtroMayorMenor: String,
    val filtroMenorMayor: String,
    val sinResultados: String,
    val sinUsuariosLista: String,
    val tituloInvitar: String,
    val descInvitar1: String,
    val descInvitar2: String,
    val buscarInvestigador: String,
    val sinInvestigadores: String,
    val btnInvitar: String,
    val tituloPersonas: String,
    val buscarUsuarios: String,
    val descPersonas1: String,
    val descPersonas2: String,
    val sinOtrosUsuarios: String,
    val rolCreador: String,
    val rolColaborador: String,
    val rolEspera: String,
    val tituloFoto: String,
    val opcionGaleria: String,
    val descGaleria: String,
    val opcionInternet: String,
    val descInternet: String,
    val tituloAvatar: String,
    val btnCerrar: String,
    val btnGuardar: String,
    val tituloAbandonar: String,
    val tituloEliminarCol: String,
    val descAbandonar1: String,
    val descAbandonar2: String,
    val descEliminarCol: String,
    val btnAbandonar: String,
    val btnEliminar: String,
    val btnCancelar: String,
    val tituloCerrar: String,
    val descCerrar: String,
    val tituloEliminar: String,
    val descEliminar: String,
    val btnBorrarTodo: String,
    val tituloNombre: String,
    val labelApodo: String,
    val btnConfirmar: String,
    val tituloMigracion: String,
    val descMigracion: String,
    val btnDescartar: String,
    val tituloSobreMi: String,
    val placeholderSobreMi: String,
    val etiquetaColaborativa: String,
    val etiquetaPublica: String,
    val etiquetaPrivada: String,
    val pal: String,
    val msgFotoExito: String,
    val msgFotoError: String,
    val msgBienvenidoNuevo: String,
    val msgBienvenido: String,
    val msgSincronizado: String,
    val msgDescExito: String,
    val msgInvitacionEnviada: String,
    val msgErrorInvitacion: String,
    val msgExpulsado: String,
    val errorMinLetras: String,
    val errorNombreUso: String
)

fun obtenerTextosPerfil(idioma: IdiomaSoportado): TextosPerfil {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosPerfil(
            tituloMiPerfil = "Mi Perfil", btnCerrarSesion = "Cerrar sesión", btnEliminarCuenta = "Eliminar cuenta",
            tituloSincroniza = "¡Sincroniza tus datos!", descSincroniza = "Guarda tus listas y progreso en la nube.", btnIniciarSesion = "INICIAR SESIÓN",
            anadirDescripcion = "Añadir descripción sobre mí...", seguidores = "Seguidores", siguiendo = "Siguiendo",
            misCreaciones = "Mis Creaciones", sinListas = "No tienes listas aún.", buscarListas = "Buscar tus listas...",
            filtroNuevas = "Nuevas", filtroPopulares = "Populares", filtroMayorMenor = "Mayor a menor", filtroMenorMayor = "Menor a mayor",
            sinResultados = "No se encontraron resultados.", sinUsuariosLista = "No hay usuarios en esta lista.",
            tituloInvitar = "Invitar Colaborador", descInvitar1 = "Añade a alguien para que te ayude a rellenar '", descInvitar2 = "'.",
            buscarInvestigador = "Nombre del investigador...", sinInvestigadores = "No se encontró a nadie o ya tienen invitación.", btnInvitar = "INVITAR",
            tituloPersonas = "Personas en esta lista", buscarUsuarios = "Buscar usuarios por nombre...", descPersonas1 = "Usuarios que pueden editar '", descPersonas2 = "':",
            sinOtrosUsuarios = "No se encontraron otros usuarios.", rolCreador = "Creador", rolColaborador = "Colaborador", rolEspera = "En espera de respuesta...",
            tituloFoto = "Actualizar foto de perfil", opcionGaleria = "Elegir de la galería", descGaleria = "Se comprimirá automáticamente",
            opcionInternet = "Buscar en Internet", descInternet = "Elegir un avatar predefinido", tituloAvatar = "Elige tu avatar", btnCerrar = "Cerrar", btnGuardar = "GUARDAR",
            tituloAbandonar = "¿Abandonar colaboración?", tituloEliminarCol = "¿Eliminar colección?",
            descAbandonar1 = "¿Seguro que quieres dejar de colaborar en '", descAbandonar2 = "'? Perderás el acceso.",
            descEliminarCol = "¿Estás seguro de que quieres borrar la lista de la nube? No se puede deshacer.",
            btnAbandonar = "ABANDONAR", btnEliminar = "ELIMINAR", btnCancelar = "CANCELAR",
            tituloCerrar = "¿Cerrar sesión?", descCerrar = "Se borrarán los datos temporales. Tus listas seguirán en la nube.",
            tituloEliminar = "⚠️ ELIMINAR CUENTA", descEliminar = "Acción IRREVERSIBLE. Se borrarán tus listas, tu nombre y progreso para siempre.", btnBorrarTodo = "BORRAR TODO",
            tituloNombre = "Nombre de investigador", labelApodo = "Tu apodo único", btnConfirmar = "CONFIRMAR",
            tituloMigracion = "¿Guardar listas locales?", descMigracion = "Tienes listas locales. ¿Quieres subirlas a tu cuenta de Google?", btnDescartar = "DESCARTAR LOCALES",
            tituloSobreMi = "Sobre mí", placeholderSobreMi = "¿Qué te gusta hacer? ¿Qué listas sueles crear?...",
            etiquetaColaborativa = "Colaborativa", etiquetaPublica = "Pública", etiquetaPrivada = "Privada", pal = "pal.",
            msgFotoExito = "Foto de perfil actualizada correctamente", msgFotoError = "Error al subir la foto",
            msgBienvenidoNuevo = "¡Bienvenido de nuevo!", msgBienvenido = "¡Bienvenido", msgSincronizado = "¡Todo sincronizado!", msgDescExito = "Descripción actualizada",
            msgInvitacionEnviada = "Invitación enviada a", msgErrorInvitacion = "Error al enviar invitación", msgExpulsado = "Expulsado a",
            errorMinLetras = "Mínimo 3 letras", errorNombreUso = "Nombre en uso"
        )
        IdiomaSoportado.FRANCES -> TextosPerfil(
            tituloMiPerfil = "Mon Profil", btnCerrarSesion = "Se déconnecter", btnEliminarCuenta = "Supprimer le compte",
            tituloSincroniza = "Synchronisez vos données !", descSincroniza = "Sauvegardez vos listes et votre progression.", btnIniciarSesion = "SE CONNECTER",
            anadirDescripcion = "Ajouter une description de moi...", seguidores = "Abonnés", siguiendo = "Abonnements",
            misCreaciones = "Mes Créations", sinListas = "Vous n'avez pas encore de listes.", buscarListas = "Rechercher vos listes...",
            filtroNuevas = "Nouvelles", filtroPopulares = "Populaires", filtroMayorMenor = "Plus au Moins", filtroMenorMayor = "Moins au Plus",
            sinResultados = "Aucun résultat trouvé.", sinUsuariosLista = "Aucun utilisateur dans cette liste.",
            tituloInvitar = "Inviter un Collaborateur", descInvitar1 = "Ajoutez quelqu'un pour vous aider avec '", descInvitar2 = "'.",
            buscarInvestigador = "Nom de l'enquêteur...", sinInvestigadores = "Personne trouvée ou déjà invité.", btnInvitar = "INVITER",
            tituloPersonas = "Personnes dans cette liste", buscarUsuarios = "Rechercher des utilisateurs...", descPersonas1 = "Utilisateurs pouvant éditer '", descPersonas2 = "':",
            sinOtrosUsuarios = "Aucun autre utilisateur trouvé.", rolCreador = "Créateur", rolColaborador = "Collaborateur", rolEspera = "En attente de réponse...",
            tituloFoto = "Mettre à jour la photo", opcionGaleria = "Choisir dans la galerie", descGaleria = "Sera compressé automatiquement",
            opcionInternet = "Chercher sur Internet", descInternet = "Choisir un avatar prédéfini", tituloAvatar = "Choisissez votre avatar", btnCerrar = "Fermer", btnGuardar = "ENREGISTRER",
            tituloAbandonar = "Quitter la collaboration ?", tituloEliminarCol = "Supprimer la collection ?",
            descAbandonar1 = "Voulez-vous vraiment quitter '", descAbandonar2 = "' ? Vous perdrez l'accès.",
            descEliminarCol = "Voulez-vous vraiment supprimer la liste ? Action irréversible.",
            btnAbandonar = "QUITTER", btnEliminar = "SUPPRIMER", btnCancelar = "ANNULER",
            tituloCerrar = "Se déconnecter ?", descCerrar = "Les données temporaires seront effacées. Vos listes resteront dans le cloud.",
            tituloEliminar = "⚠️ SUPPRIMER LE COMPTE", descEliminar = "Action IRRÉVERSIBLE. Vos listes, nom et progression seront effacés à jamais.", btnBorrarTodo = "TOUT SUPPRIMER",
            tituloNombre = "Nom d'enquêteur", labelApodo = "Votre pseudo unique", btnConfirmar = "CONFIRMER",
            tituloMigracion = "Sauvegarder les listes locales ?", descMigracion = "Voulez-vous télécharger vos listes locales sur Google ?", btnDescartar = "IGNORER",
            tituloSobreMi = "À propos de moi", placeholderSobreMi = "Qu'aimez-vous faire ? Quelles listes créez-vous ?...",
            etiquetaColaborativa = "Collaborative", etiquetaPublica = "Publique", etiquetaPrivada = "Privée", pal = "mots",
            msgFotoExito = "Photo mise à jour avec succès", msgFotoError = "Erreur lors du téléchargement",
            msgBienvenidoNuevo = "De retour !", msgBienvenido = "Bienvenue", msgSincronizado = "Tout est synchronisé !", msgDescExito = "Description mise à jour",
            msgInvitacionEnviada = "Invitation envoyée à", msgErrorInvitacion = "Erreur d'envoi", msgExpulsado = "Expulsé",
            errorMinLetras = "Minimum 3 lettres", errorNombreUso = "Nom déjà utilisé"
        )
        IdiomaSoportado.ITALIANO -> TextosPerfil(
            tituloMiPerfil = "Il Mio Profilo", btnCerrarSesion = "Esci", btnEliminarCuenta = "Elimina account",
            tituloSincroniza = "Sincronizza i tuoi dati!", descSincroniza = "Salva le tue liste e i progressi nel cloud.", btnIniciarSesion = "ACCEDI",
            anadirDescripcion = "Aggiungi descrizione su di me...", seguidores = "Follower", siguiendo = "Seguiti",
            misCreaciones = "Le Mie Creazioni", sinListas = "Non hai ancora liste.", buscarListas = "Cerca le tue liste...",
            filtroNuevas = "Nuove", filtroPopulares = "Popolari", filtroMayorMenor = "Maggiore a minore", filtroMenorMayor = "Minore a maggiore",
            sinResultados = "Nessun risultato trovato.", sinUsuariosLista = "Nessun utente in questa lista.",
            tituloInvitar = "Invita Collaboratore", descInvitar1 = "Aggiungi qualcuno per aiutarti con '", descInvitar2 = "'.",
            buscarInvestigador = "Nome dell'investigatore...", sinInvestigadores = "Nessuno trovato o già invitato.", btnInvitar = "INVITA",
            tituloPersonas = "Persone in questa lista", buscarUsuarios = "Cerca utenti per nome...", descPersonas1 = "Utenti che possono modificare '", descPersonas2 = "':",
            sinOtrosUsuarios = "Nessun altro utente trovato.", rolCreador = "Creatore", rolColaborador = "Collaboratore", rolEspera = "In attesa di risposta...",
            tituloFoto = "Aggiorna foto profilo", opcionGaleria = "Scegli dalla galleria", descGaleria = "Verrà compressa automaticamente",
            opcionInternet = "Cerca su Internet", descInternet = "Scegli un avatar predefinito", tituloAvatar = "Scegli il tuo avatar", btnCerrar = "Chiudi", btnGuardar = "SALVA",
            tituloAbandonar = "Abbandonare collaborazione?", tituloEliminarCol = "Eliminare collezione?",
            descAbandonar1 = "Sicuro di voler abbandonare '", descAbandonar2 = "'? Perderai l'accesso.",
            descEliminarCol = "Sicuro di voler eliminare la lista dal cloud? Non si può annullare.",
            btnAbandonar = "ABBANDONA", btnEliminar = "ELIMINA", btnCancelar = "ANNULLA",
            tituloCerrar = "Uscire?", descCerrar = "I dati temporanei verranno cancellati. Le liste resteranno nel cloud.",
            tituloEliminar = "⚠️ ELIMINA ACCOUNT", descEliminar = "Azione IRREVERSIBILE. Le tue liste, il nome e i progressi verranno cancellati per sempre.", btnBorrarTodo = "CANCELLA TUTTO",
            tituloNombre = "Nome investigatore", labelApodo = "Il tuo nickname unico", btnConfirmar = "CONFERMA",
            tituloMigracion = "Salvare liste locali?", descMigracion = "Hai liste locali. Vuoi caricarle sul tuo account Google?", btnDescartar = "SCARTA LOCALI",
            tituloSobreMi = "Su di me", placeholderSobreMi = "Cosa ti piace fare? Che liste crei di solito?...",
            etiquetaColaborativa = "Collaborativa", etiquetaPublica = "Pubblica", etiquetaPrivada = "Privata", pal = "par.",
            msgFotoExito = "Foto profilo aggiornata", msgFotoError = "Errore durante il caricamento",
            msgBienvenidoNuevo = "Bentornato!", msgBienvenido = "Benvenuto", msgSincronizado = "Tutto sincronizzato!", msgDescExito = "Descrizione aggiornata",
            msgInvitacionEnviada = "Invito inviato a", msgErrorInvitacion = "Errore invio invito", msgExpulsado = "Espulso",
            errorMinLetras = "Minimo 3 lettere", errorNombreUso = "Nome in uso"
        )
        IdiomaSoportado.ALEMAN -> TextosPerfil(
            tituloMiPerfil = "Mein Profil", btnCerrarSesion = "Abmelden", btnEliminarCuenta = "Konto löschen",
            tituloSincroniza = "Daten synchronisieren!", descSincroniza = "Speichere deine Listen in der Cloud.", btnIniciarSesion = "ANMELDEN",
            anadirDescripcion = "Beschreibung hinzufügen...", seguidores = "Follower", siguiendo = "Folge ich",
            misCreaciones = "Meine Kreationen", sinListas = "Du hast noch keine Listen.", buscarListas = "Deine Listen suchen...",
            filtroNuevas = "Neue", filtroPopulares = "Beliebte", filtroMayorMenor = "Absteigend", filtroMenorMayor = "Aufsteigend",
            sinResultados = "Keine Ergebnisse gefunden.", sinUsuariosLista = "Keine Benutzer in dieser Liste.",
            tituloInvitar = "Mitarbeiter einladen", descInvitar1 = "Füge jemanden hinzu für '", descInvitar2 = "'.",
            buscarInvestigador = "Name des Ermittlers...", sinInvestigadores = "Niemand gefunden oder bereits eingeladen.", btnInvitar = "EINLADEN",
            tituloPersonas = "Personen in dieser Liste", buscarUsuarios = "Benutzer suchen...", descPersonas1 = "Benutzer, die '", descPersonas2 = "' bearbeiten können:",
            sinOtrosUsuarios = "Keine anderen Benutzer gefunden.", rolCreador = "Ersteller", rolColaborador = "Mitarbeiter", rolEspera = "Warte auf Antwort...",
            tituloFoto = "Profilbild aktualisieren", opcionGaleria = "Aus Galerie wählen", descGaleria = "Wird automatisch komprimiert",
            opcionInternet = "Im Internet suchen", descInternet = "Vorgefertigten Avatar wählen", tituloAvatar = "Wähle deinen Avatar", btnCerrar = "Schließen", btnGuardar = "SPEICHERN",
            tituloAbandonar = "Zusammenarbeit verlassen?", tituloEliminarCol = "Sammlung löschen?",
            descAbandonar1 = "Wirklich verlassen: '", descAbandonar2 = "'? Du verlierst den Zugriff.",
            descEliminarCol = "Wirklich aus der Cloud löschen? Kann nicht rückgängig gemacht werden.",
            btnAbandonar = "VERLASSEN", btnEliminar = "LÖSCHEN", btnCancelar = "ABBRECHEN",
            tituloCerrar = "Abmelden?", descCerrar = "Temporäre Daten werden gelöscht. Listen bleiben in der Cloud.",
            tituloEliminar = "⚠️ KONTO LÖSCHEN", descEliminar = "IRREVERSIBEL. Deine Listen, Name und Fortschritt werden für immer gelöscht.", btnBorrarTodo = "ALLES LÖSCHEN",
            tituloNombre = "Ermittlername", labelApodo = "Dein einzigartiger Spitzname", btnConfirmar = "BESTÄTIGEN",
            tituloMigracion = "Lokale Listen speichern?", descMigracion = "Du hast lokale Listen. In Google-Konto hochladen?", btnDescartar = "LOKALE VERWERFEN",
            tituloSobreMi = "Über mich", placeholderSobreMi = "Was machst du gerne? Welche Listen erstellst du?...",
            etiquetaColaborativa = "Kollaborativ", etiquetaPublica = "Öffentlich", etiquetaPrivada = "Privat", pal = "Wört.",
            msgFotoExito = "Profilbild erfolgreich aktualisiert", msgFotoError = "Fehler beim Hochladen",
            msgBienvenidoNuevo = "Willkommen zurück!", msgBienvenido = "Willkommen", msgSincronizado = "Alles synchronisiert!", msgDescExito = "Beschreibung aktualisiert",
            msgInvitacionEnviada = "Einladung gesendet an", msgErrorInvitacion = "Fehler beim Senden", msgExpulsado = "Hinausgeworfen",
            errorMinLetras = "Mindestens 3 Buchstaben", errorNombreUso = "Name vergeben"
        )
        IdiomaSoportado.CHINO -> TextosPerfil(
            tituloMiPerfil = "我的个人资料", btnCerrarSesion = "登出", btnEliminarCuenta = "删除账号",
            tituloSincroniza = "同步您的数据！", descSincroniza = "将您的列表保存在云端。", btnIniciarSesion = "登录",
            anadirDescripcion = "添加关于我的描述...", seguidores = "粉丝", siguiendo = "关注",
            misCreaciones = "我的创作", sinListas = "您还没有列表。", buscarListas = "搜索您的列表...",
            filtroNuevas = "最新", filtroPopulares = "热门", filtroMayorMenor = "从多到少", filtroMenorMayor = "从少到多",
            sinResultados = "未找到结果。", sinUsuariosLista = "此列表中没有用户。",
            tituloInvitar = "邀请合作者", descInvitar1 = "添加某人来帮助您完成 '", descInvitar2 = "'。",
            buscarInvestigador = "调查员名称...", sinInvestigadores = "未找到任何人或已邀请。", btnInvitar = "邀请",
            tituloPersonas = "此列表中的人", buscarUsuarios = "搜索用户...", descPersonas1 = "可以编辑 '", descPersonas2 = "' 的用户：",
            sinOtrosUsuarios = "未找到其他用户。", rolCreador = "创建者", rolColaborador = "合作者", rolEspera = "等待回复...",
            tituloFoto = "更新头像", opcionGaleria = "从图库中选择", descGaleria = "将自动压缩",
            opcionInternet = "在互联网上搜索", descInternet = "选择预设头像", tituloAvatar = "选择您的头像", btnCerrar = "关闭", btnGuardar = "保存",
            tituloAbandonar = "放弃合作？", tituloEliminarCol = "删除集合？",
            descAbandonar1 = "确定要离开 '", descAbandonar2 = "' 吗？您将失去访问权限。",
            descEliminarCol = "确定要从云端删除吗？此操作无法撤销。",
            btnAbandonar = "离开", btnEliminar = "删除", btnCancelar = "取消",
            tituloCerrar = "登出？", descCerrar = "临时数据将被删除。您的列表将保留在云端。",
            tituloEliminar = "⚠️ 删除账号", descEliminar = "不可逆操作。您的列表、名称和进度将永远被删除。", btnBorrarTodo = "删除全部",
            tituloNombre = "调查员名称", labelApodo = "您的唯一昵称", btnConfirmar = "确认",
            tituloMigracion = "保存本地列表？", descMigracion = "您有本地列表。要将它们上传到 Google 账号吗？", btnDescartar = "放弃本地",
            tituloSobreMi = "关于我", placeholderSobreMi = "您喜欢做什么？您通常创建什么列表？...",
            etiquetaColaborativa = "合作", etiquetaPublica = "公开", etiquetaPrivada = "私密", pal = "词",
            msgFotoExito = "头像更新成功", msgFotoError = "上传出错",
            msgBienvenidoNuevo = "欢迎回来！", msgBienvenido = "欢迎", msgSincronizado = "全部同步成功！", msgDescExito = "描述已更新",
            msgInvitacionEnviada = "邀请已发送给", msgErrorInvitacion = "发送邀请时出错", msgExpulsado = "已踢出",
            errorMinLetras = "至少 3 个字母", errorNombreUso = "名称已被使用"
        )
        IdiomaSoportado.JAPONES -> TextosPerfil(
            tituloMiPerfil = "マイプロフィール", btnCerrarSesion = "ログアウト", btnEliminarCuenta = "アカウントを削除",
            tituloSincroniza = "データを同期！", descSincroniza = "リストと進行状況をクラウドに保存します。", btnIniciarSesion = "ログイン",
            anadirDescripcion = "自己紹介を追加...", seguidores = "フォロワー", siguiendo = "フォロー中",
            misCreaciones = "マイクリエーション", sinListas = "まだリストがありません。", buscarListas = "リストを検索...",
            filtroNuevas = "新着", filtroPopulares = "人気", filtroMayorMenor = "多い順", filtroMenorMayor = "少ない順",
            sinResultados = "結果が見つかりませんでした。", sinUsuariosLista = "このリストにはユーザーがいません。",
            tituloInvitar = "コラボレーターを招待", descInvitar1 = "リスト '", descInvitar2 = "' を手伝ってくれる人を追加します。",
            buscarInvestigador = "調査員の名前...", sinInvestigadores = "誰も見つからないか、すでに招待されています。", btnInvitar = "招待する",
            tituloPersonas = "このリストのメンバー", buscarUsuarios = "ユーザーを検索...", descPersonas1 = "リスト '", descPersonas2 = "' を編集できるユーザー:",
            sinOtrosUsuarios = "他のユーザーは見つかりませんでした。", rolCreador = "作成者", rolColaborador = "コラボレーター", rolEspera = "返答待ち...",
            tituloFoto = "プロフィール写真を更新", opcionGaleria = "ギャラリーから選択", descGaleria = "自動的に圧縮されます",
            opcionInternet = "インターネットで検索", descInternet = "プリセットアバターを選択", tituloAvatar = "アバターを選択", btnCerrar = "閉じる", btnGuardar = "保存",
            tituloAbandonar = "コラボを終了しますか？", tituloEliminarCol = "コレクションを削除しますか？",
            descAbandonar1 = "本当に '", descAbandonar2 = "' のコラボを終了しますか？アクセス権を失います。",
            descEliminarCol = "本当にクラウドからリストを削除しますか？元に戻すことはできません。",
            btnAbandonar = "終了する", btnEliminar = "削除する", btnCancelar = "キャンセル",
            tituloCerrar = "ログアウトしますか？", descCerrar = "一時データは削除されます。リストはクラウドに残ります。",
            tituloEliminar = "⚠️ アカウントを削除", descEliminar = "取り返しのつかない操作です。リスト、名前、進行状況は永遠に消去されます。", btnBorrarTodo = "すべて削除",
            tituloNombre = "調査員の名前", labelApodo = "あなただけのニックネーム", btnConfirmar = "確認",
            tituloMigracion = "ローカルリストを保存しますか？", descMigracion = "ローカルリストがあります。Googleアカウントにアップロードしますか？", btnDescartar = "破棄する",
            tituloSobreMi = "自己紹介", placeholderSobreMi = "何をするのが好きですか？どんなリストを作りますか？...",
            etiquetaColaborativa = "コラボ", etiquetaPublica = "公開", etiquetaPrivada = "非公開", pal = "単語",
            msgFotoExito = "プロフィール写真が更新されました", msgFotoError = "アップロードエラー",
            msgBienvenidoNuevo = "お帰りなさい！", msgBienvenido = "ようこそ", msgSincronizado = "すべて同期されました！", msgDescExito = "自己紹介を更新しました",
            msgInvitacionEnviada = "招待を送信しました:", msgErrorInvitacion = "招待の送信エラー", msgExpulsado = "追放しました:",
            errorMinLetras = "最低3文字", errorNombreUso = "すでに使われています"
        )
        // INGLÉS POR DEFECTO
        else -> TextosPerfil(
            tituloMiPerfil = "My Profile", btnCerrarSesion = "Log out", btnEliminarCuenta = "Delete account",
            tituloSincroniza = "Sync your data!", descSincroniza = "Save your lists and progress in the cloud.", btnIniciarSesion = "LOG IN",
            anadirDescripcion = "Add description about me...", seguidores = "Followers", siguiendo = "Following",
            misCreaciones = "My Creations", sinListas = "You don't have any lists yet.", buscarListas = "Search your lists...",
            filtroNuevas = "New", filtroPopulares = "Popular", filtroMayorMenor = "Most to least", filtroMenorMayor = "Least to most",
            sinResultados = "No results found.", sinUsuariosLista = "No users in this list.",
            tituloInvitar = "Invite Collaborator", descInvitar1 = "Add someone to help you fill '", descInvitar2 = "'.",
            buscarInvestigador = "Investigator's name...", sinInvestigadores = "No one found or already invited.", btnInvitar = "INVITE",
            tituloPersonas = "People in this list", buscarUsuarios = "Search users by name...", descPersonas1 = "Users who can edit '", descPersonas2 = "':",
            sinOtrosUsuarios = "No other users found.", rolCreador = "Creator", rolColaborador = "Collaborator", rolEspera = "Waiting for reply...",
            tituloFoto = "Update profile photo", opcionGaleria = "Choose from gallery", descGaleria = "Will be compressed automatically",
            opcionInternet = "Search the Internet", descInternet = "Choose a preset avatar", tituloAvatar = "Choose your avatar", btnCerrar = "Close", btnGuardar = "SAVE",
            tituloAbandonar = "Leave collaboration?", tituloEliminarCol = "Delete collection?",
            descAbandonar1 = "Are you sure you want to leave '", descAbandonar2 = "'? You will lose access.",
            descEliminarCol = "Are you sure you want to delete the list from the cloud? Cannot be undone.",
            btnAbandonar = "LEAVE", btnEliminar = "DELETE", btnCancelar = "CANCEL",
            tituloCerrar = "Log out?", descCerrar = "Temporary data will be deleted. Your lists will remain in the cloud.",
            tituloEliminar = "⚠️ DELETE ACCOUNT", descEliminar = "IRREVERSIBLE action. Your lists, name, and progress will be deleted forever.", btnBorrarTodo = "DELETE EVERYTHING",
            tituloNombre = "Investigator name", labelApodo = "Your unique nickname", btnConfirmar = "CONFIRM",
            tituloMigracion = "Save local lists?", descMigracion = "You have local lists. Do you want to upload them to your Google account?", btnDescartar = "DISCARD LOCAL",
            tituloSobreMi = "About me", placeholderSobreMi = "What do you like doing? What lists do you create?...",
            etiquetaColaborativa = "Collaborative", etiquetaPublica = "Public", etiquetaPrivada = "Private", pal = "wds.",
            msgFotoExito = "Profile photo updated successfully", msgFotoError = "Error uploading photo",
            msgBienvenidoNuevo = "Welcome back!", msgBienvenido = "Welcome", msgSincronizado = "Everything synced!", msgDescExito = "Description updated",
            msgInvitacionEnviada = "Invitation sent to", msgErrorInvitacion = "Error sending invitation", msgExpulsado = "Kicked",
            errorMinLetras = "Minimum 3 letters", errorNombreUso = "Name taken"
        )
    }
}