package org.example.project.Datos.TextosTraducidos

import org.example.project.Datos.IdiomaSoportado

data class TextosCrear(
    val cargandoTaller: String,
    val tituloEditar: String,
    val tituloNueva: String,
    val btnGuardar: String,
    val placeholderBuscar: String,
    val labelNombreLista: String,
    val labelCategoria: String,
    val tituloPublica: String,
    val tituloPrivada: String,
    val descPublica: String,
    val descPrivada: String,
    val etiquetaPalabraIndividual: String,
    val labelPalabra: String,
    val labelPistas: String,
    val placeholderPalabra: String,
    val placeholderGrupo: String,
    val labelNombreGrupo: String,
    val btnAnadirPalabraGrupo: String,
    val btnAnadirPalabra: String,
    val btnAnadirGrupo: String,
    val tituloDialogoPublicar: String,
    val tituloDialogoPrivar: String,
    val descDialogoPublicar: String,
    val descDialogoPrivar: String,
    val btnConfirmar: String,
    val btnCancelar: String,
    val tituloSeleccionarImagen: String,
    val btnCerrar: String,
    val btnSaveImagen: String,
    val tituloEliminarElemento: String,
    val tituloBorrarPalabra: String,
    val tituloBorrarGrupo: String,
    val descEliminarElemento: String,
    val btnEliminar: String,
    val tituloImportar: String,
    val descImportar: String,
    val placeholderImportar: String,
    val btnProcesar: String,
    val tituloConflictos: String,
    val descConflictos: String,
    val btnReemplazar: String,
    val btnOmitirNuevas: String,
    val btnAnadirTodo: String,
    val btnCancelarImportacion: String,
    val msgSalirTutorial: String,
    val msgGuardarTutorial: String,
    val msgMinimoPalabras: String,
    val msgFaltanCampos: String,
    val msgImportExito: String,
    val msgSesionPublicar: String,
    val msgSesionPrimero: String,
    val msgImagenSelec: String,
    val msgAbrirImagen: String,
    val errorRepetida: String
)

fun obtenerTextosCrear(idioma: IdiomaSoportado): TextosCrear {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosCrear(
            cargandoTaller = "Preparando el taller...", tituloEditar = "Editar Lista", tituloNueva = "Nueva Lista", btnGuardar = "GUARDAR",
            placeholderBuscar = "Buscar palabra, pista o grupo...", labelNombreLista = "Nombre de la Lista", labelCategoria = "Categoría (Ej: Películas)",
            tituloPublica = "Lista Pública", tituloPrivada = "Lista Privada", descPublica = "Cualquiera podrá encontrarla y jugarla", descPrivada = "Solo tú puedes ver esta lista",
            etiquetaPalabraIndividual = "Palabra Individual", labelPalabra = "Palabra Secreta", labelPistas = "Pista(s) separadas por coma",
            placeholderPalabra = "Palabra", placeholderGrupo = "Grupo de palabras...", labelNombreGrupo = "Nombre de este Grupo",
            btnAnadirPalabraGrupo = "AÑADIR PALABRA AL GRUPO", btnAnadirPalabra = "+ PALABRA", btnAnadirGrupo = "+ GRUPO",
            tituloDialogoPublicar = "¿Publicar esta lista?", tituloDialogoPrivar = "¿Hacer privada?",
            descDialogoPublicar = "Al publicar esta lista, cualquier persona en la comunidad podrá verla, jugarla y descargarla. Tu nombre de investigador aparecerá como el creador oficial.\n\nPodrás deshacer esto más adelante.",
            descDialogoPrivar = "Si haces esta lista privada, desaparecerá inmediatamente del explorador de la comunidad y solo tú podrás verla o jugarla.",
            btnConfirmar = "CONFIRMAR", btnCancelar = "CANCELAR", tituloSeleccionarImagen = "Selecciona una imagen", btnCerrar = "Cerrar", btnSaveImagen = "GUARDAR",
            tituloEliminarElemento = "¿Eliminar ", tituloBorrarPalabra = "Palabra Individual", tituloBorrarGrupo = "Grupo Completo",
            descEliminarElemento = "¿Estás seguro de que quieres borrar este elemento? Se perderán todos los datos.", btnEliminar = "ELIMINAR",
            tituloImportar = "Importar Palabras", descImportar = "Normas de formato:\nSi la palabra empieza por (.) y no tiene (,) será el nombre de un Grupo. Cada palabra acompañada con (,) que se ponga debajo de un grupo se asociara como palabra y pistas y para finalizar el grupo se pone un (.) en la pista final de la ultima palabra. Si son palabras individuales bastará con poner el nombre y las pistas fuera de cualquier grupo.\n\nPega el texto como el formato de ejemplo:\n.Animales\nPerro, Pista1,Pista2,Pista3\nGato, Pista1,Pista2,Pista3.\n\nCarretera, Pista1,Pista2,Pista3.",
            placeholderImportar = "Pega aquí...", btnProcesar = "PROCESAR", tituloConflictos = "¡Palabras repetidas!", descConflictos = "Algunas de las palabras que intentas importar ya existen. ¿Qué deseas hacer?",
            btnReemplazar = "Reemplazar antiguas", btnOmitirNuevas = "Omitir nuevas repetidas", btnAnadirTodo = "Añadir todo y editar manual", btnCancelarImportacion = "CANCELAR IMPORTACIÓN",
            msgSalirTutorial = "Para salir, pulsa 'Omitir Tutorial' arriba a la derecha.", msgGuardarTutorial = "Guarda tu lista con 3 palabras para continuar.",
            msgMinimoPalabras = "Para el tutorial, añade al menos 3 palabras de prueba.", msgFaltanCampos = "Faltan campos por rellenar o hay errores",
            msgImportExito = "Elementos importados con éxito", msgSesionPublicar = "Debes iniciar sesión para publicar listas.", msgSesionPrimero = "Inicia sesión primero.",
            msgImagenSelec = "Imagen seleccionada", msgAbrirImagen = "Abre la imagen en grande primero", errorRepetida = "Repetida"
        )
        IdiomaSoportado.FRANCES -> TextosCrear(
            cargandoTaller = "Préparation de l'atelier...", tituloEditar = "Modifier la liste", tituloNueva = "Nouvelle liste", btnGuardar = "SAUVEGARDER",
            placeholderBuscar = "Chercher mot, indice ou groupe...", labelNombreLista = "Nom de la liste", labelCategoria = "Catégorie (Ex: Films)",
            tituloPublica = "Liste Publique", tituloPrivada = "Liste Privée", descPublica = "Tout le monde pourra la trouver et y jouer", descPrivada = "Seul vous pouvez voir cette liste",
            etiquetaPalabraIndividual = "Mot individuel", labelPalabra = "Mot secret", labelPistas = "Indice(s) séparés par une virgule",
            placeholderPalabra = "Mot", placeholderGrupo = "Groupe de mots...", labelNombreGrupo = "Nom de ce groupe",
            btnAnadirPalabraGrupo = "AJOUTER UN MOT AU GROUPE", btnAnadirPalabra = "+ MOT", btnAnadirGrupo = "+ GROUPE",
            tituloDialogoPublicar = "Publier cette liste ?", tituloDialogoPrivar = "Rendre privée ?",
            descDialogoPublicar = "En publiant cette liste, toute la communauté pourra la voir. Votre nom apparaîtra comme créateur.\n\nVous pourrez annuler cela plus tard.",
            descDialogoPrivar = "Si vous rendez cette liste privée, elle disparaîtra de la communauté et vous seul pourrez y jouer.",
            btnConfirmar = "CONFIRMER", btnCancelar = "ANNULER", tituloSeleccionarImagen = "Sélectionner une image", btnCerrar = "Fermer", btnSaveImagen = "SAUVER",
            tituloEliminarElemento = "Supprimer ", tituloBorrarPalabra = "Mot individuel", tituloBorrarGrupo = "Groupe complet",
            descEliminarElemento = "Êtes-vous sûr de vouloir supprimer cet élément ? Toutes les données seront perdues.", btnEliminar = "SUPPRIMER",
            tituloImportar = "Importer des mots", descImportar = "Règles de format:\nCommencez par (.) sans (,) pour un Groupe. Les mots avec (,) sous un groupe s'y ajoutent. Finissez avec (.) sur le dernier indice. En dehors des groupes, ce sont des mots individuels.\n\nExemple:\n.Animaux\nChien, Indice1,Indice2\nChat, Indice1,Indice2.",
            placeholderImportar = "Collez ici...", btnProcesar = "TRAITER", tituloConflictos = "Mots répétés !", descConflictos = "Certains mots importés existent déjà. Que voulez-vous faire ?",
            btnReemplazar = "Remplacer les anciens", btnOmitirNuevas = "Ignorer les nouveaux", btnAnadirTodo = "Tout ajouter et éditer", btnCancelarImportacion = "ANNULER L'IMPORTATION",
            msgSalirTutorial = "Pour quitter, appuyez sur 'Ignorer le tutoriel' en haut à droite.", msgGuardarTutorial = "Sauvegardez votre liste avec 3 mots pour continuer.",
            msgMinimoPalabras = "Pour le tutoriel, ajoutez au moins 3 mots de test.", msgFaltanCampos = "Il manque des champs ou il y a des erreurs",
            msgImportExito = "Éléments importés avec succès", msgSesionPublicar = "Connectez-vous pour publier des listes.", msgSesionPrimero = "Connectez-vous d'abord.",
            msgImagenSelec = "Image sélectionnée", msgAbrirImagen = "Ouvrez l'image en grand d'abord", errorRepetida = "Répété"
        )
        IdiomaSoportado.ITALIANO -> TextosCrear(
            cargandoTaller = "Preparazione del laboratorio...", tituloEditar = "Modifica Lista", tituloNueva = "Nuova Lista", btnGuardar = "SALVA",
            placeholderBuscar = "Cerca parola, indizio o gruppo...", labelNombreLista = "Nome della Lista", labelCategoria = "Categoria (Es: Film)",
            tituloPublica = "Lista Pubblica", tituloPrivada = "Lista Privata", descPublica = "Chiunque potrà trovarla e giocarci", descPrivada = "Solo tu puoi vedere questa lista",
            etiquetaPalabraIndividual = "Parola Individuale", labelPalabra = "Parola Segreta", labelPistas = "Indizio/i separati da virgola",
            placeholderPalabra = "Parola", placeholderGrupo = "Gruppo di parole...", labelNombreGrupo = "Nome di questo gruppo",
            btnAnadirPalabraGrupo = "AGGIUNGI PAROLA AL GRUPPO", btnAnadirPalabra = "+ PAROLA", btnAnadirGrupo = "+ GRUPPO",
            tituloDialogoPublicar = "Pubblicare questa lista?", tituloDialogoPrivar = "Rendere privata?",
            descDialogoPublicar = "Pubblicando questa lista, chiunque nella community potrà vederla e giocarci. Il tuo nome apparirà come creatore.\n\nPotrai annullarlo in seguito.",
            descDialogoPrivar = "Se rendi questa lista privata, scomparirà dalla community e solo tu potrai vederla.",
            btnConfirmar = "CONFERMA", btnCancelar = "ANNULLA", tituloSeleccionarImagen = "Seleziona un'immagine", btnCerrar = "Chiudi", btnSaveImagen = "SALVA",
            tituloEliminarElemento = "Eliminare ", tituloBorrarPalabra = "Parola Individuale", tituloBorrarGrupo = "Gruppo Completo",
            descEliminarElemento = "Sei sicuro di voler eliminare questo elemento? Tutti i dati andranno persi.", btnEliminar = "ELIMINA",
            tituloImportar = "Importa Parole", descImportar = "Regole di formato:\nInizia con (.) senza (,) per un Gruppo. Parole con (,) sotto un gruppo vi appartengono. Termina con (.) sull'ultimo indizio. Fuori dai gruppi sono parole individuali.\n\nEsempio:\n.Animali\nCane, Indizio1,Indizio2\nGatto, Indizio1,Indizio2.",
            placeholderImportar = "Incolla qui...", btnProcesar = "ELABORA", tituloConflictos = "Parole ripetute!", descConflictos = "Alcune parole importate esistono già. Cosa vuoi fare?",
            btnReemplazar = "Sostituisci vecchie", btnOmitirNuevas = "Ignora nuove", btnAnadirTodo = "Aggiungi tutto e modifica", btnCancelarImportacion = "ANNULLA IMPORTAZIONE",
            msgSalirTutorial = "Per uscire, premi 'Ignora Tutorial' in alto a destra.", msgGuardarTutorial = "Salva la lista con 3 parole per continuare.",
            msgMinimoPalabras = "Per il tutorial, aggiungi almeno 3 parole di prova.", msgFaltanCampos = "Campi mancanti o errori presenti",
            msgImportExito = "Elementi importati con successo", msgSesionPublicar = "Devi accedere per pubblicare le liste.", msgSesionPrimero = "Accedi prima.",
            msgImagenSelec = "Immagine selezionata", msgAbrirImagen = "Apri l'immagine in grande prima", errorRepetida = "Ripetuta"
        )
        IdiomaSoportado.ALEMAN -> TextosCrear(
            cargandoTaller = "Werkstatt wird vorbereitet...", tituloEditar = "Liste bearbeiten", tituloNueva = "Neue Liste", btnGuardar = "SPEICHERN",
            placeholderBuscar = "Wort, Hinweis oder Gruppe suchen...", labelNombreLista = "Name der Liste", labelCategoria = "Kategorie (Z.B.: Filme)",
            tituloPublica = "Öffentliche Liste", tituloPrivada = "Private Liste", descPublica = "Jeder kann sie finden und spielen", descPrivada = "Nur du kannst diese Liste sehen",
            etiquetaPalabraIndividual = "Einzelnes Wort", labelPalabra = "Geheimes Wort", labelPistas = "Hinweis(e) durch Komma getrennt",
            placeholderPalabra = "Wort", placeholderGrupo = "Wortgruppe...", labelNombreGrupo = "Name dieser Gruppe",
            btnAnadirPalabraGrupo = "WORT ZUR GRUPPE HINZUFÜGEN", btnAnadirPalabra = "+ WORT", btnAnadirGrupo = "+ GRUPPE",
            tituloDialogoPublicar = "Diese Liste veröffentlichen?", tituloDialogoPrivar = "Privat machen?",
            descDialogoPublicar = "Wenn du diese Liste veröffentlichst, kann jeder in der Community sie sehen und spielen. Dein Name wird als Ersteller angezeigt.\n\nDu kannst dies später rückgängig machen.",
            descDialogoPrivar = "Wenn du diese Liste privat machst, verschwindet sie aus der Community und nur du kannst sie sehen.",
            btnConfirmar = "BESTÄTIGEN", btnCancelar = "ABBRECHEN", tituloSeleccionarImagen = "Wähle ein Bild", btnCerrar = "Schließen", btnSaveImagen = "SPEICHERN",
            tituloEliminarElemento = "Löschen: ", tituloBorrarPalabra = "Einzelnes Wort", tituloBorrarGrupo = "Komplette Gruppe",
            descEliminarElemento = "Bist du sicher, dass du dieses Element löschen willst? Alle Daten gehen verloren.", btnEliminar = "LÖSCHEN",
            tituloImportar = "Wörter importieren", descImportar = "Formatregeln:\nBeginne mit (.) ohne (,) für eine Gruppe. Wörter mit (,) unter einer Gruppe gehören dazu. Beende mit (.) beim letzten Hinweis. Außerhalb von Gruppen sind es einzelne Wörter.\n\nBeispiel:\n.Tiere\nHund, Hinweis1,Hinweis2\nKatze, Hinweis1,Hinweis2.",
            placeholderImportar = "Hier einfügen...", btnProcesar = "VERARBEITEN", tituloConflictos = "Wiederholte Wörter!", descConflictos = "Einige zu importierende Wörter existieren bereits. Was möchtest du tun?",
            btnReemplazar = "Alte ersetzen", btnOmitirNuevas = "Neue ignorieren", btnAnadirTodo = "Alle hinzufügen und bearbeiten", btnCancelarImportacion = "IMPORT ABBRECHEN",
            msgSalirTutorial = "Drücke 'Tutorial überspringen' oben rechts, um zu beenden.", msgGuardarTutorial = "Speichere die Liste mit 3 Wörtern, um fortzufahren.",
            msgMinimoPalabras = "Füge für das Tutorial mindestens 3 Testwörter hinzu.", msgFaltanCampos = "Fehlende Felder oder Fehler vorhanden",
            msgImportExito = "Elemente erfolgreich importiert", msgSesionPublicar = "Du musst dich anmelden, um Listen zu veröffentlichen.", msgSesionPrimero = "Zuerst anmelden.",
            msgImagenSelec = "Bild ausgewählt", msgAbrirImagen = "Öffne das Bild zuerst in groß", errorRepetida = "Wiederholt"
        )
        IdiomaSoportado.CHINO -> TextosCrear(
            cargandoTaller = "正在准备工作坊...", tituloEditar = "编辑列表", tituloNueva = "新列表", btnGuardar = "保存",
            placeholderBuscar = "搜索单词、线索或群组...", labelNombreLista = "列表名称", labelCategoria = "类别 (例如：电影)",
            tituloPublica = "公开列表", tituloPrivada = "私人列表", descPublica = "任何人都可以找到并游玩它", descPrivada = "只有您可以查看此列表",
            etiquetaPalabraIndividual = "单个单词", labelPalabra = "秘密单词", labelPistas = "线索（用逗号分隔）",
            placeholderPalabra = "单词", placeholderGrupo = "单词组...", labelNombreGrupo = "该组的名称",
            btnAnadirPalabraGrupo = "将单词添加到组", btnAnadirPalabra = "+ 单词", btnAnadirGrupo = "+ 组",
            tituloDialogoPublicar = "发布此列表？", tituloDialogoPrivar = "设为私有？",
            descDialogoPublicar = "发布此列表后，社区中的任何人都可以看到并游玩它。您的名字将作为创作者显示。\n\n您可以稍后撤消此操作。",
            descDialogoPrivar = "如果您将此列表设为私有，它将从社区中消失，只有您可以查看。",
            btnConfirmar = "确认", btnCancelar = "取消", tituloSeleccionarImagen = "选择一张图片", btnCerrar = "关闭", btnSaveImagen = "保存",
            tituloEliminarElemento = "删除 ", tituloBorrarPalabra = "单个单词", tituloBorrarGrupo = "整个组",
            descEliminarElemento = "您确定要删除此元素吗？所有数据都将丢失。", btnEliminar = "删除",
            tituloImportar = "导入单词", descImportar = "格式规则：\n以(.)开头且没有(,)的为组名。在组下带有(,)的单词属于该组。在最后一个线索上以(.)结束。在组外的为单个单词。\n\n示例：\n.动物\n狗, 线索1,线索2\n猫, 线索1,线索2.",
            placeholderImportar = "在此粘贴...", btnProcesar = "处理", tituloConflictos = "重复的单词！", descConflictos = "您尝试导入的一些单词已经存在。您想做什么？",
            btnReemplazar = "替换旧的", btnOmitirNuevas = "跳过新的", btnAnadirTodo = "全部添加并手动编辑", btnCancelarImportacion = "取消导入",
            msgSalirTutorial = "要退出，请按右上角的“跳过教程”。", msgGuardarTutorial = "保存包含3个单词的列表以继续。",
            msgMinimoPalabras = "对于教程，请至少添加3个测试单词。", msgFaltanCampos = "缺少字段或存在错误",
            msgImportExito = "元素导入成功", msgSesionPublicar = "您必须登录才能发布列表。", msgSesionPrimero = "请先登录。",
            msgImagenSelec = "已选择图片", msgAbrirImagen = "请先打开大图", errorRepetida = "重复"
        )
        IdiomaSoportado.JAPONES -> TextosCrear(
            cargandoTaller = "ワークショップを準備中...", tituloEditar = "リストを編集", tituloNueva = "新しいリスト", btnGuardar = "保存",
            placeholderBuscar = "単語、ヒント、またはグループを検索...", labelNombreLista = "リスト名", labelCategoria = "カテゴリ (例: 映画)",
            tituloPublica = "公開リスト", tituloPrivada = "非公開リスト", descPublica = "誰でも見つけてプレイできます", descPrivada = "あなただけがこのリストを見ることができます",
            etiquetaPalabraIndividual = "単一の単語", labelPalabra = "秘密の言葉", labelPistas = "ヒント（カンマ区切り）",
            placeholderPalabra = "単語", placeholderGrupo = "単語グループ...", labelNombreGrupo = "このグループの名前",
            btnAnadirPalabraGrupo = "グループに単語を追加", btnAnadirPalabra = "+ 単語", btnAnadirGrupo = "+ グループ",
            tituloDialogoPublicar = "このリストを公開しますか？", tituloDialogoPrivar = "非公開にしますか？",
            descDialogoPublicar = "公開すると、コミュニティの誰もが見てプレイできるようになります。あなたの名前が作成者として表示されます。\n\n後で元に戻すことができます。",
            descDialogoPrivar = "非公開にするとコミュニティから消え、あなただけが見ることができます。",
            btnConfirmar = "確認", btnCancelar = "キャンセル", tituloSeleccionarImagen = "画像を選択", btnCerrar = "閉じる", btnSaveImagen = "保存",
            tituloEliminarElemento = "削除 ", tituloBorrarPalabra = "単一の単語", tituloBorrarGrupo = "グループ全体",
            descEliminarElemento = "この要素を削除してもよろしいですか？すべてのデータが失われます。", btnEliminar = "削除",
            tituloImportar = "単語をインポート", descImportar = "フォーマットルール:\n(.)で始まり(,)がない場合はグループ名です。グループ下の(,)付きの単語はそこに属します。最後のヒントは(.)で終わります。グループ外は個別の単語です。\n\n例:\n.動物\n犬, ヒント1,ヒント2\n猫, ヒント1,ヒント2.",
            placeholderImportar = "ここに貼り付け...", btnProcesar = "処理", tituloConflictos = "重複した単語！", descConflictos = "インポートしようとした単語のいくつかはすでに存在します。どうしますか？",
            btnReemplazar = "古いものを置き換える", btnOmitirNuevas = "新しいものをスキップ", btnAnadirTodo = "すべて追加して編集", btnCancelarImportacion = "インポートをキャンセル",
            msgSalirTutorial = "終了するには右上の「チュートリアルをスキップ」を押してください。", msgGuardarTutorial = "続けるには3つの単語を含むリストを保存してください。",
            msgMinimoPalabras = "チュートリアルのために、少なくとも3つのテスト単語を追加してください。", msgFaltanCampos = "未入力のフィールドまたはエラーがあります",
            msgImportExito = "要素が正常にインポートされました", msgSesionPublicar = "リストを公開するにはログインする必要があります。", msgSesionPrimero = "最初にログインしてください。",
            msgImagenSelec = "画像が選択されました", msgAbrirImagen = "最初に大きな画像を開いてください", errorRepetida = "重複"
        )
        // INGLÉS POR DEFECTO
        else -> TextosCrear(
            cargandoTaller = "Preparing the workshop...", tituloEditar = "Edit List", tituloNueva = "New List", btnGuardar = "SAVE",
            placeholderBuscar = "Search word, clue or group...", labelNombreLista = "List Name", labelCategoria = "Category (Ex: Movies)",
            tituloPublica = "Public List", tituloPrivada = "Private List", descPublica = "Anyone can find and play it", descPrivada = "Only you can see this list",
            etiquetaPalabraIndividual = "Individual Word", labelPalabra = "Secret Word", labelPistas = "Clue(s) separated by comma",
            placeholderPalabra = "Word", placeholderGrupo = "Word group...", labelNombreGrupo = "Name of this Group",
            btnAnadirPalabraGrupo = "ADD WORD TO GROUP", btnAnadirPalabra = "+ WORD", btnAnadirGrupo = "+ GROUP",
            tituloDialogoPublicar = "Publish this list?", tituloDialogoPrivar = "Make private?",
            descDialogoPublicar = "By publishing this list, anyone in the community can see and play it. Your name will appear as the creator.\n\nYou can undo this later.",
            descDialogoPrivar = "If you make this list private, it will disappear from the community and only you can play it.",
            btnConfirmar = "CONFIRM", btnCancelar = "CANCEL", tituloSeleccionarImagen = "Select an image", btnCerrar = "Close", btnSaveImagen = "SAVE",
            tituloEliminarElemento = "Delete ", tituloBorrarPalabra = "Individual Word", tituloBorrarGrupo = "Entire Group",
            descEliminarElemento = "Are you sure you want to delete this element? All data will be lost.", btnEliminar = "DELETE",
            tituloImportar = "Import Words", descImportar = "Format rules:\nStart with (.) and no (,) for a Group. Words with (,) below a group belong to it. End with (.) on the last clue. Outside of groups are individual words.\n\nExample:\n.Animals\nDog, Clue1,Clue2\nCat, Clue1,Clue2.",
            placeholderImportar = "Paste here...", btnProcesar = "PROCESS", tituloConflictos = "Repeated words!", descConflictos = "Some of the words you are trying to import already exist. What do you want to do?",
            btnReemplazar = "Replace old", btnOmitirNuevas = "Skip new", btnAnadirTodo = "Add all and edit manual", btnCancelarImportacion = "CANCEL IMPORT",
            msgSalirTutorial = "To exit, press 'Skip Tutorial' in the top right.", msgGuardarTutorial = "Save your list with 3 words to continue.",
            msgMinimoPalabras = "For the tutorial, add at least 3 test words.", msgFaltanCampos = "Missing fields or errors found",
            msgImportExito = "Elements imported successfully", msgSesionPublicar = "You must log in to publish lists.", msgSesionPrimero = "Log in first.",
            msgImagenSelec = "Image selected", msgAbrirImagen = "Open the full image first", errorRepetida = "Repeated"
        )
    }
}