package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosDE {
    val listasPredeterminadas = listOf(
        // === 1. KATEGORIE: OBJEKT ===
        ColeccionPredefinida(
            nombre = "Alltagsgegenstände",
            categoria = "Objekt",
            elementos = listOf(
                ElementoPredefinido.Individual("Bleistift", "Grafit"),
                ElementoPredefinido.Individual("Spiegel", "Reflexion"),
                ElementoPredefinido.Individual("Bettlaken", "Bett"),
                ElementoPredefinido.Individual("Gabel", "Zinken"),
                ElementoPredefinido.Individual("Telefon", "Kommunikation"),
                ElementoPredefinido.Individual("Uhr", "Minuten"),
                ElementoPredefinido.Individual("Schlüssel", "Schloss"),
                ElementoPredefinido.Individual("Brille", "Gläser"),
                ElementoPredefinido.Individual("Glühbirne", "Glühfaden"),
                ElementoPredefinido.Individual("Tisch", "Platte"),
                ElementoPredefinido.Individual("Teller", "Keramik"),
                ElementoPredefinido.Individual("Glas", "Kristall"),
                ElementoPredefinido.Individual("Hammer", "Nagel"),
                ElementoPredefinido.Individual("Rucksack", "Last"),
                ElementoPredefinido.Individual("Regenschirm", "Regen"),
                ElementoPredefinido.Individual("Kamera", "Objektiv"),
                ElementoPredefinido.Individual("Buch", "Seiten"),
                ElementoPredefinido.Individual("Flasche", "Flüssigkeit"),
                ElementoPredefinido.Individual("Schere", "Klinge"),
                ElementoPredefinido.Individual("Brieftasche", "Tasche"),
                ElementoPredefinido.Individual("Stuhl", "Lehne"),
                ElementoPredefinido.Individual("Kissen", "Federn"),
                ElementoPredefinido.Individual("Ventilator", "Flügel"),
                ElementoPredefinido.Individual("Batterie", "Ladung"),
                ElementoPredefinido.Individual("Besen", "Boden"),
                ElementoPredefinido.Individual("Taschenrechner", "Zahlen"),
                ElementoPredefinido.Individual("Wörterbuch", "Definitionen"),
                ElementoPredefinido.Individual("Kamm", "Haare"),
                ElementoPredefinido.Individual("Löffel", "Suppe"),
                ElementoPredefinido.Individual("Handtuch", "Bad"),
                ElementoPredefinido.Individual("Koffer", "Reise"),
                ElementoPredefinido.Individual("Gürtel", "Hose"),
                ElementoPredefinido.Individual("Handschuh", "Hand"),
                ElementoPredefinido.Individual("Socke", "Fuß"),
                ElementoPredefinido.Individual("Mütze", "Kopf"),
                ElementoPredefinido.Individual("Ring", "Finger"),
                ElementoPredefinido.Individual("Halskette", "Hals"),
                ElementoPredefinido.Individual("Armband", "Handgelenk"),
                ElementoPredefinido.Individual("Ohrring", "Ohr"),
                ElementoPredefinido.Individual("Geldbörse", "Bargeld"),
                ElementoPredefinido.Individual("Feuerzeug", "Flamme"),
                ElementoPredefinido.Individual("Aschenbecher", "Asche"),
                ElementoPredefinido.Individual("Fächer", "Wind"),
                ElementoPredefinido.Individual("Zelle", "Spannung"),
                ElementoPredefinido.Individual("Controller", "Tasten"),
                ElementoPredefinido.Individual("Tastatur", "Buchstaben"),
                ElementoPredefinido.Individual("Maus", "Klick"),
                ElementoPredefinido.Individual("Monitor", "Bildschirm"),
                ElementoPredefinido.Individual("Kopfhörer", "Klang"),
                ElementoPredefinido.Individual("Mikrofon", "Stimme"),
                ElementoPredefinido.Individual("Lautsprecher", "Lautstärke"),
                ElementoPredefinido.Individual("Ladegerät", "Kabel"),
                ElementoPredefinido.Individual("Stecker", "Strom"),
                ElementoPredefinido.Individual("Birne", "Beleuchtung"),
                ElementoPredefinido.Individual("Kerze", "Wachs"),
                ElementoPredefinido.Individual("Teppich", "Boden"),
                ElementoPredefinido.Individual("Vorhang", "Fenster"),
                ElementoPredefinido.Individual("Gemälde", "Wand"),
                ElementoPredefinido.Individual("Vase", "Dekoration"),
                ElementoPredefinido.Individual("Korb", "Weide"),
                ElementoPredefinido.Individual("Kiste", "Karton"),
                ElementoPredefinido.Individual("Tüte", "Plastik"),
                ElementoPredefinido.Individual("Mülleimer", "Abfall"),
                ElementoPredefinido.Individual("Hefter", "Büro"),
                ElementoPredefinido.Individual("Büroklammer", "Halt"),
                ElementoPredefinido.Individual("Ordner", "Dokumente"),
                ElementoPredefinido.Individual("Briefumschlag", "Brief"),
                ElementoPredefinido.Individual("Briefmarke", "Post"),
                ElementoPredefinido.Individual("Klebstoff", "Kleber"),
                ElementoPredefinido.Individual("Klebeband", "Klebend"),
                ElementoPredefinido.Individual("Radiergummi", "Radieren"),
                ElementoPredefinido.Individual("Anspitzer", "Spitze"),
                ElementoPredefinido.Individual("Lineal", "Maß"),
                ElementoPredefinido.Individual("Zirkel", "Kreis"),
                ElementoPredefinido.Individual("Pinsel", "Öl")
            )
        ),

        // === 2. KATEGORIE: ORT ===
        ColeccionPredefinida(
            nombre = "Orte",
            categoria = "Ort",
            elementos = listOf(
                ElementoPredefinido.Individual("Bibliothek", "Regal"),
                ElementoPredefinido.Individual("Wald", "Vegetation"),
                ElementoPredefinido.Individual("Kino", "Sitze"),
                ElementoPredefinido.Individual("Wüste", "Dürre"),
                ElementoPredefinido.Individual("Bahnhof", "Gleis"),
                ElementoPredefinido.Individual("Krankenhaus", "Patienten"),
                ElementoPredefinido.Individual("Museum", "Ausstellung"),
                ElementoPredefinido.Individual("Strand", "Wellen"),
                ElementoPredefinido.Individual("Park", "Schaukeln"),
                ElementoPredefinido.Individual("Fluss", "Flussbett"),
                ElementoPredefinido.Individual("Theater", "Vorhang"),
                ElementoPredefinido.Individual("Zoo", "Käfige"),
                ElementoPredefinido.Individual("Flughafen", "Terminal"),
                ElementoPredefinido.Individual("Fitnessstudio", "Gewichte"),
                ElementoPredefinido.Individual("Berg", "Gipfel"),
                ElementoPredefinido.Individual("Supermarkt", "Gänge"),
                ElementoPredefinido.Individual("Kirche", "Altar"),
                ElementoPredefinido.Individual("Schloss", "Mauer"),
                ElementoPredefinido.Individual("Stadion", "Tribüne"),
                ElementoPredefinido.Individual("Bauernhof", "Gehege"),
                ElementoPredefinido.Individual("Vulkan", "Magma"),
                ElementoPredefinido.Individual("Insel", "Archipel"),
                ElementoPredefinido.Individual("Hafen", "Pier"),
                ElementoPredefinido.Individual("Restaurant", "Speisekarte"),
                ElementoPredefinido.Individual("Bank", "Geldautomat"),
                ElementoPredefinido.Individual("Gefängnis", "Zellen"),
                ElementoPredefinido.Individual("Schule", "Klassenzimmer"),
                ElementoPredefinido.Individual("Universität", "Fakultät"),
                ElementoPredefinido.Individual("Fabrik", "Produktion"),
                ElementoPredefinido.Individual("Werkstatt", "Werkzeuge"),
                ElementoPredefinido.Individual("Büro", "Schreibtische"),
                ElementoPredefinido.Individual("Apotheke", "Medikamente"),
                ElementoPredefinido.Individual("Bäckerei", "Ofen"),
                ElementoPredefinido.Individual("Friseur", "Spiegel"),
                ElementoPredefinido.Individual("Tankstelle", "Kraftstoff"),
                ElementoPredefinido.Individual("Hotel", "Rezeption"),
                ElementoPredefinido.Individual("Campingplatz", "Zelte"),
                ElementoPredefinido.Individual("Hafen", "Boote"),
                ElementoPredefinido.Individual("Markt", "Stände"),
                ElementoPredefinido.Individual("Palast", "Königtum"),
                ElementoPredefinido.Individual("Kathedrale", "Gotik"),
                ElementoPredefinido.Individual("Friedhof", "Gräber"),
                ElementoPredefinido.Individual("Garten", "Blumen"),
                ElementoPredefinido.Individual("Terrasse", "Aussicht"),
                ElementoPredefinido.Individual("Keller", "Dunkelheit"),
                ElementoPredefinido.Individual("Dachboden", "Dach"),
                ElementoPredefinido.Individual("Garage", "Auto"),
                ElementoPredefinido.Individual("Küche", "Herd"),
                ElementoPredefinido.Individual("Badezimmer", "Dusche"),
                ElementoPredefinido.Individual("Schlafzimmer", "Ruhe"),
                ElementoPredefinido.Individual("Wohnzimmer", "Sofa"),
                ElementoPredefinido.Individual("Flur", "Türen"),
                ElementoPredefinido.Individual("Balkon", "Geländer"),
                ElementoPredefinido.Individual("Schwimmbad", "Chlor"),
                ElementoPredefinido.Individual("Platz", "Brunnen"),
                ElementoPredefinido.Individual("Straße", "Asphalt"),
                ElementoPredefinido.Individual("Allee", "Verkehr"),
                ElementoPredefinido.Individual("Brücke", "Fluss"),
                ElementoPredefinido.Individual("Tunnel", "Unterirdisch"),
                ElementoPredefinido.Individual("Leuchtturm", "Küste"),
                ElementoPredefinido.Individual("Klippe", "Höhe"),
                ElementoPredefinido.Individual("Höhle", "Stalaktiten"),
                ElementoPredefinido.Individual("Dschungel", "Tropisch"),
                ElementoPredefinido.Individual("Savanne", "Ebene"),
                ElementoPredefinido.Individual("Sumpf", "Schlamm"),
                ElementoPredefinido.Individual("Gletscher", "Eis"),
                ElementoPredefinido.Individual("Wasserfall", "Fall"),
                ElementoPredefinido.Individual("Tal", "Berge"),
                ElementoPredefinido.Individual("Wiese", "Weide"),
                ElementoPredefinido.Individual("Wüste", "Dünen"),
                ElementoPredefinido.Individual("Yachthafen", "Anker"),
                ElementoPredefinido.Individual("Bahnhof", "Gleise"),
                ElementoPredefinido.Individual("Flugplatz", "Landebahn"),
                ElementoPredefinido.Individual("Observatorium", "Sterne"),
                ElementoPredefinido.Individual("Labor", "Röhrchen")
            )
        ),

        // === 3. KATEGORIE: TIER ===
        ColeccionPredefinida(
            nombre = "Tiere",
            categoria = "Tier",
            elementos = listOf(
                ElementoPredefinido.Individual("Löwe", "Mähne"),
                ElementoPredefinido.Individual("Elefant", "Rüssel"),
                ElementoPredefinido.Individual("Giraffe", "Hals"),
                ElementoPredefinido.Individual("Tiger", "Streifen"),
                ElementoPredefinido.Individual("Eisbär", "Arktis"),
                ElementoPredefinido.Individual("Panda", "Bambus"),
                ElementoPredefinido.Individual("Delfin", "Intelligenz"),
                ElementoPredefinido.Individual("Wal", "Blasloch"),
                ElementoPredefinido.Individual("Adler", "Krallen"),
                ElementoPredefinido.Individual("Känguru", "Beutel"),
                ElementoPredefinido.Individual("Pinguin", "Frack"),
                ElementoPredefinido.Individual("Koala", "Eukalyptus"),
                ElementoPredefinido.Individual("Schlange", "Gift"),
                ElementoPredefinido.Individual("Oktopus", "Tinte"),
                ElementoPredefinido.Individual("Wolf", "Heulen"),
                ElementoPredefinido.Individual("Pferd", "Hufe"),
                ElementoPredefinido.Individual("Affe", "Primat"),
                ElementoPredefinido.Individual("Hai", "Flosse"),
                ElementoPredefinido.Individual("Biene", "Bienenstock"),
                ElementoPredefinido.Individual("Chamäleon", "Tarnung"),
                ElementoPredefinido.Individual("Eule", "Weisheit"),
                ElementoPredefinido.Individual("Kuh", "Milch"),
                ElementoPredefinido.Individual("Krokodil", "Kiefer"),
                ElementoPredefinido.Individual("Schmetterling", "Metamorphose"),
                ElementoPredefinido.Individual("Fledermaus", "Sonar"),
                ElementoPredefinido.Individual("Hund", "Loyalität"),
                ElementoPredefinido.Individual("Katze", "Schnurren"),
                ElementoPredefinido.Individual("Kaninchen", "Karotte"),
                ElementoPredefinido.Individual("Maus", "Käse"),
                ElementoPredefinido.Individual("Zebra", "Schwarzweiß"),
                ElementoPredefinido.Individual("Nilpferd", "Fluss"),
                ElementoPredefinido.Individual("Nashorn", "Horn"),
                ElementoPredefinido.Individual("Gepard", "Geschwindigkeit"),
                ElementoPredefinido.Individual("Hyäne", "Lachen"),
                ElementoPredefinido.Individual("Fuchs", "List"),
                ElementoPredefinido.Individual("Bär", "Winterschlaf"),
                ElementoPredefinido.Individual("Hirsch", "Geweih"),
                ElementoPredefinido.Individual("Eichhörnchen", "Nüsse"),
                ElementoPredefinido.Individual("Biber", "Damm"),
                ElementoPredefinido.Individual("Fischotter", "Wasser"),
                ElementoPredefinido.Individual("Robbe", "Antarktis"),
                ElementoPredefinido.Individual("Walross", "Stoßzähne"),
                ElementoPredefinido.Individual("Pelikan", "Schnabel"),
                ElementoPredefinido.Individual("Flamingo", "Rosa"),
                ElementoPredefinido.Individual("Papagei", "Sprechen"),
                ElementoPredefinido.Individual("Pfau", "Gefieder"),
                ElementoPredefinido.Individual("Strauß", "Ei"),
                ElementoPredefinido.Individual("Schwan", "See"),
                ElementoPredefinido.Individual("Rabe", "Schwarz"),
                ElementoPredefinido.Individual("Hahn", "Morgendämmerung"),
                ElementoPredefinido.Individual("Henne", "Hühnerstall"),
                ElementoPredefinido.Individual("Ente", "Schnabel"),
                ElementoPredefinido.Individual("Kröte", "Teich"),
                ElementoPredefinido.Individual("Frosch", "Sprung"),
                ElementoPredefinido.Individual("Schildkröte", "Panzer"),
                ElementoPredefinido.Individual("Leguan", "Reptil"),
                ElementoPredefinido.Individual("Eidechse", "Schwanz"),
                ElementoPredefinido.Individual("Skorpion", "Stachel"),
                ElementoPredefinido.Individual("Spinne", "Spinnennetz"),
                ElementoPredefinido.Individual("Ameise", "Ameisenhaufen"),
                ElementoPredefinido.Individual("Grashüpfer", "Grün"),
                ElementoPredefinido.Individual("Grille", "Zirpen"),
                ElementoPredefinido.Individual("Fliege", "Flug"),
                ElementoPredefinido.Individual("Mücke", "Stich"),
                ElementoPredefinido.Individual("Kakerlake", "Widerstand"),
                ElementoPredefinido.Individual("Krabbe", "Scheren"),
                ElementoPredefinido.Individual("Hummer", "Meer"),
                ElementoPredefinido.Individual("Garnele", "Krustentier"),
                ElementoPredefinido.Individual("Schnecke", "Schleim"),
                ElementoPredefinido.Individual("Qualle", "Tentakel"),
                ElementoPredefinido.Individual("Seestern", "Arme"),
                ElementoPredefinido.Individual("Seepferdchen", "Schnauze"),
                ElementoPredefinido.Individual("Schwertfisch", "Schwert"),
                ElementoPredefinido.Individual("Clownfisch", "Anemone"),
                ElementoPredefinido.Individual("Aal", "Elektrizität")
            )
        ),

        // === 4. KATEGORIE: ESSEN ===
        ColeccionPredefinida(
            nombre = "Gastronomie",
            categoria = "Essen",
            elementos = listOf(
                ElementoPredefinido.Individual("Pizza", "Stück"),
                ElementoPredefinido.Individual("Sushi", "Wasabi"),
                ElementoPredefinido.Individual("Hamburger", "Essiggurke"),
                ElementoPredefinido.Individual("Paella", "Safran"),
                ElementoPredefinido.Individual("Taco", "Scharf"),
                ElementoPredefinido.Individual("Eis", "Waffel"),
                ElementoPredefinido.Individual("Pasta", "Al dente"),
                ElementoPredefinido.Individual("Salat", "Vinaigrette"),
                ElementoPredefinido.Individual("Schokolade", "Kakao"),
                ElementoPredefinido.Individual("Suppe", "Löffel"),
                ElementoPredefinido.Individual("Brot", "Krume"),
                ElementoPredefinido.Individual("Käse", "Fermentation"),
                ElementoPredefinido.Individual("Ei", "Eigelb"),
                ElementoPredefinido.Individual("Apfel", "Sünde"),
                ElementoPredefinido.Individual("Kartoffel", "Frittiert"),
                ElementoPredefinido.Individual("Steak", "Blutig"),
                ElementoPredefinido.Individual("Krokette", "Béchamel"),
                ElementoPredefinido.Individual("Joghurt", "Bifidus"),
                ElementoPredefinido.Individual("Kaffee", "Koffein"),
                ElementoPredefinido.Individual("Keks", "Stückchen"),
                ElementoPredefinido.Individual("Meeresfrüchte", "Schale"),
                ElementoPredefinido.Individual("Reis", "Korn"),
                ElementoPredefinido.Individual("Honig", "Süße"),
                ElementoPredefinido.Individual("Donut", "Glasur"),
                ElementoPredefinido.Individual("Sandwich", "Füllung"),
                ElementoPredefinido.Individual("Kuchen", "Kerze"),
                ElementoPredefinido.Individual("Fisch", "Schuppen"),
                ElementoPredefinido.Individual("Hähnchen", "Gebraten"),
                ElementoPredefinido.Individual("Linsen", "Eisen"),
                ElementoPredefinido.Individual("Kichererbsen", "Eintopf"),
                ElementoPredefinido.Individual("Spaghetti", "Soße"),
                ElementoPredefinido.Individual("Makkaroni", "Gratin"),
                ElementoPredefinido.Individual("Omelett", "Kartoffeln"),
                ElementoPredefinido.Individual("Gazpacho", "Tomate"),
                ElementoPredefinido.Individual("Salmorejo", "Brot"),
                ElementoPredefinido.Individual("Kotelett", "Grill"),
                ElementoPredefinido.Individual("Lachs", "Rosa"),
                ElementoPredefinido.Individual("Thunfisch", "Dose"),
                ElementoPredefinido.Individual("Kabeljau", "Gesalzen"),
                ElementoPredefinido.Individual("Tintenfisch", "Ringe"),
                ElementoPredefinido.Individual("Oktopus", "Galicisch"),
                ElementoPredefinido.Individual("Garnelen", "Plancha"),
                ElementoPredefinido.Individual("Fleischbällchen", "Fleisch"),
                ElementoPredefinido.Individual("Lasagne", "Schichten"),
                ElementoPredefinido.Individual("Cannelloni", "Pasta"),
                ElementoPredefinido.Individual("Risotto", "Cremig"),
                ElementoPredefinido.Individual("Couscous", "Grieß"),
                ElementoPredefinido.Individual("Hummus", "Kichererbse"),
                ElementoPredefinido.Individual("Guacamole", "Avocado"),
                ElementoPredefinido.Individual("Burrito", "Bohnen"),
                ElementoPredefinido.Individual("Nacho", "Käse"),
                ElementoPredefinido.Individual("Kebab", "Fleisch"),
                ElementoPredefinido.Individual("Curry", "Gewürze"),
                ElementoPredefinido.Individual("Ramen", "Brühe"),
                ElementoPredefinido.Individual("Dim Sum", "Dampf"),
                ElementoPredefinido.Individual("Ceviche", "Zitrone"),
                ElementoPredefinido.Individual("Arepa", "Mais"),
                ElementoPredefinido.Individual("Empanada", "Teig"),
                ElementoPredefinido.Individual("Quiche", "Ei"),
                ElementoPredefinido.Individual("Crêpe", "Süß"),
                ElementoPredefinido.Individual("Waffel", "Quadrate"),
                ElementoPredefinido.Individual("Churros", "Öl"),
                ElementoPredefinido.Individual("Flan", "Karamell"),
                ElementoPredefinido.Individual("Pudding", "Zimt"),
                ElementoPredefinido.Individual("Milchreis", "Dessert"),
                ElementoPredefinido.Individual("Brownie", "Schokolade"),
                ElementoPredefinido.Individual("Muffin", "Cupcake"),
                ElementoPredefinido.Individual("Croissant", "Butter"),
                ElementoPredefinido.Individual("Baguette", "Frankreich"),
                ElementoPredefinido.Individual("Brezel", "Salz"),
                ElementoPredefinido.Individual("Popcorn", "Mais"),
                ElementoPredefinido.Individual("Sonnenblumenkerne", "Kerne"),
                ElementoPredefinido.Individual("Mandeln", "Nüsse"),
                ElementoPredefinido.Individual("Walnüsse", "Schale"),
                ElementoPredefinido.Individual("Oliven", "Aperitif")
            )
        ),

        // === 5. KATEGORIE: BERUF ===
        ColeccionPredefinida(
            nombre = "Berufe",
            categoria = "Beruf",
            elementos = listOf(
                ElementoPredefinido.Individual("Arzt", "Stethoskop"),
                ElementoPredefinido.Individual("Feuerwehrmann", "Schlauch"),
                ElementoPredefinido.Individual("Lehrer", "Tafel"),
                ElementoPredefinido.Individual("Polizist", "Handschellen"),
                ElementoPredefinido.Individual("Koch", "Mütze"),
                ElementoPredefinido.Individual("Architekt", "Bauplan"),
                ElementoPredefinido.Individual("Astronaut", "Schwerkraft"),
                ElementoPredefinido.Individual("Maler", "Leinwand"),
                ElementoPredefinido.Individual("Mechaniker", "Mutter"),
                ElementoPredefinido.Individual("Anwalt", "Gesetz"),
                ElementoPredefinido.Individual("Musiker", "Noten"),
                ElementoPredefinido.Individual("Wissenschaftler", "Mikroskop"),
                ElementoPredefinido.Individual("Fotograf", "Blitz"),
                ElementoPredefinido.Individual("Zahnarzt", "Karies"),
                ElementoPredefinido.Individual("Pilot", "Kabine"),
                ElementoPredefinido.Individual("Zimmermann", "Sägemehl"),
                ElementoPredefinido.Individual("Richter", "Hammer"),
                ElementoPredefinido.Individual("Tierarzt", "Tiere"),
                ElementoPredefinido.Individual("Journalist", "Interview"),
                ElementoPredefinido.Individual("Schauspieler", "Drehbuch"),
                ElementoPredefinido.Individual("Bauer", "Ernte"),
                ElementoPredefinido.Individual("Bäcker", "Hefe"),
                ElementoPredefinido.Individual("Elektriker", "Spannung"),
                ElementoPredefinido.Individual("Tänzer", "Bühne"),
                ElementoPredefinido.Individual("Gärtner", "Beschneidung"),
                ElementoPredefinido.Individual("Briefträger", "Briefkasten"),
                ElementoPredefinido.Individual("Schriftsteller", "Roman"),
                ElementoPredefinido.Individual("Krankenpfleger", "Spritze"),
                ElementoPredefinido.Individual("Psychologe", "Therapie"),
                ElementoPredefinido.Individual("Ingenieur", "Berechnung"),
                ElementoPredefinido.Individual("Programmierer", "Code"),
                ElementoPredefinido.Individual("Designer", "Skizze"),
                ElementoPredefinido.Individual("Ökonom", "Finanzen"),
                ElementoPredefinido.Individual("Archäologe", "Fossil"),
                ElementoPredefinido.Individual("Geologe", "Gestein"),
                ElementoPredefinido.Individual("Biologe", "Zellen"),
                ElementoPredefinido.Individual("Chemiker", "Reaktion"),
                ElementoPredefinido.Individual("Physiker", "Atom"),
                ElementoPredefinido.Individual("Mathematiker", "Gleichung"),
                ElementoPredefinido.Individual("Philosoph", "Gedanke"),
                ElementoPredefinido.Individual("Historiker", "Vergangenheit"),
                ElementoPredefinido.Individual("Geograf", "Karten"),
                ElementoPredefinido.Individual("Politiker", "Stimmen"),
                ElementoPredefinido.Individual("Diplomat", "Botschaft"),
                ElementoPredefinido.Individual("Militär", "Uniform"),
                ElementoPredefinido.Individual("Seemann", "Ozean"),
                ElementoPredefinido.Individual("Priester", "Soutane"),
                ElementoPredefinido.Individual("Bildhauer", "Meißel"),
                ElementoPredefinido.Individual("Dirigent", "Taktstock"),
                ElementoPredefinido.Individual("Sänger", "Mikrofon"),
                ElementoPredefinido.Individual("Dichter", "Vers"),
                ElementoPredefinido.Individual("Model", "Laufsteg"),
                ElementoPredefinido.Individual("Juwelier", "Diamant"),
                ElementoPredefinido.Individual("Uhrmacher", "Zahnrad"),
                ElementoPredefinido.Individual("Schuster", "Sohle"),
                ElementoPredefinido.Individual("Schneider", "Fingerhut"),
                ElementoPredefinido.Individual("Metzger", "Messer"),
                ElementoPredefinido.Individual("Fischhändler", "Theke"),
                ElementoPredefinido.Individual("Gemüsehändler", "Waage"),
                ElementoPredefinido.Individual("Kellner", "Tablett"),
                ElementoPredefinido.Individual("Rezeptionist", "Telefon"),
                ElementoPredefinido.Individual("Stewardess", "Flug"),
                ElementoPredefinido.Individual("Reiseführer", "Tourismus"),
                ElementoPredefinido.Individual("Bibliothekar", "Archiv"),
                ElementoPredefinido.Individual("Wachmann", "Alarm"),
                ElementoPredefinido.Individual("Maurer", "Ziegel"),
                ElementoPredefinido.Individual("Klempner", "Rohr"),
                ElementoPredefinido.Individual("Maler", "Pinsel"),
                ElementoPredefinido.Individual("Schlosser", "Dietrich"),
                ElementoPredefinido.Individual("Bergmann", "Spitzhacke"),
                ElementoPredefinido.Individual("Holzfäller", "Werkzeug"),
                ElementoPredefinido.Individual("Fischer", "Netz"),
                ElementoPredefinido.Individual("Jäger", "Gewehr"),
                ElementoPredefinido.Individual("Straßenkehrer", "Besen"),
                ElementoPredefinido.Individual("Taxifahrer", "Lenkrad")
            )
        )
    )
}