package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosFR {
    val listasPredeterminadas = listOf(
        // === 1. CATÉGORIE : OBJET ===
        ColeccionPredefinida(
            nombre = "Objets Quotidiens",
            categoria = "Objet",
            elementos = listOf(
                ElementoPredefinido.Individual("Crayon", "Graphite"),
                ElementoPredefinido.Individual("Miroir", "Reflet"),
                ElementoPredefinido.Individual("Drap", "Lit"),
                ElementoPredefinido.Individual("Fourchette", "Pointes"),
                ElementoPredefinido.Individual("Téléphone", "Communication"),
                ElementoPredefinido.Individual("Montre", "Minutes"),
                ElementoPredefinido.Individual("Clé", "Serrure"),
                ElementoPredefinido.Individual("Lunettes", "Verres"),
                ElementoPredefinido.Individual("Ampoule", "Filament"),
                ElementoPredefinido.Individual("Table", "Plateau"),
                ElementoPredefinido.Individual("Assiette", "Céramique"),
                ElementoPredefinido.Individual("Verre", "Cristal"),
                ElementoPredefinido.Individual("Marteau", "Clou"),
                ElementoPredefinido.Individual("Sac à dos", "Charge"),
                ElementoPredefinido.Individual("Parapluie", "Pluie"),
                ElementoPredefinido.Individual("Appareil photo", "Objectif"),
                ElementoPredefinido.Individual("Livre", "Pages"),
                ElementoPredefinido.Individual("Bouteille", "Liquide"),
                ElementoPredefinido.Individual("Ciseaux", "Lame"),
                ElementoPredefinido.Individual("Portefeuille", "Poche"),
                ElementoPredefinido.Individual("Chaise", "Dossier"),
                ElementoPredefinido.Individual("Oreiller", "Plumes"),
                ElementoPredefinido.Individual("Ventilateur", "Pales"),
                ElementoPredefinido.Individual("Batterie", "Charge"),
                ElementoPredefinido.Individual("Balai", "Sol"),
                ElementoPredefinido.Individual("Calculatrice", "Nombres"),
                ElementoPredefinido.Individual("Dictionnaire", "Définitions"),
                ElementoPredefinido.Individual("Peigne", "Cheveux"),
                ElementoPredefinido.Individual("Cuillère", "Soupe"),
                ElementoPredefinido.Individual("Serviette", "Bain"),
                ElementoPredefinido.Individual("Valise", "Voyage"),
                ElementoPredefinido.Individual("Ceinture", "Pantalon"),
                ElementoPredefinido.Individual("Gant", "Main"),
                ElementoPredefinido.Individual("Chaussette", "Pied"),
                ElementoPredefinido.Individual("Casquette", "Tête"),
                ElementoPredefinido.Individual("Bague", "Doigt"),
                ElementoPredefinido.Individual("Collier", "Cou"),
                ElementoPredefinido.Individual("Bracelet", "Poignet"),
                ElementoPredefinido.Individual("Boucle d'oreille", "Oreille"),
                ElementoPredefinido.Individual("Porte-monnaie", "Espèces"),
                ElementoPredefinido.Individual("Briquet", "Flamme"),
                ElementoPredefinido.Individual("Cendrier", "Cendre"),
                ElementoPredefinido.Individual("Éventail", "Vent"),
                ElementoPredefinido.Individual("Pile", "Tension"),
                ElementoPredefinido.Individual("Télécommande", "Boutons"),
                ElementoPredefinido.Individual("Clavier", "Lettres"),
                ElementoPredefinido.Individual("Souris", "Clic"),
                ElementoPredefinido.Individual("Moniteur", "Écran"),
                ElementoPredefinido.Individual("Écouteurs", "Son"),
                ElementoPredefinido.Individual("Microphone", "Voix"),
                ElementoPredefinido.Individual("Haut-parleur", "Volume"),
                ElementoPredefinido.Individual("Chargeur", "Câble"),
                ElementoPredefinido.Individual("Prise", "Courant"),
                ElementoPredefinido.Individual("Ampoule", "Éclairage"),
                ElementoPredefinido.Individual("Bougie", "Cire"),
                ElementoPredefinido.Individual("Tapis", "Sol"),
                ElementoPredefinido.Individual("Rideau", "Fenêtre"),
                ElementoPredefinido.Individual("Tableau", "Mur"),
                ElementoPredefinido.Individual("Vase", "Décoration"),
                ElementoPredefinido.Individual("Panier", "Osier"),
                ElementoPredefinido.Individual("Boîte", "Carton"),
                ElementoPredefinido.Individual("Sac", "Plastique"),
                ElementoPredefinido.Individual("Poubelle", "Déchets"),
                ElementoPredefinido.Individual("Agrafeuse", "Bureau"),
                ElementoPredefinido.Individual("Trombone", "Maintien"),
                ElementoPredefinido.Individual("Dossier", "Documents"),
                ElementoPredefinido.Individual("Enveloppe", "Lettre"),
                ElementoPredefinido.Individual("Timbre", "Courrier"),
                ElementoPredefinido.Individual("Colle", "Adhésif"),
                ElementoPredefinido.Individual("Ruban adhésif", "Bande"),
                ElementoPredefinido.Individual("Gomme", "Effacer"),
                ElementoPredefinido.Individual("Taille-crayon", "Pointe"),
                ElementoPredefinido.Individual("Règle", "Mesure"),
                ElementoPredefinido.Individual("Compas", "Cercle"),
                ElementoPredefinido.Individual("Pinceau", "Huile")
            )
        ),

        // === 2. CATÉGORIE : LIEU ===
        ColeccionPredefinida(
            nombre = "Lieux",
            categoria = "Lieu",
            elementos = listOf(
                ElementoPredefinido.Individual("Bibliothèque", "Étagère"),
                ElementoPredefinido.Individual("Forêt", "Végétation"),
                ElementoPredefinido.Individual("Cinéma", "Fauteuils"),
                ElementoPredefinido.Individual("Désert", "Sécheresse"),
                ElementoPredefinido.Individual("Gare", "Quai"),
                ElementoPredefinido.Individual("Hôpital", "Patients"),
                ElementoPredefinido.Individual("Musée", "Exposition"),
                ElementoPredefinido.Individual("Plage", "Vagues"),
                ElementoPredefinido.Individual("Parc", "Balançoires"),
                ElementoPredefinido.Individual("Rivière", "Lit"),
                ElementoPredefinido.Individual("Théâtre", "Rideau"),
                ElementoPredefinido.Individual("Zoo", "Cages"),
                ElementoPredefinido.Individual("Aéroport", "Terminal"),
                ElementoPredefinido.Individual("Salle de sport", "Poids"),
                ElementoPredefinido.Individual("Montagne", "Sommet"),
                ElementoPredefinido.Individual("Supermarché", "Rayons"),
                ElementoPredefinido.Individual("Église", "Autel"),
                ElementoPredefinido.Individual("Château", "Muraille"),
                ElementoPredefinido.Individual("Stade", "Gradins"),
                ElementoPredefinido.Individual("Ferme", "Enclos"),
                ElementoPredefinido.Individual("Volcan", "Magma"),
                ElementoPredefinido.Individual("Île", "Archipel"),
                ElementoPredefinido.Individual("Port", "Quai"),
                ElementoPredefinido.Individual("Restaurant", "Menu"),
                ElementoPredefinido.Individual("Banque", "Distributeur"),
                ElementoPredefinido.Individual("Prison", "Cellules"),
                ElementoPredefinido.Individual("École", "Salles de classe"),
                ElementoPredefinido.Individual("Université", "Faculté"),
                ElementoPredefinido.Individual("Usine", "Production"),
                ElementoPredefinido.Individual("Atelier", "Outils"),
                ElementoPredefinido.Individual("Bureau", "Bureaux"),
                ElementoPredefinido.Individual("Pharmacie", "Médicaments"),
                ElementoPredefinido.Individual("Boulangerie", "Four"),
                ElementoPredefinido.Individual("Salon de coiffure", "Miroirs"),
                ElementoPredefinido.Individual("Station-service", "Carburant"),
                ElementoPredefinido.Individual("Hôtel", "Réception"),
                ElementoPredefinido.Individual("Camping", "Tentes"),
                ElementoPredefinido.Individual("Port", "Bateaux"),
                ElementoPredefinido.Individual("Marché", "Stands"),
                ElementoPredefinido.Individual("Palais", "Royauté"),
                ElementoPredefinido.Individual("Cathédrale", "Gothique"),
                ElementoPredefinido.Individual("Cimetière", "Tombes"),
                ElementoPredefinido.Individual("Jardin", "Fleurs"),
                ElementoPredefinido.Individual("Terrasse", "Vues"),
                ElementoPredefinido.Individual("Sous-sol", "Obscurité"),
                ElementoPredefinido.Individual("Grenier", "Toit"),
                ElementoPredefinido.Individual("Garage", "Voiture"),
                ElementoPredefinido.Individual("Cuisine", "Plaques"),
                ElementoPredefinido.Individual("Salle de bain", "Douche"),
                ElementoPredefinido.Individual("Chambre", "Repos"),
                ElementoPredefinido.Individual("Salon", "Canapé"),
                ElementoPredefinido.Individual("Couloir", "Portes"),
                ElementoPredefinido.Individual("Balcon", "Rambarde"),
                ElementoPredefinido.Individual("Piscine", "Chlore"),
                ElementoPredefinido.Individual("Place", "Fontaine"),
                ElementoPredefinido.Individual("Rue", "Asphalte"),
                ElementoPredefinido.Individual("Avenue", "Trafic"),
                ElementoPredefinido.Individual("Pont", "Rivière"),
                ElementoPredefinido.Individual("Tunnel", "Souterrain"),
                ElementoPredefinido.Individual("Phare", "Côte"),
                ElementoPredefinido.Individual("Falaise", "Hauteur"),
                ElementoPredefinido.Individual("Grotte", "Stalactites"),
                ElementoPredefinido.Individual("Jungle", "Tropicale"),
                ElementoPredefinido.Individual("Savane", "Plaine"),
                ElementoPredefinido.Individual("Marais", "Boue"),
                ElementoPredefinido.Individual("Glacier", "Glace"),
                ElementoPredefinido.Individual("Cascade", "Chute"),
                ElementoPredefinido.Individual("Vallée", "Montagnes"),
                ElementoPredefinido.Individual("Prairie", "Pâturage"),
                ElementoPredefinido.Individual("Désert", "Dunes"),
                ElementoPredefinido.Individual("Port", "Ancres"),
                ElementoPredefinido.Individual("Gare", "Voies"),
                ElementoPredefinido.Individual("Aéroport", "Piste"),
                ElementoPredefinido.Individual("Observatoire", "Étoiles"),
                ElementoPredefinido.Individual("Laboratoire", "Tubes")
            )
        ),

        // === 3. CATÉGORIE : ANIMAL ===
        ColeccionPredefinida(
            nombre = "Animaux",
            categoria = "Animal",
            elementos = listOf(
                ElementoPredefinido.Individual("Lion", "Crinière"),
                ElementoPredefinido.Individual("Éléphant", "Trompe"),
                ElementoPredefinido.Individual("Girafe", "Cou"),
                ElementoPredefinido.Individual("Tigre", "Rayures"),
                ElementoPredefinido.Individual("Ours Polaire", "Arctique"),
                ElementoPredefinido.Individual("Panda", "Bambou"),
                ElementoPredefinido.Individual("Dauphin", "Intelligence"),
                ElementoPredefinido.Individual("Baleine", "Souffle"),
                ElementoPredefinido.Individual("Aigle", "Serres"),
                ElementoPredefinido.Individual("Kangourou", "Poche"),
                ElementoPredefinido.Individual("Pingouin", "Smoking"),
                ElementoPredefinido.Individual("Koala", "Eucalyptus"),
                ElementoPredefinido.Individual("Serpent", "Venin"),
                ElementoPredefinido.Individual("Pieuvre", "Encre"),
                ElementoPredefinido.Individual("Loup", "Hurlement"),
                ElementoPredefinido.Individual("Cheval", "Sabots"),
                ElementoPredefinido.Individual("Singe", "Primate"),
                ElementoPredefinido.Individual("Requin", "Nageoire"),
                ElementoPredefinido.Individual("Abeille", "Ruche"),
                ElementoPredefinido.Individual("Caméléon", "Camouflage"),
                ElementoPredefinido.Individual("Hibou", "Sagesse"),
                ElementoPredefinido.Individual("Vache", "Lait"),
                ElementoPredefinido.Individual("Crocodile", "Mâchoire"),
                ElementoPredefinido.Individual("Papillon", "Métamorphose"),
                ElementoPredefinido.Individual("Chauve-souris", "Sonar"),
                ElementoPredefinido.Individual("Chien", "Loyauté"),
                ElementoPredefinido.Individual("Chat", "Ronronnement"),
                ElementoPredefinido.Individual("Lapin", "Carotte"),
                ElementoPredefinido.Individual("Souris", "Fromage"),
                ElementoPredefinido.Individual("Zèbre", "Noir et blanc"),
                ElementoPredefinido.Individual("Hippopotame", "Rivière"),
                ElementoPredefinido.Individual("Rhinocéros", "Corne"),
                ElementoPredefinido.Individual("Guépard", "Vitesse"),
                ElementoPredefinido.Individual("Hyène", "Rire"),
                ElementoPredefinido.Individual("Renard", "Ruse"),
                ElementoPredefinido.Individual("Ours", "Hibernation"),
                ElementoPredefinido.Individual("Cerf", "Bois"),
                ElementoPredefinido.Individual("Écureuil", "Noix"),
                ElementoPredefinido.Individual("Castor", "Barrage"),
                ElementoPredefinido.Individual("Loutre", "Eau"),
                ElementoPredefinido.Individual("Phoque", "Antarctique"),
                ElementoPredefinido.Individual("Morse", "Défenses"),
                ElementoPredefinido.Individual("Pélican", "Bec"),
                ElementoPredefinido.Individual("Flamant", "Rose"),
                ElementoPredefinido.Individual("Perroquet", "Parole"),
                ElementoPredefinido.Individual("Paon", "Plumage"),
                ElementoPredefinido.Individual("Autruche", "Œuf"),
                ElementoPredefinido.Individual("Cygne", "Lac"),
                ElementoPredefinido.Individual("Corbeau", "Noir"),
                ElementoPredefinido.Individual("Coq", "Aube"),
                ElementoPredefinido.Individual("Poule", "Poulailler"),
                ElementoPredefinido.Individual("Canard", "Bec"),
                ElementoPredefinido.Individual("Crapaud", "Mare"),
                ElementoPredefinido.Individual("Grenouille", "Saut"),
                ElementoPredefinido.Individual("Tortue", "Carapace"),
                ElementoPredefinido.Individual("Iguane", "Reptile"),
                ElementoPredefinido.Individual("Lézard", "Queue"),
                ElementoPredefinido.Individual("Scorpion", "Dard"),
                ElementoPredefinido.Individual("Araignée", "Toile"),
                ElementoPredefinido.Individual("Fourmi", "Fourmilière"),
                ElementoPredefinido.Individual("Sauterelle", "Vert"),
                ElementoPredefinido.Individual("Grillon", "Chant"),
                ElementoPredefinido.Individual("Mouche", "Vol"),
                ElementoPredefinido.Individual("Moustique", "Piqûre"),
                ElementoPredefinido.Individual("Cafard", "Résistance"),
                ElementoPredefinido.Individual("Crabe", "Pinces"),
                ElementoPredefinido.Individual("Homard", "Mer"),
                ElementoPredefinido.Individual("Crevette", "Crustacé"),
                ElementoPredefinido.Individual("Escargot", "Bave"),
                ElementoPredefinido.Individual("Méduse", "Tentacules"),
                ElementoPredefinido.Individual("Étoile de mer", "Bras"),
                ElementoPredefinido.Individual("Hippocampe", "Museau"),
                ElementoPredefinido.Individual("Espadon", "Épée"),
                ElementoPredefinido.Individual("Poisson-clown", "Anémone"),
                ElementoPredefinido.Individual("Anguille", "Électricité")
            )
        ),

        // === 4. CATÉGORIE : NOURRITURE ===
        ColeccionPredefinida(
            nombre = "Gastronomie",
            categoria = "Nourriture",
            elementos = listOf(
                ElementoPredefinido.Individual("Pizza", "Part"),
                ElementoPredefinido.Individual("Sushi", "Wasabi"),
                ElementoPredefinido.Individual("Hamburger", "Cornichon"),
                ElementoPredefinido.Individual("Paella", "Safran"),
                ElementoPredefinido.Individual("Taco", "Épicé"),
                ElementoPredefinido.Individual("Glace", "Cornet"),
                ElementoPredefinido.Individual("Pâtes", "Al dente"),
                ElementoPredefinido.Individual("Salade", "Vinaigrette"),
                ElementoPredefinido.Individual("Chocolat", "Cacao"),
                ElementoPredefinido.Individual("Soupe", "Cuillère"),
                ElementoPredefinido.Individual("Pain", "Mie"),
                ElementoPredefinido.Individual("Fromage", "Fermentation"),
                ElementoPredefinido.Individual("Œuf", "Jaune"),
                ElementoPredefinido.Individual("Pomme", "Péché"),
                ElementoPredefinido.Individual("Pomme de terre", "Frite"),
                ElementoPredefinido.Individual("Steak", "Cuisson"),
                ElementoPredefinido.Individual("Croquette", "Béchamel"),
                ElementoPredefinido.Individual("Yaourt", "Bifidus"),
                ElementoPredefinido.Individual("Café", "Caféine"),
                ElementoPredefinido.Individual("Biscuit", "Pépites"),
                ElementoPredefinido.Individual("Fruits de mer", "Coquille"),
                ElementoPredefinido.Individual("Riz", "Grain"),
                ElementoPredefinido.Individual("Miel", "Douceur"),
                ElementoPredefinido.Individual("Beignet", "Glaçage"),
                ElementoPredefinido.Individual("Sandwich", "Garniture"),
                ElementoPredefinido.Individual("Gâteau", "Bougie"),
                ElementoPredefinido.Individual("Poisson", "Écailles"),
                ElementoPredefinido.Individual("Poulet", "Rôti"),
                ElementoPredefinido.Individual("Lentilles", "Fer"),
                ElementoPredefinido.Individual("Pois chiches", "Ragoût"),
                ElementoPredefinido.Individual("Spaghettis", "Sauce"),
                ElementoPredefinido.Individual("Macaronis", "Gratin"),
                ElementoPredefinido.Individual("Omelette", "Pommes de terre"),
                ElementoPredefinido.Individual("Gaspacho", "Tomate"),
                ElementoPredefinido.Individual("Salmorejo", "Pain"),
                ElementoPredefinido.Individual("Côte de bœuf", "Braise"),
                ElementoPredefinido.Individual("Saumon", "Rose"),
                ElementoPredefinido.Individual("Thon", "Boîte"),
                ElementoPredefinido.Individual("Morue", "Salaison"),
                ElementoPredefinido.Individual("Calamars", "Anneaux"),
                ElementoPredefinido.Individual("Poulpe", "Galicienne"),
                ElementoPredefinido.Individual("Crevettes", "Plancha"),
                ElementoPredefinido.Individual("Boulettes", "Viande"),
                ElementoPredefinido.Individual("Lasagnes", "Couches"),
                ElementoPredefinido.Individual("Cannellonis", "Pâtes"),
                ElementoPredefinido.Individual("Risotto", "Crémeux"),
                ElementoPredefinido.Individual("Couscous", "Semoule"),
                ElementoPredefinido.Individual("Houmous", "Pois chiche"),
                ElementoPredefinido.Individual("Guacamole", "Avocat"),
                ElementoPredefinido.Individual("Burrito", "Haricots"),
                ElementoPredefinido.Individual("Nachos", "Fromage"),
                ElementoPredefinido.Individual("Kebab", "Viande"),
                ElementoPredefinido.Individual("Curry", "Épices"),
                ElementoPredefinido.Individual("Ramen", "Bouillon"),
                ElementoPredefinido.Individual("Dim Sum", "Vapeur"),
                ElementoPredefinido.Individual("Ceviche", "Citron"),
                ElementoPredefinido.Individual("Arepa", "Maïs"),
                ElementoPredefinido.Individual("Empanada", "Pâte"),
                ElementoPredefinido.Individual("Quiche", "Œuf"),
                ElementoPredefinido.Individual("Crêpe", "Sucré"),
                ElementoPredefinido.Individual("Gaufre", "Carrés"),
                ElementoPredefinido.Individual("Churros", "Huile"),
                ElementoPredefinido.Individual("Flan", "Caramel"),
                ElementoPredefinido.Individual("Crème dessert", "Cannelle"),
                ElementoPredefinido.Individual("Riz au lait", "Dessert"),
                ElementoPredefinido.Individual("Brownie", "Chocolat"),
                ElementoPredefinido.Individual("Muffin", "Madeleine"),
                ElementoPredefinido.Individual("Croissant", "Beurre"),
                ElementoPredefinido.Individual("Baguette", "France"),
                ElementoPredefinido.Individual("Bretzel", "Sel"),
                ElementoPredefinido.Individual("Pop-corn", "Maïs"),
                ElementoPredefinido.Individual("Graines de tournesol", "Graines"),
                ElementoPredefinido.Individual("Amandes", "Fruits secs"),
                ElementoPredefinido.Individual("Noix", "Coquille"),
                ElementoPredefinido.Individual("Olives", "Apéritif")
            )
        ),

        // === 5. CATÉGORIE : PROFESSION ===
        ColeccionPredefinida(
            nombre = "Métiers",
            categoria = "Profession",
            elementos = listOf(
                ElementoPredefinido.Individual("Médecin", "Stéthoscope"),
                ElementoPredefinido.Individual("Pompier", "Lance"),
                ElementoPredefinido.Individual("Professeur", "Tableau"),
                ElementoPredefinido.Individual("Policier", "Menottes"),
                ElementoPredefinido.Individual("Cuisinier", "Toque"),
                ElementoPredefinido.Individual("Architecte", "Plan"),
                ElementoPredefinido.Individual("Astronaute", "Gravité"),
                ElementoPredefinido.Individual("Peintre", "Toile"),
                ElementoPredefinido.Individual("Mécanicien", "Écrou"),
                ElementoPredefinido.Individual("Avocat", "Code"),
                ElementoPredefinido.Individual("Musicien", "Partition"),
                ElementoPredefinido.Individual("Scientifique", "Microscope"),
                ElementoPredefinido.Individual("Photographe", "Flash"),
                ElementoPredefinido.Individual("Dentiste", "Carie"),
                ElementoPredefinido.Individual("Pilote", "Cabine"),
                ElementoPredefinido.Individual("Charpentier", "Sciure"),
                ElementoPredefinido.Individual("Juge", "Marteau"),
                ElementoPredefinido.Individual("Vétérinaire", "Animaux"),
                ElementoPredefinido.Individual("Journaliste", "Interview"),
                ElementoPredefinido.Individual("Acteur", "Scénario"),
                ElementoPredefinido.Individual("Fermier", "Récolte"),
                ElementoPredefinido.Individual("Boulanger", "Levure"),
                ElementoPredefinido.Individual("Électricien", "Tension"),
                ElementoPredefinido.Individual("Danseur", "Scène"),
                ElementoPredefinido.Individual("Jardinier", "Taille"),
                ElementoPredefinido.Individual("Facteur", "Boîte aux lettres"),
                ElementoPredefinido.Individual("Écrivain", "Roman"),
                ElementoPredefinido.Individual("Infirmier", "Injection"),
                ElementoPredefinido.Individual("Psychologue", "Thérapie"),
                ElementoPredefinido.Individual("Ingénieur", "Calcul"),
                ElementoPredefinido.Individual("Programmeur", "Code"),
                ElementoPredefinido.Individual("Designer", "Croquis"),
                ElementoPredefinido.Individual("Économiste", "Finances"),
                ElementoPredefinido.Individual("Archéologue", "Fossile"),
                ElementoPredefinido.Individual("Géologue", "Roches"),
                ElementoPredefinido.Individual("Biologiste", "Cellules"),
                ElementoPredefinido.Individual("Chimiste", "Réaction"),
                ElementoPredefinido.Individual("Physicien", "Atome"),
                ElementoPredefinido.Individual("Mathématicien", "Équation"),
                ElementoPredefinido.Individual("Philosophe", "Pensée"),
                ElementoPredefinido.Individual("Historien", "Passé"),
                ElementoPredefinido.Individual("Géographe", "Cartes"),
                ElementoPredefinido.Individual("Politicien", "Votes"),
                ElementoPredefinido.Individual("Diplomate", "Ambassade"),
                ElementoPredefinido.Individual("Militaire", "Uniforme"),
                ElementoPredefinido.Individual("Marin", "Océan"),
                ElementoPredefinido.Individual("Prêtre", "Soutane"),
                ElementoPredefinido.Individual("Sculpteur", "Ciseau"),
                ElementoPredefinido.Individual("Chef d'orchestre", "Baguette"),
                ElementoPredefinido.Individual("Chanteur", "Microphone"),
                ElementoPredefinido.Individual("Poète", "Vers"),
                ElementoPredefinido.Individual("Mannequin", "Défilé"),
                ElementoPredefinido.Individual("Bijoutier", "Diamant"),
                ElementoPredefinido.Individual("Horloger", "Engrenage"),
                ElementoPredefinido.Individual("Cordonnier", "Semelle"),
                ElementoPredefinido.Individual("Tailleur", "Dé à coudre"),
                ElementoPredefinido.Individual("Boucher", "Couteau"),
                ElementoPredefinido.Individual("Poissonnier", "Étals"),
                ElementoPredefinido.Individual("Primeur", "Balance"),
                ElementoPredefinido.Individual("Serveur", "Plateau"),
                ElementoPredefinido.Individual("Réceptionniste", "Téléphone"),
                ElementoPredefinido.Individual("Hôtesse de l'air", "Vol"),
                ElementoPredefinido.Individual("Guide", "Tourisme"),
                ElementoPredefinido.Individual("Bibliothécaire", "Archive"),
                ElementoPredefinido.Individual("Vigile", "Alarme"),
                ElementoPredefinido.Individual("Maçon", "Brique"),
                ElementoPredefinido.Individual("Plombier", "Tuyau"),
                ElementoPredefinido.Individual("Peintre en bâtiment", "Pinceau"),
                ElementoPredefinido.Individual("Serrurier", "Crochet"),
                ElementoPredefinido.Individual("Mineur", "Pioche"),
                ElementoPredefinido.Individual("Bûcheron", "Outil"),
                ElementoPredefinido.Individual("Pêcheur", "Filet"),
                ElementoPredefinido.Individual("Chasseur", "Fusil"),
                ElementoPredefinido.Individual("Balayeur", "Balai"),
                ElementoPredefinido.Individual("Chauffeur de taxi", "Volant")
            )
        )
    )
}