package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosEN {
    val listasPredeterminadas = listOf(
        // === 1. CATEGORY: OBJECT ===
        ColeccionPredefinida(
            nombre = "Everyday Objects",
            categoria = "Object",
            elementos = listOf(
                ElementoPredefinido.Individual("Pencil", "Graphite"),
                ElementoPredefinido.Individual("Mirror", "Reflection"),
                ElementoPredefinido.Individual("Bed sheet", "Bed"),
                ElementoPredefinido.Individual("Fork", "Prongs"),
                ElementoPredefinido.Individual("Telephone", "Communication"),
                ElementoPredefinido.Individual("Watch", "Minutes"),
                ElementoPredefinido.Individual("Key", "Lock"),
                ElementoPredefinido.Individual("Glasses", "Lenses"),
                ElementoPredefinido.Individual("Light bulb", "Filament"),
                ElementoPredefinido.Individual("Table", "Board"),
                ElementoPredefinido.Individual("Plate", "Ceramic"),
                ElementoPredefinido.Individual("Glass", "Crystal"),
                ElementoPredefinido.Individual("Hammer", "Nail"),
                ElementoPredefinido.Individual("Backpack", "Load"),
                ElementoPredefinido.Individual("Umbrella", "Rain"),
                ElementoPredefinido.Individual("Camera", "Lens"),
                ElementoPredefinido.Individual("Book", "Pages"),
                ElementoPredefinido.Individual("Bottle", "Liquid"),
                ElementoPredefinido.Individual("Scissors", "Blade"),
                ElementoPredefinido.Individual("Wallet", "Pocket"),
                ElementoPredefinido.Individual("Chair", "Backrest"),
                ElementoPredefinido.Individual("Pillow", "Feathers"),
                ElementoPredefinido.Individual("Fan", "Blades"),
                ElementoPredefinido.Individual("Battery", "Charge"),
                ElementoPredefinido.Individual("Broom", "Floor"),
                ElementoPredefinido.Individual("Calculator", "Numbers"),
                ElementoPredefinido.Individual("Dictionary", "Definitions"),
                ElementoPredefinido.Individual("Comb", "Hair"),
                ElementoPredefinido.Individual("Spoon", "Soup"),
                ElementoPredefinido.Individual("Towel", "Bath"),
                ElementoPredefinido.Individual("Suitcase", "Travel"),
                ElementoPredefinido.Individual("Belt", "Pants"),
                ElementoPredefinido.Individual("Glove", "Hand"),
                ElementoPredefinido.Individual("Sock", "Foot"),
                ElementoPredefinido.Individual("Cap", "Head"),
                ElementoPredefinido.Individual("Ring", "Finger"),
                ElementoPredefinido.Individual("Necklace", "Neck"),
                ElementoPredefinido.Individual("Bracelet", "Wrist"),
                ElementoPredefinido.Individual("Earring", "Ear"),
                ElementoPredefinido.Individual("Billfold", "Cash"),
                ElementoPredefinido.Individual("Lighter", "Flame"),
                ElementoPredefinido.Individual("Ashtray", "Ash"),
                ElementoPredefinido.Individual("Hand fan", "Wind"),
                ElementoPredefinido.Individual("Cell", "Voltage"),
                ElementoPredefinido.Individual("Controller", "Buttons"),
                ElementoPredefinido.Individual("Keyboard", "Letters"),
                ElementoPredefinido.Individual("Mouse", "Click"),
                ElementoPredefinido.Individual("Monitor", "Screen"),
                ElementoPredefinido.Individual("Headphones", "Sound"),
                ElementoPredefinido.Individual("Microphone", "Voice"),
                ElementoPredefinido.Individual("Speaker", "Volume"),
                ElementoPredefinido.Individual("Charger", "Cable"),
                ElementoPredefinido.Individual("Plug", "Current"),
                ElementoPredefinido.Individual("Bulb", "Illumination"),
                ElementoPredefinido.Individual("Candle", "Wax"),
                ElementoPredefinido.Individual("Rug", "Floor"),
                ElementoPredefinido.Individual("Curtain", "Window"),
                ElementoPredefinido.Individual("Painting", "Wall"),
                ElementoPredefinido.Individual("Vase", "Decoration"),
                ElementoPredefinido.Individual("Basket", "Wicker"),
                ElementoPredefinido.Individual("Box", "Cardboard"),
                ElementoPredefinido.Individual("Bag", "Plastic"),
                ElementoPredefinido.Individual("Trash can", "Waste"),
                ElementoPredefinido.Individual("Stapler", "Office"),
                ElementoPredefinido.Individual("Paperclip", "Hold"),
                ElementoPredefinido.Individual("Folder", "Documents"),
                ElementoPredefinido.Individual("Envelope", "Letter"),
                ElementoPredefinido.Individual("Stamp", "Mail"),
                ElementoPredefinido.Individual("Glue", "Adhesive"),
                ElementoPredefinido.Individual("Tape", "Sticky"),
                ElementoPredefinido.Individual("Eraser", "Erase"),
                ElementoPredefinido.Individual("Sharpener", "Blade"),
                ElementoPredefinido.Individual("Ruler", "Measure"),
                ElementoPredefinido.Individual("Compass", "Circle"),
                ElementoPredefinido.Individual("Paintbrush", "Oil")
            )
        ),

        // === 2. CATEGORY: PLACE ===
        ColeccionPredefinida(
            nombre = "Places",
            categoria = "Place",
            elementos = listOf(
                ElementoPredefinido.Individual("Library", "Bookshelf"),
                ElementoPredefinido.Individual("Forest", "Vegetation"),
                ElementoPredefinido.Individual("Cinema", "Seats"),
                ElementoPredefinido.Individual("Desert", "Drought"),
                ElementoPredefinido.Individual("Station", "Platform"),
                ElementoPredefinido.Individual("Hospital", "Patients"),
                ElementoPredefinido.Individual("Museum", "Exhibition"),
                ElementoPredefinido.Individual("Beach", "Waves"),
                ElementoPredefinido.Individual("Park", "Swings"),
                ElementoPredefinido.Individual("River", "Riverbed"),
                ElementoPredefinido.Individual("Theater", "Curtain"),
                ElementoPredefinido.Individual("Zoo", "Cages"),
                ElementoPredefinido.Individual("Airport", "Terminal"),
                ElementoPredefinido.Individual("Gym", "Weights"),
                ElementoPredefinido.Individual("Mountain", "Peak"),
                ElementoPredefinido.Individual("Supermarket", "Aisles"),
                ElementoPredefinido.Individual("Church", "Altar"),
                ElementoPredefinido.Individual("Castle", "Wall"),
                ElementoPredefinido.Individual("Stadium", "Stands"),
                ElementoPredefinido.Individual("Farm", "Pen"),
                ElementoPredefinido.Individual("Volcano", "Magma"),
                ElementoPredefinido.Individual("Island", "Archipelago"),
                ElementoPredefinido.Individual("Seaport", "Dock"),
                ElementoPredefinido.Individual("Restaurant", "Menu"),
                ElementoPredefinido.Individual("Bank", "ATM"),
                ElementoPredefinido.Individual("Prison", "Cells"),
                ElementoPredefinido.Individual("School", "Classrooms"),
                ElementoPredefinido.Individual("University", "Faculty"),
                ElementoPredefinido.Individual("Factory", "Production"),
                ElementoPredefinido.Individual("Workshop", "Tools"),
                ElementoPredefinido.Individual("Office", "Desks"),
                ElementoPredefinido.Individual("Pharmacy", "Medicines"),
                ElementoPredefinido.Individual("Bakery", "Oven"),
                ElementoPredefinido.Individual("Hairdresser", "Mirrors"),
                ElementoPredefinido.Individual("Gas station", "Fuel"),
                ElementoPredefinido.Individual("Hotel", "Reception"),
                ElementoPredefinido.Individual("Campsite", "Tents"),
                ElementoPredefinido.Individual("Harbor", "Boats"),
                ElementoPredefinido.Individual("Market", "Stalls"),
                ElementoPredefinido.Individual("Palace", "Royalty"),
                ElementoPredefinido.Individual("Cathedral", "Gothic"),
                ElementoPredefinido.Individual("Cemetery", "Graves"),
                ElementoPredefinido.Individual("Garden", "Flowers"),
                ElementoPredefinido.Individual("Terrace", "Views"),
                ElementoPredefinido.Individual("Basement", "Darkness"),
                ElementoPredefinido.Individual("Attic", "Roof"),
                ElementoPredefinido.Individual("Garage", "Car"),
                ElementoPredefinido.Individual("Kitchen", "Stove"),
                ElementoPredefinido.Individual("Bathroom", "Shower"),
                ElementoPredefinido.Individual("Bedroom", "Rest"),
                ElementoPredefinido.Individual("Living room", "Sofa"),
                ElementoPredefinido.Individual("Hallway", "Doors"),
                ElementoPredefinido.Individual("Balcony", "Railing"),
                ElementoPredefinido.Individual("Pool", "Chlorine"),
                ElementoPredefinido.Individual("Square", "Fountain"),
                ElementoPredefinido.Individual("Street", "Asphalt"),
                ElementoPredefinido.Individual("Avenue", "Traffic"),
                ElementoPredefinido.Individual("Bridge", "River"),
                ElementoPredefinido.Individual("Tunnel", "Underground"),
                ElementoPredefinido.Individual("Lighthouse", "Coast"),
                ElementoPredefinido.Individual("Cliff", "Height"),
                ElementoPredefinido.Individual("Cave", "Stalactites"),
                ElementoPredefinido.Individual("Jungle", "Tropical"),
                ElementoPredefinido.Individual("Savanna", "Plains"),
                ElementoPredefinido.Individual("Swamp", "Mud"),
                ElementoPredefinido.Individual("Glacier", "Ice"),
                ElementoPredefinido.Individual("Waterfall", "Drop"),
                ElementoPredefinido.Individual("Valley", "Mountains"),
                ElementoPredefinido.Individual("Meadow", "Pasture"),
                ElementoPredefinido.Individual("Wasteland", "Dunes"),
                ElementoPredefinido.Individual("Marina", "Anchors"),
                ElementoPredefinido.Individual("Train station", "Tracks"),
                ElementoPredefinido.Individual("Airfield", "Runway"),
                ElementoPredefinido.Individual("Observatory", "Stars"),
                ElementoPredefinido.Individual("Laboratory", "Tubes")
            )
        ),

        // === 3. CATEGORY: ANIMAL ===
        ColeccionPredefinida(
            nombre = "Animals",
            categoria = "Animal",
            elementos = listOf(
                ElementoPredefinido.Individual("Lion", "Mane"),
                ElementoPredefinido.Individual("Elephant", "Trunk"),
                ElementoPredefinido.Individual("Giraffe", "Neck"),
                ElementoPredefinido.Individual("Tiger", "Stripes"),
                ElementoPredefinido.Individual("Polar Bear", "Arctic"),
                ElementoPredefinido.Individual("Panda", "Bamboo"),
                ElementoPredefinido.Individual("Dolphin", "Intelligence"),
                ElementoPredefinido.Individual("Whale", "Blowhole"),
                ElementoPredefinido.Individual("Eagle", "Claws"),
                ElementoPredefinido.Individual("Kangaroo", "Pouch"),
                ElementoPredefinido.Individual("Penguin", "Tuxedo"),
                ElementoPredefinido.Individual("Koala", "Eucalyptus"),
                ElementoPredefinido.Individual("Snake", "Venom"),
                ElementoPredefinido.Individual("Octopus", "Ink"),
                ElementoPredefinido.Individual("Wolf", "Howl"),
                ElementoPredefinido.Individual("Horse", "Hooves"),
                ElementoPredefinido.Individual("Monkey", "Primate"),
                ElementoPredefinido.Individual("Shark", "Fin"),
                ElementoPredefinido.Individual("Bee", "Hive"),
                ElementoPredefinido.Individual("Chameleon", "Camouflage"),
                ElementoPredefinido.Individual("Owl", "Wisdom"),
                ElementoPredefinido.Individual("Cow", "Milk"),
                ElementoPredefinido.Individual("Crocodile", "Jaw"),
                ElementoPredefinido.Individual("Butterfly", "Metamorphosis"),
                ElementoPredefinido.Individual("Bat", "Sonar"),
                ElementoPredefinido.Individual("Dog", "Loyalty"),
                ElementoPredefinido.Individual("Cat", "Purr"),
                ElementoPredefinido.Individual("Rabbit", "Carrot"),
                ElementoPredefinido.Individual("Mouse", "Cheese"),
                ElementoPredefinido.Individual("Zebra", "Black and white"),
                ElementoPredefinido.Individual("Hippopotamus", "River"),
                ElementoPredefinido.Individual("Rhinoceros", "Horn"),
                ElementoPredefinido.Individual("Cheetah", "Speed"),
                ElementoPredefinido.Individual("Hyena", "Laugh"),
                ElementoPredefinido.Individual("Fox", "Cunning"),
                ElementoPredefinido.Individual("Bear", "Hibernation"),
                ElementoPredefinido.Individual("Deer", "Antlers"),
                ElementoPredefinido.Individual("Squirrel", "Nuts"),
                ElementoPredefinido.Individual("Beaver", "Dam"),
                ElementoPredefinido.Individual("Otter", "Water"),
                ElementoPredefinido.Individual("Seal", "Antarctica"),
                ElementoPredefinido.Individual("Walrus", "Tusks"),
                ElementoPredefinido.Individual("Pelican", "Beak"),
                ElementoPredefinido.Individual("Flamingo", "Pink"),
                ElementoPredefinido.Individual("Parrot", "Speech"),
                ElementoPredefinido.Individual("Peacock", "Plumage"),
                ElementoPredefinido.Individual("Ostrich", "Egg"),
                ElementoPredefinido.Individual("Swan", "Lake"),
                ElementoPredefinido.Individual("Crow", "Black"),
                ElementoPredefinido.Individual("Rooster", "Dawn"),
                ElementoPredefinido.Individual("Hen", "Coop"),
                ElementoPredefinido.Individual("Duck", "Bill"),
                ElementoPredefinido.Individual("Toad", "Pond"),
                ElementoPredefinido.Individual("Frog", "Jump"),
                ElementoPredefinido.Individual("Turtle", "Shell"),
                ElementoPredefinido.Individual("Iguana", "Reptile"),
                ElementoPredefinido.Individual("Lizard", "Tail"),
                ElementoPredefinido.Individual("Scorpion", "Stinger"),
                ElementoPredefinido.Individual("Spider", "Web"),
                ElementoPredefinido.Individual("Ant", "Anthill"),
                ElementoPredefinido.Individual("Grasshopper", "Green"),
                ElementoPredefinido.Individual("Cricket", "Chirp"),
                ElementoPredefinido.Individual("Fly", "Flight"),
                ElementoPredefinido.Individual("Mosquito", "Bite"),
                ElementoPredefinido.Individual("Cockroach", "Resistance"),
                ElementoPredefinido.Individual("Crab", "Pincers"),
                ElementoPredefinido.Individual("Lobster", "Sea"),
                ElementoPredefinido.Individual("Prawn", "Crustacean"),
                ElementoPredefinido.Individual("Snail", "Slime"),
                ElementoPredefinido.Individual("Jellyfish", "Tentacles"),
                ElementoPredefinido.Individual("Starfish", "Arms"),
                ElementoPredefinido.Individual("Seahorse", "Snout"),
                ElementoPredefinido.Individual("Swordfish", "Sword"),
                ElementoPredefinido.Individual("Clownfish", "Anemone"),
                ElementoPredefinido.Individual("Eel", "Electricity")
            )
        ),

        // === 4. CATEGORY: FOOD ===
        ColeccionPredefinida(
            nombre = "Gastronomy",
            categoria = "Food",
            elementos = listOf(
                ElementoPredefinido.Individual("Pizza", "Slice"),
                ElementoPredefinido.Individual("Sushi", "Wasabi"),
                ElementoPredefinido.Individual("Hamburger", "Pickle"),
                ElementoPredefinido.Individual("Paella", "Saffron"),
                ElementoPredefinido.Individual("Taco", "Spicy"),
                ElementoPredefinido.Individual("Ice cream", "Cone"),
                ElementoPredefinido.Individual("Pasta", "Al dente"),
                ElementoPredefinido.Individual("Salad", "Vinaigrette"),
                ElementoPredefinido.Individual("Chocolate", "Cocoa"),
                ElementoPredefinido.Individual("Soup", "Spoon"),
                ElementoPredefinido.Individual("Bread", "Crumb"),
                ElementoPredefinido.Individual("Cheese", "Fermentation"),
                ElementoPredefinido.Individual("Egg", "Yolk"),
                ElementoPredefinido.Individual("Apple", "Sin"),
                ElementoPredefinido.Individual("Potato", "Fried"),
                ElementoPredefinido.Individual("Steak", "Rare"),
                ElementoPredefinido.Individual("Croquette", "Béchamel"),
                ElementoPredefinido.Individual("Yogurt", "Bifidus"),
                ElementoPredefinido.Individual("Coffee", "Caffeine"),
                ElementoPredefinido.Individual("Cookie", "Chips"),
                ElementoPredefinido.Individual("Seafood", "Shell"),
                ElementoPredefinido.Individual("Rice", "Grain"),
                ElementoPredefinido.Individual("Honey", "Sweetness"),
                ElementoPredefinido.Individual("Donut", "Glaze"),
                ElementoPredefinido.Individual("Sandwich", "Filling"),
                ElementoPredefinido.Individual("Cake", "Candle"),
                ElementoPredefinido.Individual("Fish", "Scales"),
                ElementoPredefinido.Individual("Chicken", "Roasted"),
                ElementoPredefinido.Individual("Lentils", "Iron"),
                ElementoPredefinido.Individual("Chickpeas", "Stew"),
                ElementoPredefinido.Individual("Spaghetti", "Sauce"),
                ElementoPredefinido.Individual("Macaroni", "Gratin"),
                ElementoPredefinido.Individual("Omelette", "Potatoes"),
                ElementoPredefinido.Individual("Gazpacho", "Tomato"),
                ElementoPredefinido.Individual("Salmorejo", "Bread"),
                ElementoPredefinido.Individual("Ribeye", "Grill"),
                ElementoPredefinido.Individual("Salmon", "Pink"),
                ElementoPredefinido.Individual("Tuna", "Can"),
                ElementoPredefinido.Individual("Cod", "Salted"),
                ElementoPredefinido.Individual("Squid", "Rings"),
                ElementoPredefinido.Individual("Octopus", "Galician"),
                ElementoPredefinido.Individual("Prawns", "Grilled"),
                ElementoPredefinido.Individual("Meatballs", "Meat"),
                ElementoPredefinido.Individual("Lasagna", "Layers"),
                ElementoPredefinido.Individual("Cannelloni", "Pasta"),
                ElementoPredefinido.Individual("Risotto", "Creamy"),
                ElementoPredefinido.Individual("Couscous", "Semolina"),
                ElementoPredefinido.Individual("Hummus", "Chickpea"),
                ElementoPredefinido.Individual("Guacamole", "Avocado"),
                ElementoPredefinido.Individual("Burrito", "Beans"),
                ElementoPredefinido.Individual("Nacho", "Cheese"),
                ElementoPredefinido.Individual("Kebab", "Meat"),
                ElementoPredefinido.Individual("Curry", "Spices"),
                ElementoPredefinido.Individual("Ramen", "Broth"),
                ElementoPredefinido.Individual("Dim Sum", "Steam"),
                ElementoPredefinido.Individual("Ceviche", "Lemon"),
                ElementoPredefinido.Individual("Arepa", "Corn"),
                ElementoPredefinido.Individual("Empanada", "Dough"),
                ElementoPredefinido.Individual("Quiche", "Egg"),
                ElementoPredefinido.Individual("Crepe", "Sweet"),
                ElementoPredefinido.Individual("Waffle", "Squares"),
                ElementoPredefinido.Individual("Churros", "Oil"),
                ElementoPredefinido.Individual("Flan", "Caramel"),
                ElementoPredefinido.Individual("Custard", "Cinnamon"),
                ElementoPredefinido.Individual("Rice pudding", "Dessert"),
                ElementoPredefinido.Individual("Brownie", "Chocolate"),
                ElementoPredefinido.Individual("Muffin", "Cupcake"),
                ElementoPredefinido.Individual("Croissant", "Butter"),
                ElementoPredefinido.Individual("Baguette", "France"),
                ElementoPredefinido.Individual("Pretzel", "Salt"),
                ElementoPredefinido.Individual("Popcorn", "Corn"),
                ElementoPredefinido.Individual("Sunflower seeds", "Seeds"),
                ElementoPredefinido.Individual("Almonds", "Nuts"),
                ElementoPredefinido.Individual("Walnuts", "Shell"),
                ElementoPredefinido.Individual("Olives", "Appetizer")
            )
        ),

        // === 5. CATEGORY: PROFESSION ===
        ColeccionPredefinida(
            nombre = "Professions",
            categoria = "Profession",
            elementos = listOf(
                ElementoPredefinido.Individual("Doctor", "Stethoscope"),
                ElementoPredefinido.Individual("Firefighter", "Hose"),
                ElementoPredefinido.Individual("Teacher", "Blackboard"),
                ElementoPredefinido.Individual("Police officer", "Handcuffs"),
                ElementoPredefinido.Individual("Chef", "Hat"),
                ElementoPredefinido.Individual("Architect", "Blueprint"),
                ElementoPredefinido.Individual("Astronaut", "Gravity"),
                ElementoPredefinido.Individual("Painter", "Canvas"),
                ElementoPredefinido.Individual("Mechanic", "Nut"),
                ElementoPredefinido.Individual("Lawyer", "Code"),
                ElementoPredefinido.Individual("Musician", "Sheet music"),
                ElementoPredefinido.Individual("Scientist", "Microscope"),
                ElementoPredefinido.Individual("Photographer", "Flash"),
                ElementoPredefinido.Individual("Dentist", "Cavity"),
                ElementoPredefinido.Individual("Pilot", "Cabin"),
                ElementoPredefinido.Individual("Carpenter", "Sawdust"),
                ElementoPredefinido.Individual("Judge", "Gavel"),
                ElementoPredefinido.Individual("Veterinarian", "Pets"),
                ElementoPredefinido.Individual("Journalist", "Interview"),
                ElementoPredefinido.Individual("Actor", "Script"),
                ElementoPredefinido.Individual("Farmer", "Harvest"),
                ElementoPredefinido.Individual("Baker", "Yeast"),
                ElementoPredefinido.Individual("Electrician", "Voltage"),
                ElementoPredefinido.Individual("Dancer", "Stage"),
                ElementoPredefinido.Individual("Gardener", "Pruning"),
                ElementoPredefinido.Individual("Postman", "Mailbox"),
                ElementoPredefinido.Individual("Writer", "Novel"),
                ElementoPredefinido.Individual("Nurse", "Injection"),
                ElementoPredefinido.Individual("Psychologist", "Therapy"),
                ElementoPredefinido.Individual("Engineer", "Calculation"),
                ElementoPredefinido.Individual("Programmer", "Code"),
                ElementoPredefinido.Individual("Designer", "Sketch"),
                ElementoPredefinido.Individual("Economist", "Finance"),
                ElementoPredefinido.Individual("Archaeologist", "Fossil"),
                ElementoPredefinido.Individual("Geologist", "Rocks"),
                ElementoPredefinido.Individual("Biologist", "Cells"),
                ElementoPredefinido.Individual("Chemist", "Reaction"),
                ElementoPredefinido.Individual("Physicist", "Atom"),
                ElementoPredefinido.Individual("Mathematician", "Equation"),
                ElementoPredefinido.Individual("Philosopher", "Thought"),
                ElementoPredefinido.Individual("Historian", "Past"),
                ElementoPredefinido.Individual("Geographer", "Maps"),
                ElementoPredefinido.Individual("Politician", "Votes"),
                ElementoPredefinido.Individual("Diplomat", "Embassy"),
                ElementoPredefinido.Individual("Military", "Uniform"),
                ElementoPredefinido.Individual("Sailor", "Ocean"),
                ElementoPredefinido.Individual("Priest", "Cassock"),
                ElementoPredefinido.Individual("Sculptor", "Chisel"),
                ElementoPredefinido.Individual("Director", "Baton"),
                ElementoPredefinido.Individual("Singer", "Microphone"),
                ElementoPredefinido.Individual("Poet", "Verse"),
                ElementoPredefinido.Individual("Model", "Runway"),
                ElementoPredefinido.Individual("Jeweler", "Diamond"),
                ElementoPredefinido.Individual("Watchmaker", "Gear"),
                ElementoPredefinido.Individual("Shoemaker", "Sole"),
                ElementoPredefinido.Individual("Tailor", "Thimble"),
                ElementoPredefinido.Individual("Butcher", "Knife"),
                ElementoPredefinido.Individual("Fishmonger", "Counter"),
                ElementoPredefinido.Individual("Greengrocer", "Scale"),
                ElementoPredefinido.Individual("Waiter", "Tray"),
                ElementoPredefinido.Individual("Receptionist", "Telephone"),
                ElementoPredefinido.Individual("Flight attendant", "Flight"),
                ElementoPredefinido.Individual("Guide", "Tourism"),
                ElementoPredefinido.Individual("Librarian", "Archive"),
                ElementoPredefinido.Individual("Security guard", "Alarm"),
                ElementoPredefinido.Individual("Bricklayer", "Brick"),
                ElementoPredefinido.Individual("Plumber", "Pipe"),
                ElementoPredefinido.Individual("House painter", "Brush"),
                ElementoPredefinido.Individual("Locksmith", "Lockpick"),
                ElementoPredefinido.Individual("Miner", "Pickaxe"),
                ElementoPredefinido.Individual("Lumberjack", "Tool"),
                ElementoPredefinido.Individual("Fisherman", "Net"),
                ElementoPredefinido.Individual("Hunter", "Rifle"),
                ElementoPredefinido.Individual("Street sweeper", "Broom"),
                ElementoPredefinido.Individual("Taxi driver", "Steering wheel")
            )
        )
    )
}