package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosZH {
    val listasPredeterminadas = listOf(
        // === 1. CATEGORÍA: OBJETO (物品) ===
        ColeccionPredefinida(
            nombre = "日常用品",
            categoria = "物品",
            elementos = listOf(
                ElementoPredefinido.Individual("铅笔", "石墨"),
                ElementoPredefinido.Individual("镜子", "反射"),
                ElementoPredefinido.Individual("床单", "床"),
                ElementoPredefinido.Individual("叉子", "尖端"),
                ElementoPredefinido.Individual("电话", "通讯"),
                ElementoPredefinido.Individual("手表", "分钟"),
                ElementoPredefinido.Individual("钥匙", "锁"),
                ElementoPredefinido.Individual("眼镜", "镜片"),
                ElementoPredefinido.Individual("灯泡", "灯丝"),
                ElementoPredefinido.Individual("桌子", "桌面"),
                ElementoPredefinido.Individual("盘子", "陶瓷"),
                ElementoPredefinido.Individual("玻璃杯", "水晶"),
                ElementoPredefinido.Individual("锤子", "钉子"),
                ElementoPredefinido.Individual("背包", "负载"),
                ElementoPredefinido.Individual("雨伞", "雨"),
                ElementoPredefinido.Individual("相机", "镜头"),
                ElementoPredefinido.Individual("书", "书页"),
                ElementoPredefinido.Individual("瓶子", "液体"),
                ElementoPredefinido.Individual("剪刀", "刀刃"),
                ElementoPredefinido.Individual("钱包", "口袋"),
                ElementoPredefinido.Individual("椅子", "靠背"),
                ElementoPredefinido.Individual("枕头", "羽毛"),
                ElementoPredefinido.Individual("风扇", "叶片"),
                ElementoPredefinido.Individual("电池", "充电"),
                ElementoPredefinido.Individual("扫帚", "地板"),
                ElementoPredefinido.Individual("计算器", "数字"),
                ElementoPredefinido.Individual("字典", "定义"),
                ElementoPredefinido.Individual("梳子", "头发"),
                ElementoPredefinido.Individual("勺子", "汤"),
                ElementoPredefinido.Individual("毛巾", "洗澡"),
                ElementoPredefinido.Individual("手提箱", "旅行"),
                ElementoPredefinido.Individual("皮带", "裤子"),
                ElementoPredefinido.Individual("手套", "手"),
                ElementoPredefinido.Individual("袜子", "脚"),
                ElementoPredefinido.Individual("帽子", "头"),
                ElementoPredefinido.Individual("戒指", "手指"),
                ElementoPredefinido.Individual("项链", "脖子"),
                ElementoPredefinido.Individual("手镯", "手腕"),
                ElementoPredefinido.Individual("耳环", "耳朵"),
                ElementoPredefinido.Individual("钱包", "现金"),
                ElementoPredefinido.Individual("打火机", "火焰"),
                ElementoPredefinido.Individual("烟灰缸", "烟灰"),
                ElementoPredefinido.Individual("扇子", "风"),
                ElementoPredefinido.Individual("干电池", "电压"),
                ElementoPredefinido.Individual("遥控器", "按钮"),
                ElementoPredefinido.Individual("键盘", "字母"),
                ElementoPredefinido.Individual("鼠标", "点击"),
                ElementoPredefinido.Individual("显示器", "屏幕"),
                ElementoPredefinido.Individual("耳机", "声音"),
                ElementoPredefinido.Individual("麦克风", "声音"),
                ElementoPredefinido.Individual("扬声器", "音量"),
                ElementoPredefinido.Individual("充电器", "线"),
                ElementoPredefinido.Individual("插头", "电流"),
                ElementoPredefinido.Individual("照明灯", "照明"),
                ElementoPredefinido.Individual("蜡烛", "蜡"),
                ElementoPredefinido.Individual("地毯", "地板"),
                ElementoPredefinido.Individual("窗帘", "窗户"),
                ElementoPredefinido.Individual("画", "墙壁"),
                ElementoPredefinido.Individual("花瓶", "装饰"),
                ElementoPredefinido.Individual("篮子", "柳条"),
                ElementoPredefinido.Individual("箱子", "纸板"),
                ElementoPredefinido.Individual("袋子", "塑料"),
                ElementoPredefinido.Individual("垃圾桶", "废物"),
                ElementoPredefinido.Individual("订书机", "办公室"),
                ElementoPredefinido.Individual("回形针", "固定"),
                ElementoPredefinido.Individual("文件夹", "文件"),
                ElementoPredefinido.Individual("信封", "信"),
                ElementoPredefinido.Individual("邮票", "邮件"),
                ElementoPredefinido.Individual("胶水", "粘合剂"),
                ElementoPredefinido.Individual("胶带", "粘性"),
                ElementoPredefinido.Individual("橡皮", "擦除"),
                ElementoPredefinido.Individual("卷笔刀", "刀片"),
                ElementoPredefinido.Individual("尺子", "测量"),
                ElementoPredefinido.Individual("圆规", "圆"),
                ElementoPredefinido.Individual("画笔", "油画")
            )
        ),

        // === 2. CATEGORÍA: LUGAR (地点) ===
        ColeccionPredefinida(
            nombre = "地点",
            categoria = "地点",
            elementos = listOf(
                ElementoPredefinido.Individual("图书馆", "书架"),
                ElementoPredefinido.Individual("森林", "植被"),
                ElementoPredefinido.Individual("电影院", "座位"),
                ElementoPredefinido.Individual("沙漠", "干旱"),
                ElementoPredefinido.Individual("车站", "站台"),
                ElementoPredefinido.Individual("医院", "患者"),
                ElementoPredefinido.Individual("博物馆", "展览"),
                ElementoPredefinido.Individual("海滩", "海浪"),
                ElementoPredefinido.Individual("公园", "秋千"),
                ElementoPredefinido.Individual("河流", "河床"),
                ElementoPredefinido.Individual("剧院", "幕布"),
                ElementoPredefinido.Individual("动物园", "笼子"),
                ElementoPredefinido.Individual("机场", "航站楼"),
                ElementoPredefinido.Individual("健身房", "重量"),
                ElementoPredefinido.Individual("山", "山峰"),
                ElementoPredefinido.Individual("超市", "过道"),
                ElementoPredefinido.Individual("教堂", "祭坛"),
                ElementoPredefinido.Individual("城堡", "城墙"),
                ElementoPredefinido.Individual("体育场", "看台"),
                ElementoPredefinido.Individual("农场", "围栏"),
                ElementoPredefinido.Individual("火山", "岩浆"),
                ElementoPredefinido.Individual("岛屿", "群岛"),
                ElementoPredefinido.Individual("港口", "码头"),
                ElementoPredefinido.Individual("餐厅", "菜单"),
                ElementoPredefinido.Individual("银行", "自动取款机"),
                ElementoPredefinido.Individual("监狱", "牢房"),
                ElementoPredefinido.Individual("学校", "教室"),
                ElementoPredefinido.Individual("大学", "学院"),
                ElementoPredefinido.Individual("工厂", "生产"),
                ElementoPredefinido.Individual("车间", "工具"),
                ElementoPredefinido.Individual("办公室", "办公桌"),
                ElementoPredefinido.Individual("药店", "药物"),
                ElementoPredefinido.Individual("面包店", "烤箱"),
                ElementoPredefinido.Individual("理发店", "镜子"),
                ElementoPredefinido.Individual("加油站", "燃料"),
                ElementoPredefinido.Individual("酒店", "接待处"),
                ElementoPredefinido.Individual("露营地", "帐篷"),
                ElementoPredefinido.Individual("港口", "船只"),
                ElementoPredefinido.Individual("市场", "摊位"),
                ElementoPredefinido.Individual("宫殿", "皇室"),
                ElementoPredefinido.Individual("大教堂", "哥特式"),
                ElementoPredefinido.Individual("墓地", "坟墓"),
                ElementoPredefinido.Individual("花园", "花"),
                ElementoPredefinido.Individual("露台", "风景"),
                ElementoPredefinido.Individual("地下室", "黑暗"),
                ElementoPredefinido.Individual("阁楼", "屋顶"),
                ElementoPredefinido.Individual("车库", "汽车"),
                ElementoPredefinido.Individual("厨房", "炉灶"),
                ElementoPredefinido.Individual("浴室", "淋浴"),
                ElementoPredefinido.Individual("卧室", "休息"),
                ElementoPredefinido.Individual("客厅", "沙发"),
                ElementoPredefinido.Individual("走廊", "门"),
                ElementoPredefinido.Individual("阳台", "栏杆"),
                ElementoPredefinido.Individual("游泳池", "氯"),
                ElementoPredefinido.Individual("广场", "喷泉"),
                ElementoPredefinido.Individual("街道", "柏油路"),
                ElementoPredefinido.Individual("大道", "交通"),
                ElementoPredefinido.Individual("桥梁", "河流"),
                ElementoPredefinido.Individual("隧道", "地下"),
                ElementoPredefinido.Individual("灯塔", "海岸"),
                ElementoPredefinido.Individual("悬崖", "高度"),
                ElementoPredefinido.Individual("洞穴", "钟乳石"),
                ElementoPredefinido.Individual("丛林", "热带"),
                ElementoPredefinido.Individual("稀树草原", "平原"),
                ElementoPredefinido.Individual("沼泽", "泥"),
                ElementoPredefinido.Individual("冰川", "冰"),
                ElementoPredefinido.Individual("瀑布", "掉落"),
                ElementoPredefinido.Individual("山谷", "群山"),
                ElementoPredefinido.Individual("草地", "牧场"),
                ElementoPredefinido.Individual("荒地", "沙丘"),
                ElementoPredefinido.Individual("码头", "锚"),
                ElementoPredefinido.Individual("火车站", "铁轨"),
                ElementoPredefinido.Individual("飞机场", "跑道"),
                ElementoPredefinido.Individual("天文台", "星星"),
                ElementoPredefinido.Individual("实验室", "试管")
            )
        ),

        // === 3. CATEGORÍA: ANIMAL (动物) ===
        ColeccionPredefinida(
            nombre = "动物",
            categoria = "动物",
            elementos = listOf(
                ElementoPredefinido.Individual("狮子", "鬃毛"),
                ElementoPredefinido.Individual("大象", "象鼻"),
                ElementoPredefinido.Individual("长颈鹿", "脖子"),
                ElementoPredefinido.Individual("老虎", "条纹"),
                ElementoPredefinido.Individual("北极熊", "北极"),
                ElementoPredefinido.Individual("熊猫", "竹子"),
                ElementoPredefinido.Individual("海豚", "智力"),
                ElementoPredefinido.Individual("鲸鱼", "喷水孔"),
                ElementoPredefinido.Individual("老鹰", "爪子"),
                ElementoPredefinido.Individual("袋鼠", "育儿袋"),
                ElementoPredefinido.Individual("企鹅", "燕尾服"),
                ElementoPredefinido.Individual("考拉", "桉树"),
                ElementoPredefinido.Individual("蛇", "毒液"),
                ElementoPredefinido.Individual("章鱼", "墨水"),
                ElementoPredefinido.Individual("狼", "嚎叫"),
                ElementoPredefinido.Individual("马", "马蹄"),
                ElementoPredefinido.Individual("猴子", "灵长类"),
                ElementoPredefinido.Individual("鲨鱼", "鳍"),
                ElementoPredefinido.Individual("蜜蜂", "蜂巢"),
                ElementoPredefinido.Individual("变色龙", "伪装"),
                ElementoPredefinido.Individual("猫头鹰", "智慧"),
                ElementoPredefinido.Individual("牛", "牛奶"),
                ElementoPredefinido.Individual("鳄鱼", "下巴"),
                ElementoPredefinido.Individual("蝴蝶", "蜕变"),
                ElementoPredefinido.Individual("蝙蝠", "声纳"),
                ElementoPredefinido.Individual("狗", "忠诚"),
                ElementoPredefinido.Individual("猫", "呼噜声"),
                ElementoPredefinido.Individual("兔子", "胡萝卜"),
                ElementoPredefinido.Individual("老鼠", "奶酪"),
                ElementoPredefinido.Individual("斑马", "黑白"),
                ElementoPredefinido.Individual("河马", "河流"),
                ElementoPredefinido.Individual("犀牛", "角"),
                ElementoPredefinido.Individual("猎豹", "速度"),
                ElementoPredefinido.Individual("鬣狗", "笑声"),
                ElementoPredefinido.Individual("狐狸", "狡猾"),
                ElementoPredefinido.Individual("熊", "冬眠"),
                ElementoPredefinido.Individual("鹿", "鹿角"),
                ElementoPredefinido.Individual("松鼠", "坚果"),
                ElementoPredefinido.Individual("海狸", "水坝"),
                ElementoPredefinido.Individual("水獭", "水"),
                ElementoPredefinido.Individual("海豹", "南极洲"),
                ElementoPredefinido.Individual("海象", "象牙"),
                ElementoPredefinido.Individual("鹈鹕", "喙"),
                ElementoPredefinido.Individual("火烈鸟", "粉红色"),
                ElementoPredefinido.Individual("鹦鹉", "说话"),
                ElementoPredefinido.Individual("孔雀", "羽毛"),
                ElementoPredefinido.Individual("鸵鸟", "蛋"),
                ElementoPredefinido.Individual("天鹅", "湖"),
                ElementoPredefinido.Individual("乌鸦", "黑色"),
                ElementoPredefinido.Individual("公鸡", "黎明"),
                ElementoPredefinido.Individual("母鸡", "鸡舍"),
                ElementoPredefinido.Individual("鸭子", "喙"),
                ElementoPredefinido.Individual("蟾蜍", "池塘"),
                ElementoPredefinido.Individual("青蛙", "跳跃"),
                ElementoPredefinido.Individual("乌龟", "壳"),
                ElementoPredefinido.Individual("鬣蜥", "爬行动物"),
                ElementoPredefinido.Individual("蜥蜴", "尾巴"),
                ElementoPredefinido.Individual("蝎子", "毒刺"),
                ElementoPredefinido.Individual("蜘蛛", "蜘蛛网"),
                ElementoPredefinido.Individual("蚂蚁", "蚁丘"),
                ElementoPredefinido.Individual("蚱蜢", "绿色"),
                ElementoPredefinido.Individual("蟋蟀", "叫声"),
                ElementoPredefinido.Individual("苍蝇", "飞行"),
                ElementoPredefinido.Individual("蚊子", "叮咬"),
                ElementoPredefinido.Individual("蟑螂", "抵抗力"),
                ElementoPredefinido.Individual("螃蟹", "钳子"),
                ElementoPredefinido.Individual("龙虾", "海洋"),
                ElementoPredefinido.Individual("虾", "甲壳类"),
                ElementoPredefinido.Individual("蜗牛", "粘液"),
                ElementoPredefinido.Individual("水母", "触手"),
                ElementoPredefinido.Individual("海星", "手臂"),
                ElementoPredefinido.Individual("海马", "鼻子"),
                ElementoPredefinido.Individual("剑鱼", "剑"),
                ElementoPredefinido.Individual("小丑鱼", "海葵"),
                ElementoPredefinido.Individual("鳗鱼", "电")
            )
        ),

        // === 4. CATEGORÍA: COMIDA (食物) ===
        ColeccionPredefinida(
            nombre = "美食",
            categoria = "食物",
            elementos = listOf(
                ElementoPredefinido.Individual("披萨", "切片"),
                ElementoPredefinido.Individual("寿司", "芥末"),
                ElementoPredefinido.Individual("汉堡", "酸黄瓜"),
                ElementoPredefinido.Individual("西班牙海鲜饭", "藏红花"),
                ElementoPredefinido.Individual("塔可", "辛辣"),
                ElementoPredefinido.Individual("冰淇淋", "蛋筒"),
                ElementoPredefinido.Individual("意大利面", "有嚼劲"),
                ElementoPredefinido.Individual("沙拉", "油醋汁"),
                ElementoPredefinido.Individual("巧克力", "可可"),
                ElementoPredefinido.Individual("汤", "勺子"),
                ElementoPredefinido.Individual("面包", "面包屑"),
                ElementoPredefinido.Individual("奶酪", "发酵"),
                ElementoPredefinido.Individual("鸡蛋", "蛋黄"),
                ElementoPredefinido.Individual("苹果", "原罪"),
                ElementoPredefinido.Individual("土豆", "油炸"),
                ElementoPredefinido.Individual("牛排", "几分熟"),
                ElementoPredefinido.Individual("可乐饼", "调味汁"),
                ElementoPredefinido.Individual("酸奶", "双歧杆菌"),
                ElementoPredefinido.Individual("咖啡", "咖啡因"),
                ElementoPredefinido.Individual("饼干", "巧克力豆"),
                ElementoPredefinido.Individual("海鲜", "贝壳"),
                ElementoPredefinido.Individual("米饭", "谷物"),
                ElementoPredefinido.Individual("蜂蜜", "甜味"),
                ElementoPredefinido.Individual("甜甜圈", "糖霜"),
                ElementoPredefinido.Individual("三明治", "馅料"),
                ElementoPredefinido.Individual("蛋糕", "蜡烛"),
                ElementoPredefinido.Individual("鱼", "鳞片"),
                ElementoPredefinido.Individual("鸡肉", "烤"),
                ElementoPredefinido.Individual("扁豆", "铁"),
                ElementoPredefinido.Individual("鹰嘴豆", "炖菜"),
                ElementoPredefinido.Individual("意大利细面", "酱汁"),
                ElementoPredefinido.Individual("通心粉", "焗烤"),
                ElementoPredefinido.Individual("煎蛋饼", "土豆"),
                ElementoPredefinido.Individual("西班牙凉菜汤", "西红柿"),
                ElementoPredefinido.Individual("萨尔莫雷霍", "面包"),
                ElementoPredefinido.Individual("肋眼牛排", "烤架"),
                ElementoPredefinido.Individual("三文鱼", "粉红色"),
                ElementoPredefinido.Individual("金枪鱼", "罐头"),
                ElementoPredefinido.Individual("鳕鱼", "腌制"),
                ElementoPredefinido.Individual("鱿鱼", "鱿鱼圈"),
                ElementoPredefinido.Individual("章鱼", "加利西亚风味"),
                ElementoPredefinido.Individual("虾", "铁板"),
                ElementoPredefinido.Individual("肉丸", "肉"),
                ElementoPredefinido.Individual("烤宽面条", "分层"),
                ElementoPredefinido.Individual("碎肉卷", "意面"),
                ElementoPredefinido.Individual("意大利炖饭", "奶油味"),
                ElementoPredefinido.Individual("古斯古斯", "粗粒小麦粉"),
                ElementoPredefinido.Individual("鹰嘴豆泥", "鹰嘴豆"),
                ElementoPredefinido.Individual("鳄梨酱", "牛油果"),
                ElementoPredefinido.Individual("墨西哥卷饼", "豆子"),
                ElementoPredefinido.Individual("玉米片", "奶酪"),
                ElementoPredefinido.Individual("烤肉串", "肉"),
                ElementoPredefinido.Individual("咖喱", "香料"),
                ElementoPredefinido.Individual("拉面", "肉汤"),
                ElementoPredefinido.Individual("点心", "蒸汽"),
                ElementoPredefinido.Individual("酸橘汁腌鱼", "柠檬"),
                ElementoPredefinido.Individual("玉米饼", "玉米"),
                ElementoPredefinido.Individual("馅饼", "面团"),
                ElementoPredefinido.Individual("法式咸派", "鸡蛋"),
                ElementoPredefinido.Individual("可丽饼", "甜点"),
                ElementoPredefinido.Individual("华夫饼", "方块"),
                ElementoPredefinido.Individual("吉拿棒", "油"),
                ElementoPredefinido.Individual("焦糖布丁", "焦糖"),
                ElementoPredefinido.Individual("蛋奶冻", "肉桂"),
                ElementoPredefinido.Individual("大米布丁", "甜点"),
                ElementoPredefinido.Individual("布朗尼", "巧克力"),
                ElementoPredefinido.Individual("松饼", "纸杯蛋糕"),
                ElementoPredefinido.Individual("牛角包", "黄油"),
                ElementoPredefinido.Individual("法棍", "法国"),
                ElementoPredefinido.Individual("椒盐卷饼", "盐"),
                ElementoPredefinido.Individual("爆米花", "玉米"),
                ElementoPredefinido.Individual("葵花籽", "瓜子"),
                ElementoPredefinido.Individual("杏仁", "坚果"),
                ElementoPredefinido.Individual("核桃", "核桃壳"),
                ElementoPredefinido.Individual("橄榄", "开胃菜")
            )
        ),

        // === 5. CATEGORÍA: PROFESIÓN (职业) ===
        ColeccionPredefinida(
            nombre = "职业",
            categoria = "职业",
            elementos = listOf(
                ElementoPredefinido.Individual("医生", "听诊器"),
                ElementoPredefinido.Individual("消防员", "软管"),
                ElementoPredefinido.Individual("老师", "黑板"),
                ElementoPredefinido.Individual("警察", "手铐"),
                ElementoPredefinido.Individual("厨师", "帽子"),
                ElementoPredefinido.Individual("建筑师", "蓝图"),
                ElementoPredefinido.Individual("宇航员", "重力"),
                ElementoPredefinido.Individual("画家", "画布"),
                ElementoPredefinido.Individual("机械师", "螺母"),
                ElementoPredefinido.Individual("律师", "法律"),
                ElementoPredefinido.Individual("音乐家", "乐谱"),
                ElementoPredefinido.Individual("科学家", "显微镜"),
                ElementoPredefinido.Individual("摄影师", "闪光灯"),
                ElementoPredefinido.Individual("牙医", "蛀牙"),
                ElementoPredefinido.Individual("飞行员", "驾驶舱"),
                ElementoPredefinido.Individual("木匠", "锯末"),
                ElementoPredefinido.Individual("法官", "法槌"),
                ElementoPredefinido.Individual("兽医", "宠物"),
                ElementoPredefinido.Individual("记者", "采访"),
                ElementoPredefinido.Individual("演员", "剧本"),
                ElementoPredefinido.Individual("农民", "丰收"),
                ElementoPredefinido.Individual("面包师", "酵母"),
                ElementoPredefinido.Individual("电工", "电压"),
                ElementoPredefinido.Individual("舞者", "舞台"),
                ElementoPredefinido.Individual("园丁", "修剪"),
                ElementoPredefinido.Individual("邮递员", "邮箱"),
                ElementoPredefinido.Individual("作家", "小说"),
                ElementoPredefinido.Individual("护士", "注射"),
                ElementoPredefinido.Individual("心理学家", "治疗"),
                ElementoPredefinido.Individual("工程师", "计算"),
                ElementoPredefinido.Individual("程序员", "代码"),
                ElementoPredefinido.Individual("设计师", "草图"),
                ElementoPredefinido.Individual("经济学家", "金融"),
                ElementoPredefinido.Individual("考古学家", "化石"),
                ElementoPredefinido.Individual("地质学家", "岩石"),
                ElementoPredefinido.Individual("生物学家", "细胞"),
                ElementoPredefinido.Individual("化学家", "反应"),
                ElementoPredefinido.Individual("物理学家", "原子"),
                ElementoPredefinido.Individual("数学家", "方程"),
                ElementoPredefinido.Individual("哲学家", "思想"),
                ElementoPredefinido.Individual("历史学家", "过去"),
                ElementoPredefinido.Individual("地理学家", "地图"),
                ElementoPredefinido.Individual("政治家", "选票"),
                ElementoPredefinido.Individual("外交官", "大使馆"),
                ElementoPredefinido.Individual("军人", "制服"),
                ElementoPredefinido.Individual("水手", "海洋"),
                ElementoPredefinido.Individual("神父", "法衣"),
                ElementoPredefinido.Individual("雕塑家", "凿子"),
                ElementoPredefinido.Individual("指挥家", "指挥棒"),
                ElementoPredefinido.Individual("歌手", "麦克风"),
                ElementoPredefinido.Individual("诗人", "诗歌"),
                ElementoPredefinido.Individual("模特", "T台"),
                ElementoPredefinido.Individual("珠宝商", "钻石"),
                ElementoPredefinido.Individual("钟表匠", "齿轮"),
                ElementoPredefinido.Individual("鞋匠", "鞋底"),
                ElementoPredefinido.Individual("裁缝", "顶针"),
                ElementoPredefinido.Individual("屠夫", "刀"),
                ElementoPredefinido.Individual("鱼贩", "柜台"),
                ElementoPredefinido.Individual("果蔬商", "秤"),
                ElementoPredefinido.Individual("服务员", "托盘"),
                ElementoPredefinido.Individual("接待员", "电话"),
                ElementoPredefinido.Individual("空乘", "航班"),
                ElementoPredefinido.Individual("导游", "旅游"),
                ElementoPredefinido.Individual("图书管理员", "档案"),
                ElementoPredefinido.Individual("保安", "警报"),
                ElementoPredefinido.Individual("泥瓦匠", "砖"),
                ElementoPredefinido.Individual("水管工", "水管"),
                ElementoPredefinido.Individual("油漆工", "刷子"),
                ElementoPredefinido.Individual("锁匠", "开锁工具"),
                ElementoPredefinido.Individual("矿工", "镐"),
                ElementoPredefinido.Individual("伐木工", "工具"),
                ElementoPredefinido.Individual("渔夫", "网"),
                ElementoPredefinido.Individual("猎人", "步枪"),
                ElementoPredefinido.Individual("清洁工", "扫帚"),
                ElementoPredefinido.Individual("出租车司机", "方向盘")
            )
        )
    )
}