package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosIT {
    val listasPredeterminadas = listOf(
        // === 1. CATEGORIA: OGGETTO ===
        ColeccionPredefinida(
            nombre = "Oggetti Quotidiani",
            categoria = "Oggetto",
            elementos = listOf(
                ElementoPredefinido.Individual("Matita", "Grafite"),
                ElementoPredefinido.Individual("Specchio", "Riflesso"),
                ElementoPredefinido.Individual("Lenzuolo", "Letto"),
                ElementoPredefinido.Individual("Forchetta", "Punte"),
                ElementoPredefinido.Individual("Telefono", "Comunicazione"),
                ElementoPredefinido.Individual("Orologio", "Minuti"),
                ElementoPredefinido.Individual("Chiave", "Serratura"),
                ElementoPredefinido.Individual("Occhiali", "Lenti"),
                ElementoPredefinido.Individual("Lampadina", "Filamento"),
                ElementoPredefinido.Individual("Tavolo", "Tavola"),
                ElementoPredefinido.Individual("Piatto", "Ceramica"),
                ElementoPredefinido.Individual("Bicchiere", "Cristallo"),
                ElementoPredefinido.Individual("Martello", "Chiodo"),
                ElementoPredefinido.Individual("Zaino", "Carico"),
                ElementoPredefinido.Individual("Ombrello", "Pioggia"),
                ElementoPredefinido.Individual("Fotocamera", "Obiettivo"),
                ElementoPredefinido.Individual("Libro", "Pagine"),
                ElementoPredefinido.Individual("Bottiglia", "Liquido"),
                ElementoPredefinido.Individual("Forbici", "Lama"),
                ElementoPredefinido.Individual("Portafoglio", "Tasca"),
                ElementoPredefinido.Individual("Sedia", "Schienale"),
                ElementoPredefinido.Individual("Cuscino", "Piume"),
                ElementoPredefinido.Individual("Ventilatore", "Pale"),
                ElementoPredefinido.Individual("Batteria", "Carica"),
                ElementoPredefinido.Individual("Scopa", "Pavimento"),
                ElementoPredefinido.Individual("Calcolatrice", "Numeri"),
                ElementoPredefinido.Individual("Dizionario", "Definizioni"),
                ElementoPredefinido.Individual("Pettine", "Capelli"),
                ElementoPredefinido.Individual("Cucchiaio", "Zuppa"),
                ElementoPredefinido.Individual("Asciugamano", "Bagno"),
                ElementoPredefinido.Individual("Valigia", "Viaggio"),
                ElementoPredefinido.Individual("Cintura", "Pantaloni"),
                ElementoPredefinido.Individual("Guanto", "Mano"),
                ElementoPredefinido.Individual("Calzino", "Piede"),
                ElementoPredefinido.Individual("Cappello", "Testa"),
                ElementoPredefinido.Individual("Anello", "Dito"),
                ElementoPredefinido.Individual("Collana", "Collo"),
                ElementoPredefinido.Individual("Bracciale", "Polso"),
                ElementoPredefinido.Individual("Orecchino", "Orecchio"),
                ElementoPredefinido.Individual("Portamonete", "Contanti"),
                ElementoPredefinido.Individual("Accendino", "Fiamma"),
                ElementoPredefinido.Individual("Posacenere", "Cenere"),
                ElementoPredefinido.Individual("Ventaglio", "Vento"),
                ElementoPredefinido.Individual("Pila", "Voltaggio"),
                ElementoPredefinido.Individual("Telecomando", "Pulsanti"),
                ElementoPredefinido.Individual("Tastiera", "Lettere"),
                ElementoPredefinido.Individual("Mouse", "Clic"),
                ElementoPredefinido.Individual("Monitor", "Schermo"),
                ElementoPredefinido.Individual("Cuffie", "Suono"),
                ElementoPredefinido.Individual("Microfono", "Voce"),
                ElementoPredefinido.Individual("Altoparlante", "Volume"),
                ElementoPredefinido.Individual("Caricabatterie", "Cavo"),
                ElementoPredefinido.Individual("Spina", "Corrente"),
                ElementoPredefinido.Individual("Lampadina", "Illuminazione"),
                ElementoPredefinido.Individual("Candela", "Cera"),
                ElementoPredefinido.Individual("Tappeto", "Pavimento"),
                ElementoPredefinido.Individual("Tenda", "Finestra"),
                ElementoPredefinido.Individual("Quadro", "Parete"),
                ElementoPredefinido.Individual("Vaso", "Decorazione"),
                ElementoPredefinido.Individual("Cesto", "Vimini"),
                ElementoPredefinido.Individual("Scatola", "Cartone"),
                ElementoPredefinido.Individual("Borsa", "Plastica"),
                ElementoPredefinido.Individual("Cestino", "Rifiuti"),
                ElementoPredefinido.Individual("Cucitrice", "Ufficio"),
                ElementoPredefinido.Individual("Graffetta", "Fermaglio"),
                ElementoPredefinido.Individual("Cartella", "Documenti"),
                ElementoPredefinido.Individual("Busta", "Lettera"),
                ElementoPredefinido.Individual("Francobollo", "Posta"),
                ElementoPredefinido.Individual("Colla", "Adesivo"),
                ElementoPredefinido.Individual("Nastro", "Adesivo"),
                ElementoPredefinido.Individual("Gomma", "Cancellare"),
                ElementoPredefinido.Individual("Temperamatite", "Punta"),
                ElementoPredefinido.Individual("Righello", "Misura"),
                ElementoPredefinido.Individual("Compasso", "Cerchio"),
                ElementoPredefinido.Individual("Pennello", "Olio")
            )
        ),

        // === 2. CATEGORIA: LUOGO ===
        ColeccionPredefinida(
            nombre = "Luoghi",
            categoria = "Luogo",
            elementos = listOf(
                ElementoPredefinido.Individual("Biblioteca", "Scaffale"),
                ElementoPredefinido.Individual("Foresta", "Vegetazione"),
                ElementoPredefinido.Individual("Cinema", "Poltrone"),
                ElementoPredefinido.Individual("Deserto", "Siccità"),
                ElementoPredefinido.Individual("Stazione", "Binario"),
                ElementoPredefinido.Individual("Ospedale", "Pazienti"),
                ElementoPredefinido.Individual("Museo", "Mostra"),
                ElementoPredefinido.Individual("Spiaggia", "Onde"),
                ElementoPredefinido.Individual("Parco", "Altalene"),
                ElementoPredefinido.Individual("Fiume", "Letto"),
                ElementoPredefinido.Individual("Teatro", "Sipario"),
                ElementoPredefinido.Individual("Zoo", "Gabbie"),
                ElementoPredefinido.Individual("Aeroporto", "Terminal"),
                ElementoPredefinido.Individual("Palestra", "Pesi"),
                ElementoPredefinido.Individual("Montagna", "Cima"),
                ElementoPredefinido.Individual("Supermercato", "Corsie"),
                ElementoPredefinido.Individual("Chiesa", "Altare"),
                ElementoPredefinido.Individual("Castello", "Mura"),
                ElementoPredefinido.Individual("Stadio", "Spalti"),
                ElementoPredefinido.Individual("Fattoria", "Recinto"),
                ElementoPredefinido.Individual("Vulcano", "Magma"),
                ElementoPredefinido.Individual("Isola", "Arcipelago"),
                ElementoPredefinido.Individual("Porto", "Molo"),
                ElementoPredefinido.Individual("Ristorante", "Menu"),
                ElementoPredefinido.Individual("Banca", "Bancomat"),
                ElementoPredefinido.Individual("Prigione", "Celle"),
                ElementoPredefinido.Individual("Scuola", "Aule"),
                ElementoPredefinido.Individual("Università", "Facoltà"),
                ElementoPredefinido.Individual("Fabbrica", "Produzione"),
                ElementoPredefinido.Individual("Officina", "Strumenti"),
                ElementoPredefinido.Individual("Ufficio", "Scrivanie"),
                ElementoPredefinido.Individual("Farmacia", "Farmaci"),
                ElementoPredefinido.Individual("Panetteria", "Forno"),
                ElementoPredefinido.Individual("Parrucchiere", "Specchi"),
                ElementoPredefinido.Individual("Stazione di servizio", "Carburante"),
                ElementoPredefinido.Individual("Hotel", "Reception"),
                ElementoPredefinido.Individual("Campeggio", "Tende"),
                ElementoPredefinido.Individual("Porto", "Barche"),
                ElementoPredefinido.Individual("Mercato", "Bancarelle"),
                ElementoPredefinido.Individual("Palazzo", "Realtà"),
                ElementoPredefinido.Individual("Cattedrale", "Gotico"),
                ElementoPredefinido.Individual("Cimitero", "Tombe"),
                ElementoPredefinido.Individual("Giardino", "Fiori"),
                ElementoPredefinido.Individual("Terrazza", "Vista"),
                ElementoPredefinido.Individual("Cantina", "Oscurità"),
                ElementoPredefinido.Individual("Soffitta", "Tetto"),
                ElementoPredefinido.Individual("Garage", "Auto"),
                ElementoPredefinido.Individual("Cucina", "Fornelli"),
                ElementoPredefinido.Individual("Bagno", "Doccia"),
                ElementoPredefinido.Individual("Camera da letto", "Riposo"),
                ElementoPredefinido.Individual("Soggiorno", "Divano"),
                ElementoPredefinido.Individual("Corridoio", "Porte"),
                ElementoPredefinido.Individual("Balcone", "Ringhiera"),
                ElementoPredefinido.Individual("Piscina", "Cloro"),
                ElementoPredefinido.Individual("Piazza", "Fontana"),
                ElementoPredefinido.Individual("Strada", "Asfalto"),
                ElementoPredefinido.Individual("Viale", "Traffico"),
                ElementoPredefinido.Individual("Ponte", "Fiume"),
                ElementoPredefinido.Individual("Tunnel", "Sotterraneo"),
                ElementoPredefinido.Individual("Faro", "Costa"),
                ElementoPredefinido.Individual("Scogliera", "Altezza"),
                ElementoPredefinido.Individual("Grotta", "Stalattiti"),
                ElementoPredefinido.Individual("Giungla", "Tropicale"),
                ElementoPredefinido.Individual("Savana", "Pianura"),
                ElementoPredefinido.Individual("Palude", "Fango"),
                ElementoPredefinido.Individual("Ghiacciaio", "Ghiaccio"),
                ElementoPredefinido.Individual("Cascata", "Salto"),
                ElementoPredefinido.Individual("Valle", "Montagne"),
                ElementoPredefinido.Individual("Prateria", "Pascolo"),
                ElementoPredefinido.Individual("Deserto", "Dune"),
                ElementoPredefinido.Individual("Porto", "Ancore"),
                ElementoPredefinido.Individual("Stazione ferroviaria", "Binari"),
                ElementoPredefinido.Individual("Aeroporto", "Pista"),
                ElementoPredefinido.Individual("Osservatorio", "Stelle"),
                ElementoPredefinido.Individual("Laboratorio", "Tubi")
            )
        ),

        // === 3. CATEGORIA: ANIMALE ===
        ColeccionPredefinida(
            nombre = "Animali",
            categoria = "Animale",
            elementos = listOf(
                ElementoPredefinido.Individual("Leone", "Criniera"),
                ElementoPredefinido.Individual("Elefante", "Proboscide"),
                ElementoPredefinido.Individual("Giraffa", "Collo"),
                ElementoPredefinido.Individual("Tigre", "Strisce"),
                ElementoPredefinido.Individual("Orso Polare", "Artico"),
                ElementoPredefinido.Individual("Panda", "Bambù"),
                ElementoPredefinido.Individual("Delfino", "Intelligenza"),
                ElementoPredefinido.Individual("Balena", "Soffio"),
                ElementoPredefinido.Individual("Aquila", "Artigli"),
                ElementoPredefinido.Individual("Canguro", "Marsupio"),
                ElementoPredefinido.Individual("Pinguino", "Smoking"),
                ElementoPredefinido.Individual("Koala", "Eucalipto"),
                ElementoPredefinido.Individual("Serpente", "Veleno"),
                ElementoPredefinido.Individual("Polpo", "Inchiostro"),
                ElementoPredefinido.Individual("Lupo", "Ululato"),
                ElementoPredefinido.Individual("Cavallo", "Zoccoli"),
                ElementoPredefinido.Individual("Scimmia", "Primate"),
                ElementoPredefinido.Individual("Squalo", "Pinna"),
                ElementoPredefinido.Individual("Ape", "Alveare"),
                ElementoPredefinido.Individual("Camaleonte", "Mimetismo"),
                ElementoPredefinido.Individual("Gufo", "Saggezza"),
                ElementoPredefinido.Individual("Mucca", "Latte"),
                ElementoPredefinido.Individual("Coccodrillo", "Mascella"),
                ElementoPredefinido.Individual("Farfalla", "Metamorfosi"),
                ElementoPredefinido.Individual("Pipistrello", "Sonar"),
                ElementoPredefinido.Individual("Cane", "Lealtà"),
                ElementoPredefinido.Individual("Gatto", "Fusa"),
                ElementoPredefinido.Individual("Coniglio", "Carota"),
                ElementoPredefinido.Individual("Topo", "Formaggio"),
                ElementoPredefinido.Individual("Zebra", "Bianconero"),
                ElementoPredefinido.Individual("Ippopotamo", "Fiume"),
                ElementoPredefinido.Individual("Rinoceronte", "Corno"),
                ElementoPredefinido.Individual("Ghepardo", "Velocità"),
                ElementoPredefinido.Individual("Iena", "Risata"),
                ElementoPredefinido.Individual("Volpe", "Astuzia"),
                ElementoPredefinido.Individual("Orso", "Letargo"),
                ElementoPredefinido.Individual("Cervo", "Palchi"),
                ElementoPredefinido.Individual("Scoiattolo", "Noci"),
                ElementoPredefinido.Individual("Castoro", "Diga"),
                ElementoPredefinido.Individual("Lontra", "Acqua"),
                ElementoPredefinido.Individual("Foca", "Antartide"),
                ElementoPredefinido.Individual("Tricheco", "Zanne"),
                ElementoPredefinido.Individual("Pellicano", "Becco"),
                ElementoPredefinido.Individual("Fenicottero", "Rosa"),
                ElementoPredefinido.Individual("Pappagallo", "Parola"),
                ElementoPredefinido.Individual("Pavone", "Piumaggio"),
                ElementoPredefinido.Individual("Struzzo", "Uovo"),
                ElementoPredefinido.Individual("Cigno", "Lago"),
                ElementoPredefinido.Individual("Corvo", "Nero"),
                ElementoPredefinido.Individual("Gallo", "Alba"),
                ElementoPredefinido.Individual("Gallina", "Pollaio"),
                ElementoPredefinido.Individual("Anatra", "Becco"),
                ElementoPredefinido.Individual("Rospo", "Stagno"),
                ElementoPredefinido.Individual("Rana", "Salto"),
                ElementoPredefinido.Individual("Tartaruga", "Guscio"),
                ElementoPredefinido.Individual("Iguana", "Rettile"),
                ElementoPredefinido.Individual("Lucertola", "Coda"),
                ElementoPredefinido.Individual("Scorpione", "Pungiglione"),
                ElementoPredefinido.Individual("Ragno", "Ragnatela"),
                ElementoPredefinido.Individual("Formica", "Formicaio"),
                ElementoPredefinido.Individual("Cavalletta", "Verde"),
                ElementoPredefinido.Individual("Grillo", "Canto"),
                ElementoPredefinido.Individual("Mosca", "Volo"),
                ElementoPredefinido.Individual("Zanzara", "Puntura"),
                ElementoPredefinido.Individual("Scarafaggio", "Resistenza"),
                ElementoPredefinido.Individual("Granchio", "Chele"),
                ElementoPredefinido.Individual("Aragosta", "Mare"),
                ElementoPredefinido.Individual("Gambero", "Crostaceo"),
                ElementoPredefinido.Individual("Lumaca", "Bava"),
                ElementoPredefinido.Individual("Medusa", "Tentacoli"),
                ElementoPredefinido.Individual("Stella Marina", "Braccia"),
                ElementoPredefinido.Individual("Cavalluccio Marino", "Muso"),
                ElementoPredefinido.Individual("Pesce Spada", "Spada"),
                ElementoPredefinido.Individual("Pesce Pagliaccio", "Anemone"),
                ElementoPredefinido.Individual("Anguilla", "Elettricità")
            )
        ),

        // === 4. CATEGORIA: CIBO ===
        ColeccionPredefinida(
            nombre = "Gastronomia",
            categoria = "Cibo",
            elementos = listOf(
                ElementoPredefinido.Individual("Pizza", "Fetta"),
                ElementoPredefinido.Individual("Sushi", "Wasabi"),
                ElementoPredefinido.Individual("Hamburger", "Cetriolino"),
                ElementoPredefinido.Individual("Paella", "Zafferano"),
                ElementoPredefinido.Individual("Taco", "Piccante"),
                ElementoPredefinido.Individual("Gelato", "Cono"),
                ElementoPredefinido.Individual("Pasta", "Al dente"),
                ElementoPredefinido.Individual("Insalata", "Vinaigrette"),
                ElementoPredefinido.Individual("Cioccolato", "Cacao"),
                ElementoPredefinido.Individual("Zuppa", "Cucchiaio"),
                ElementoPredefinido.Individual("Pane", "Mollica"),
                ElementoPredefinido.Individual("Formaggio", "Fermentazione"),
                ElementoPredefinido.Individual("Uovo", "Tuorlo"),
                ElementoPredefinido.Individual("Mela", "Peccato"),
                ElementoPredefinido.Individual("Patata", "Fritta"),
                ElementoPredefinido.Individual("Bistecca", "Cottura"),
                ElementoPredefinido.Individual("Crocchetta", "Besciamella"),
                ElementoPredefinido.Individual("Yogurt", "Bifidus"),
                ElementoPredefinido.Individual("Caffè", "Caffeina"),
                ElementoPredefinido.Individual("Biscotto", "Gocce"),
                ElementoPredefinido.Individual("Frutti di mare", "Conchiglia"),
                ElementoPredefinido.Individual("Riso", "Chicco"),
                ElementoPredefinido.Individual("Miele", "Dolcezza"),
                ElementoPredefinido.Individual("Ciambella", "Glassa"),
                ElementoPredefinido.Individual("Tramezzino", "Ripieno"),
                ElementoPredefinido.Individual("Torta", "Candela"),
                ElementoPredefinido.Individual("Pesce", "Squame"),
                ElementoPredefinido.Individual("Pollo", "Arrosto"),
                ElementoPredefinido.Individual("Lenticchie", "Ferro"),
                ElementoPredefinido.Individual("Ceci", "Stufato"),
                ElementoPredefinido.Individual("Spaghetti", "Salsa"),
                ElementoPredefinido.Individual("Maccheroni", "Gratin"),
                ElementoPredefinido.Individual("Frittata", "Patate"),
                ElementoPredefinido.Individual("Gazpacho", "Pomodoro"),
                ElementoPredefinido.Individual("Salmorejo", "Pane"),
                ElementoPredefinido.Individual("Costata", "Brace"),
                ElementoPredefinido.Individual("Salmone", "Rosa"),
                ElementoPredefinido.Individual("Tonno", "Scatola"),
                ElementoPredefinido.Individual("Merluzzo", "Salagione"),
                ElementoPredefinido.Individual("Calamari", "Anelli"),
                ElementoPredefinido.Individual("Polpo", "Galiziana"),
                ElementoPredefinido.Individual("Gamberi", "Piastra"),
                ElementoPredefinido.Individual("Polpette", "Carne"),
                ElementoPredefinido.Individual("Lasagne", "Strati"),
                ElementoPredefinido.Individual("Cannelloni", "Pasta"),
                ElementoPredefinido.Individual("Risotto", "Cremoso"),
                ElementoPredefinido.Individual("Couscous", "Semola"),
                ElementoPredefinido.Individual("Hummus", "Cece"),
                ElementoPredefinido.Individual("Guacamole", "Avocado"),
                ElementoPredefinido.Individual("Burrito", "Fagioli"),
                ElementoPredefinido.Individual("Nacho", "Formaggio"),
                ElementoPredefinido.Individual("Kebab", "Carne"),
                ElementoPredefinido.Individual("Curry", "Spezie"),
                ElementoPredefinido.Individual("Ramen", "Brodo"),
                ElementoPredefinido.Individual("Dim Sum", "Vapore"),
                ElementoPredefinido.Individual("Ceviche", "Limone"),
                ElementoPredefinido.Individual("Arepa", "Mais"),
                ElementoPredefinido.Individual("Empanada", "Pasta"),
                ElementoPredefinido.Individual("Quiche", "Uovo"),
                ElementoPredefinido.Individual("Crêpe", "Dolce"),
                ElementoPredefinido.Individual("Waffle", "Quadretti"),
                ElementoPredefinido.Individual("Churros", "Olio"),
                ElementoPredefinido.Individual("Flan", "Caramello"),
                ElementoPredefinido.Individual("Crema pasticcera", "Cannella"),
                ElementoPredefinido.Individual("Riso al latte", "Dessert"),
                ElementoPredefinido.Individual("Brownie", "Cioccolato"),
                ElementoPredefinido.Individual("Muffin", "Dolcetto"),
                ElementoPredefinido.Individual("Croissant", "Burro"),
                ElementoPredefinido.Individual("Baguette", "Francia"),
                ElementoPredefinido.Individual("Pretzel", "Sale"),
                ElementoPredefinido.Individual("Popcorn", "Mais"),
                ElementoPredefinido.Individual("Semi di girasole", "Semi"),
                ElementoPredefinido.Individual("Mandorle", "Frutta secca"),
                ElementoPredefinido.Individual("Noci", "Guscio"),
                ElementoPredefinido.Individual("Olive", "Aperitivo")
            )
        ),

        // === 5. CATEGORIA: PROFESSIONE ===
        ColeccionPredefinida(
            nombre = "Mestieri",
            categoria = "Professione",
            elementos = listOf(
                ElementoPredefinido.Individual("Medico", "Stetoscopio"),
                ElementoPredefinido.Individual("Vigile del fuoco", "Manichetta"),
                ElementoPredefinido.Individual("Professore", "Lavagna"),
                ElementoPredefinido.Individual("Poliziotto", "Manette"),
                ElementoPredefinido.Individual("Cuoco", "Cappello"),
                ElementoPredefinido.Individual("Architetto", "Progetto"),
                ElementoPredefinido.Individual("Astronauta", "Gravità"),
                ElementoPredefinido.Individual("Pittore", "Tela"),
                ElementoPredefinido.Individual("Meccanico", "Dado"),
                ElementoPredefinido.Individual("Avvocato", "Codice"),
                ElementoPredefinido.Individual("Musicista", "Spartito"),
                ElementoPredefinido.Individual("Scienziato", "Microscopio"),
                ElementoPredefinido.Individual("Fotografo", "Flash"),
                ElementoPredefinido.Individual("Dentista", "Carie"),
                ElementoPredefinido.Individual("Pilota", "Cabina"),
                ElementoPredefinido.Individual("Falegname", "Segatura"),
                ElementoPredefinido.Individual("Giudice", "Martelletto"),
                ElementoPredefinido.Individual("Veterinario", "Animali"),
                ElementoPredefinido.Individual("Giornalista", "Intervista"),
                ElementoPredefinido.Individual("Attore", "Copione"),
                ElementoPredefinido.Individual("Contadino", "Raccolto"),
                ElementoPredefinido.Individual("Fornaio", "Lievito"),
                ElementoPredefinido.Individual("Elettricista", "Voltaggio"),
                ElementoPredefinido.Individual("Ballerino", "Palcoscenico"),
                ElementoPredefinido.Individual("Giardiniere", "Potatura"),
                ElementoPredefinido.Individual("Postino", "Cassetta"),
                ElementoPredefinido.Individual("Scrittore", "Romanzo"),
                ElementoPredefinido.Individual("Infermiere", "Iniezione"),
                ElementoPredefinido.Individual("Psicologo", "Terapia"),
                ElementoPredefinido.Individual("Ingegnere", "Calcolo"),
                ElementoPredefinido.Individual("Programmatore", "Codice"),
                ElementoPredefinido.Individual("Designer", "Bozzetto"),
                ElementoPredefinido.Individual("Economista", "Finanza"),
                ElementoPredefinido.Individual("Archeologo", "Fossile"),
                ElementoPredefinido.Individual("Geologo", "Rocce"),
                ElementoPredefinido.Individual("Biologo", "Cellule"),
                ElementoPredefinido.Individual("Chimico", "Reazione"),
                ElementoPredefinido.Individual("Fisico", "Atomo"),
                ElementoPredefinido.Individual("Matematico", "Equazione"),
                ElementoPredefinido.Individual("Filosofo", "Pensiero"),
                ElementoPredefinido.Individual("Storico", "Passato"),
                ElementoPredefinido.Individual("Geografo", "Mappe"),
                ElementoPredefinido.Individual("Politico", "Voti"),
                ElementoPredefinido.Individual("Diplomatico", "Ambasciata"),
                ElementoPredefinido.Individual("Militare", "Uniforme"),
                ElementoPredefinido.Individual("Marinaio", "Oceano"),
                ElementoPredefinido.Individual("Sacerdote", "Tonaca"),
                ElementoPredefinido.Individual("Scultore", "Scalpello"),
                ElementoPredefinido.Individual("Direttore d'orchestra", "Bacchetta"),
                ElementoPredefinido.Individual("Cantante", "Microfono"),
                ElementoPredefinido.Individual("Poeta", "Verso"),
                ElementoPredefinido.Individual("Modello", "Passerella"),
                ElementoPredefinido.Individual("Gioielliere", "Diamante"),
                ElementoPredefinido.Individual("Orologiaio", "Ingranaggio"),
                ElementoPredefinido.Individual("Calzolaio", "Suola"),
                ElementoPredefinido.Individual("Sarto", "Ditale"),
                ElementoPredefinido.Individual("Macellaio", "Coltello"),
                ElementoPredefinido.Individual("Pescivendolo", "Bancone"),
                ElementoPredefinido.Individual("Fruttivendolo", "Bilancia"),
                ElementoPredefinido.Individual("Cameriere", "Vassoio"),
                ElementoPredefinido.Individual("Receptionist", "Telefono"),
                ElementoPredefinido.Individual("Hostess", "Volo"),
                ElementoPredefinido.Individual("Guida", "Turismo"),
                ElementoPredefinido.Individual("Bibliotecario", "Archivio"),
                ElementoPredefinido.Individual("Guardia", "Allarme"),
                ElementoPredefinido.Individual("Muratore", "Mattone"),
                ElementoPredefinido.Individual("Idraulico", "Tubo"),
                ElementoPredefinido.Individual("Imbianchino", "Pennello"),
                ElementoPredefinido.Individual("Fabbro", "Grimaldello"),
                ElementoPredefinido.Individual("Minatore", "Piccone"),
                ElementoPredefinido.Individual("Boscaiolo", "Strumento"),
                ElementoPredefinido.Individual("Pescatore", "Rete"),
                ElementoPredefinido.Individual("Cacciatore", "Fucile"),
                ElementoPredefinido.Individual("Spazzino", "Scopa"),
                ElementoPredefinido.Individual("Tassista", "Volante")
            )
        )
    )
}