package org.example.project.Datos.ListasPredeterminadas


object DatosPredeterminadosJA {
    val listasPredeterminadas = listOf(
        // === 1. CATEGORÍA: OBJETO (日用品 / 物) ===
        ColeccionPredefinida(
            nombre = "日用品",
            categoria = "物",
            elementos = listOf(
                ElementoPredefinido.Individual("鉛筆", "黒鉛"),
                ElementoPredefinido.Individual("鏡", "反射"),
                ElementoPredefinido.Individual("シーツ", "ベッド"),
                ElementoPredefinido.Individual("フォーク", "先端"),
                ElementoPredefinido.Individual("電話", "通信"),
                ElementoPredefinido.Individual("時計", "分"),
                ElementoPredefinido.Individual("鍵", "錠"),
                ElementoPredefinido.Individual("眼鏡", "レンズ"),
                ElementoPredefinido.Individual("電球", "フィラメント"),
                ElementoPredefinido.Individual("机", "板"),
                ElementoPredefinido.Individual("皿", "陶器"),
                ElementoPredefinido.Individual("グラス", "クリスタル"),
                ElementoPredefinido.Individual("ハンマー", "釘"),
                ElementoPredefinido.Individual("バックパック", "荷物"),
                ElementoPredefinido.Individual("傘", "雨"),
                ElementoPredefinido.Individual("カメラ", "レンズ"),
                ElementoPredefinido.Individual("本", "ページ"),
                ElementoPredefinido.Individual("瓶", "液体"),
                ElementoPredefinido.Individual("はさみ", "刃"),
                ElementoPredefinido.Individual("財布", "ポケット"),
                ElementoPredefinido.Individual("椅子", "背もたれ"),
                ElementoPredefinido.Individual("枕", "羽毛"),
                ElementoPredefinido.Individual("扇風機", "羽根"),
                ElementoPredefinido.Individual("電池", "充電"),
                ElementoPredefinido.Individual("ほうき", "床"),
                ElementoPredefinido.Individual("計算機", "数字"),
                ElementoPredefinido.Individual("辞書", "定義"),
                ElementoPredefinido.Individual("くし", "髪"),
                ElementoPredefinido.Individual("スプーン", "スープ"),
                ElementoPredefinido.Individual("タオル", "風呂"),
                ElementoPredefinido.Individual("スーツケース", "旅行"),
                ElementoPredefinido.Individual("ベルト", "ズボン"),
                ElementoPredefinido.Individual("手袋", "手"),
                ElementoPredefinido.Individual("靴下", "足"),
                ElementoPredefinido.Individual("帽子", "頭"),
                ElementoPredefinido.Individual("指輪", "指"),
                ElementoPredefinido.Individual("ネックレス", "首"),
                ElementoPredefinido.Individual("ブレスレット", "手首"),
                ElementoPredefinido.Individual("イヤリング", "耳"),
                ElementoPredefinido.Individual("札入れ", "現金"),
                ElementoPredefinido.Individual("ライター", "炎"),
                ElementoPredefinido.Individual("灰皿", "灰"),
                ElementoPredefinido.Individual("扇子", "風"),
                ElementoPredefinido.Individual("乾電池", "電圧"),
                ElementoPredefinido.Individual("コントローラー", "ボタン"),
                ElementoPredefinido.Individual("キーボード", "文字"),
                ElementoPredefinido.Individual("マウス", "クリック"),
                ElementoPredefinido.Individual("モニター", "画面"),
                ElementoPredefinido.Individual("ヘッドホン", "音"),
                ElementoPredefinido.Individual("マイク", "声"),
                ElementoPredefinido.Individual("スピーカー", "音量"),
                ElementoPredefinido.Individual("充電器", "ケーブル"),
                ElementoPredefinido.Individual("プラグ", "電流"),
                ElementoPredefinido.Individual("照明", "明るい"),
                ElementoPredefinido.Individual("ろうそく", "蝋"),
                ElementoPredefinido.Individual("じゅうたん", "床"),
                ElementoPredefinido.Individual("カーテン", "窓"),
                ElementoPredefinido.Individual("絵画", "壁"),
                ElementoPredefinido.Individual("花瓶", "装飾"),
                ElementoPredefinido.Individual("かご", "籐"),
                ElementoPredefinido.Individual("箱", "段ボール"),
                ElementoPredefinido.Individual("袋", "プラスチック"),
                ElementoPredefinido.Individual("ゴミ箱", "廃棄物"),
                ElementoPredefinido.Individual("ホッチキス", "オフィス"),
                ElementoPredefinido.Individual("クリップ", "固定"),
                ElementoPredefinido.Individual("フォルダ", "書類"),
                ElementoPredefinido.Individual("封筒", "手紙"),
                ElementoPredefinido.Individual("切手", "郵便"),
                ElementoPredefinido.Individual("接着剤", "粘着"),
                ElementoPredefinido.Individual("テープ", "粘着テープ"),
                ElementoPredefinido.Individual("消しゴム", "消す"),
                ElementoPredefinido.Individual("鉛筆削り", "刃"),
                ElementoPredefinido.Individual("定規", "測定"),
                ElementoPredefinido.Individual("コンパス", "円"),
                ElementoPredefinido.Individual("筆", "油彩")
            )
        ),

        // === 2. CATEGORÍA: LUGAR (場所) ===
        ColeccionPredefinida(
            nombre = "場所",
            categoria = "場所",
            elementos = listOf(
                ElementoPredefinido.Individual("図書館", "本棚"),
                ElementoPredefinido.Individual("森", "植物"),
                ElementoPredefinido.Individual("映画館", "座席"),
                ElementoPredefinido.Individual("砂漠", "干ばつ"),
                ElementoPredefinido.Individual("駅", "ホーム"),
                ElementoPredefinido.Individual("病院", "患者"),
                ElementoPredefinido.Individual("博物館", "展示"),
                ElementoPredefinido.Individual("ビーチ", "波"),
                ElementoPredefinido.Individual("公園", "ブランコ"),
                ElementoPredefinido.Individual("川", "川底"),
                ElementoPredefinido.Individual("劇場", "幕"),
                ElementoPredefinido.Individual("動物園", "檻"),
                ElementoPredefinido.Individual("空港", "ターミナル"),
                ElementoPredefinido.Individual("ジム", "重り"),
                ElementoPredefinido.Individual("山", "頂上"),
                ElementoPredefinido.Individual("スーパー", "通路"),
                ElementoPredefinido.Individual("教会", "祭壇"),
                ElementoPredefinido.Individual("城", "城壁"),
                ElementoPredefinido.Individual("スタジアム", "観客席"),
                ElementoPredefinido.Individual("農場", "囲い"),
                ElementoPredefinido.Individual("火山", "マグマ"),
                ElementoPredefinido.Individual("島", "群島"),
                ElementoPredefinido.Individual("港", "埠頭"),
                ElementoPredefinido.Individual("レストラン", "メニュー"),
                ElementoPredefinido.Individual("銀行", "ATM"),
                ElementoPredefinido.Individual("刑務所", "独房"),
                ElementoPredefinido.Individual("学校", "教室"),
                ElementoPredefinido.Individual("大学", "学部"),
                ElementoPredefinido.Individual("工場", "生産"),
                ElementoPredefinido.Individual("作業場", "工具"),
                ElementoPredefinido.Individual("オフィス", "机"),
                ElementoPredefinido.Individual("薬局", "薬"),
                ElementoPredefinido.Individual("パン屋", "オーブン"),
                ElementoPredefinido.Individual("美容院", "鏡"),
                ElementoPredefinido.Individual("ガソリンスタンド", "燃料"),
                ElementoPredefinido.Individual("ホテル", "受付"),
                ElementoPredefinido.Individual("キャンプ場", "テント"),
                ElementoPredefinido.Individual("船着き場", "ボート"),
                ElementoPredefinido.Individual("市場", "屋台"),
                ElementoPredefinido.Individual("宮殿", "王族"),
                ElementoPredefinido.Individual("大聖堂", "ゴシック"),
                ElementoPredefinido.Individual("墓地", "墓"),
                ElementoPredefinido.Individual("庭", "花"),
                ElementoPredefinido.Individual("テラス", "景色"),
                ElementoPredefinido.Individual("地下室", "暗闇"),
                ElementoPredefinido.Individual("屋根裏部屋", "屋根"),
                ElementoPredefinido.Individual("ガレージ", "車"),
                ElementoPredefinido.Individual("キッチン", "コンロ"),
                ElementoPredefinido.Individual("バスルーム", "シャワー"),
                ElementoPredefinido.Individual("寝室", "休息"),
                ElementoPredefinido.Individual("リビング", "ソファ"),
                ElementoPredefinido.Individual("廊下", "ドア"),
                ElementoPredefinido.Individual("バルコニー", "手すり"),
                ElementoPredefinido.Individual("プール", "塩素"),
                ElementoPredefinido.Individual("広場", "噴水"),
                ElementoPredefinido.Individual("通り", "アスファルト"),
                ElementoPredefinido.Individual("大通り", "交通"),
                ElementoPredefinido.Individual("橋", "川"),
                ElementoPredefinido.Individual("トンネル", "地下"),
                ElementoPredefinido.Individual("灯台", "海岸"),
                ElementoPredefinido.Individual("崖", "高さ"),
                ElementoPredefinido.Individual("洞窟", "鍾乳石"),
                ElementoPredefinido.Individual("ジャングル", "熱帯"),
                ElementoPredefinido.Individual("サバンナ", "平原"),
                ElementoPredefinido.Individual("沼", "泥"),
                ElementoPredefinido.Individual("氷河", "氷"),
                ElementoPredefinido.Individual("滝", "落下"),
                ElementoPredefinido.Individual("谷", "山々"),
                ElementoPredefinido.Individual("草原", "牧草"),
                ElementoPredefinido.Individual("荒野", "砂丘"),
                ElementoPredefinido.Individual("マリーナ", "錨"),
                ElementoPredefinido.Individual("鉄道駅", "線路"),
                ElementoPredefinido.Individual("飛行場", "滑走路"),
                ElementoPredefinido.Individual("天文台", "星"),
                ElementoPredefinido.Individual("研究所", "試験管")
            )
        ),

        // === 3. CATEGORÍA: ANIMAL (動物) ===
        ColeccionPredefinida(
            nombre = "動物",
            categoria = "動物",
            elementos = listOf(
                ElementoPredefinido.Individual("ライオン", "たてがみ"),
                ElementoPredefinido.Individual("象", "鼻"),
                ElementoPredefinido.Individual("キリン", "首"),
                ElementoPredefinido.Individual("トラ", "縞模様"),
                ElementoPredefinido.Individual("ホッキョクグマ", "北極"),
                ElementoPredefinido.Individual("パンダ", "竹"),
                ElementoPredefinido.Individual("イルカ", "知能"),
                ElementoPredefinido.Individual("クジラ", "潮吹き"),
                ElementoPredefinido.Individual("ワシ", "爪"),
                ElementoPredefinido.Individual("カンガルー", "袋"),
                ElementoPredefinido.Individual("ペンギン", "タキシード"),
                ElementoPredefinido.Individual("コアラ", "ユーカリ"),
                ElementoPredefinido.Individual("ヘビ", "毒"),
                ElementoPredefinido.Individual("タコ", "墨"),
                ElementoPredefinido.Individual("オオカミ", "遠吠え"),
                ElementoPredefinido.Individual("馬", "ひづめ"),
                ElementoPredefinido.Individual("サル", "霊長類"),
                ElementoPredefinido.Individual("サメ", "ヒレ"),
                ElementoPredefinido.Individual("ミツバチ", "巣"),
                ElementoPredefinido.Individual("カメレオン", "擬態"),
                ElementoPredefinido.Individual("フクロウ", "知恵"),
                ElementoPredefinido.Individual("牛", "牛乳"),
                ElementoPredefinido.Individual("ワニ", "顎"),
                ElementoPredefinido.Individual("チョウ", "変態"),
                ElementoPredefinido.Individual("コウモリ", "ソナー"),
                ElementoPredefinido.Individual("犬", "忠誠心"),
                ElementoPredefinido.Individual("猫", "喉を鳴らす"),
                ElementoPredefinido.Individual("ウサギ", "ニンジン"),
                ElementoPredefinido.Individual("ネズミ", "チーズ"),
                ElementoPredefinido.Individual("シマウマ", "白黒"),
                ElementoPredefinido.Individual("カバ", "川"),
                ElementoPredefinido.Individual("サイ", "角"),
                ElementoPredefinido.Individual("チーター", "速度"),
                ElementoPredefinido.Individual("ハイエナ", "笑い"),
                ElementoPredefinido.Individual("キツネ", "狡猾"),
                ElementoPredefinido.Individual("クマ", "冬眠"),
                ElementoPredefinido.Individual("シカ", "枝角"),
                ElementoPredefinido.Individual("リス", "ナッツ"),
                ElementoPredefinido.Individual("ビーバー", "ダム"),
                ElementoPredefinido.Individual("カワウソ", "水"),
                ElementoPredefinido.Individual("アザラシ", "南極"),
                ElementoPredefinido.Individual("セイウチ", "牙"),
                ElementoPredefinido.Individual("ペリカン", "くちばし"),
                ElementoPredefinido.Individual("フラミンゴ", "ピンク"),
                ElementoPredefinido.Individual("オウム", "言葉"),
                ElementoPredefinido.Individual("クジャク", "羽"),
                ElementoPredefinido.Individual("ダチョウ", "卵"),
                ElementoPredefinido.Individual("ハクチョウ", "湖"),
                ElementoPredefinido.Individual("カラス", "黒"),
                ElementoPredefinido.Individual("オンドリ", "夜明け"),
                ElementoPredefinido.Individual("メンドリ", "鶏舎"),
                ElementoPredefinido.Individual("アヒル", "くちばし"),
                ElementoPredefinido.Individual("ヒキガエル", "池"),
                ElementoPredefinido.Individual("カエル", "ジャンプ"),
                ElementoPredefinido.Individual("カメ", "甲羅"),
                ElementoPredefinido.Individual("イグアナ", "爬虫類"),
                ElementoPredefinido.Individual("トカゲ", "尻尾"),
                ElementoPredefinido.Individual("サソリ", "毒針"),
                ElementoPredefinido.Individual("クモ", "クモの巣"),
                ElementoPredefinido.Individual("アリ", "蟻塚"),
                ElementoPredefinido.Individual("バッタ", "緑"),
                ElementoPredefinido.Individual("コオロギ", "鳴き声"),
                ElementoPredefinido.Individual("ハエ", "飛行"),
                ElementoPredefinido.Individual("蚊", "刺す"),
                ElementoPredefinido.Individual("ゴキブリ", "抵抗力"),
                ElementoPredefinido.Individual("カニ", "はさみ"),
                ElementoPredefinido.Individual("ロブスター", "海"),
                ElementoPredefinido.Individual("エビ", "甲殻類"),
                ElementoPredefinido.Individual("カタツムリ", "粘液"),
                ElementoPredefinido.Individual("クラゲ", "触手"),
                ElementoPredefinido.Individual("ヒトデ", "腕"),
                ElementoPredefinido.Individual("タツノオトシゴ", "鼻づら"),
                ElementoPredefinido.Individual("メカジキ", "剣"),
                ElementoPredefinido.Individual("クマノミ", "イソギンチャク"),
                ElementoPredefinido.Individual("ウナギ", "電気")
            )
        ),

        // === 4. CATEGORÍA: COMIDA (食べ物) ===
        ColeccionPredefinida(
            nombre = "ガストロノミー",
            categoria = "食べ物",
            elementos = listOf(
                ElementoPredefinido.Individual("ピザ", "一切れ"),
                ElementoPredefinido.Individual("寿司", "わさび"),
                ElementoPredefinido.Individual("ハンバーガー", "ピクルス"),
                ElementoPredefinido.Individual("パエリア", "サフラン"),
                ElementoPredefinido.Individual("タコス", "辛い"),
                ElementoPredefinido.Individual("アイスクリーム", "コーン"),
                ElementoPredefinido.Individual("パスタ", "アルデンテ"),
                ElementoPredefinido.Individual("サラダ", "ビネグレット"),
                ElementoPredefinido.Individual("チョコレート", "カカオ"),
                ElementoPredefinido.Individual("スープ", "スプーン"),
                ElementoPredefinido.Individual("パン", "パン粉"),
                ElementoPredefinido.Individual("チーズ", "発酵"),
                ElementoPredefinido.Individual("卵", "黄身"),
                ElementoPredefinido.Individual("リンゴ", "罪"),
                ElementoPredefinido.Individual("ジャガイモ", "フライド"),
                ElementoPredefinido.Individual("ステーキ", "レア"),
                ElementoPredefinido.Individual("コロッケ", "ベシャメル"),
                ElementoPredefinido.Individual("ヨーグルト", "ビフィズス菌"),
                ElementoPredefinido.Individual("コーヒー", "カフェイン"),
                ElementoPredefinido.Individual("クッキー", "チョコチップ"),
                ElementoPredefinido.Individual("シーフード", "貝殻"),
                ElementoPredefinido.Individual("お米", "穀物"),
                ElementoPredefinido.Individual("ハチミツ", "甘さ"),
                ElementoPredefinido.Individual("ドーナツ", "グレーズ"),
                ElementoPredefinido.Individual("サンドイッチ", "具"),
                ElementoPredefinido.Individual("ケーキ", "ろうそく"),
                ElementoPredefinido.Individual("魚", "鱗"),
                ElementoPredefinido.Individual("鶏肉", "ロースト"),
                ElementoPredefinido.Individual("レンズ豆", "鉄分"),
                ElementoPredefinido.Individual("ひよこ豆", "シチュー"),
                ElementoPredefinido.Individual("スパゲッティ", "ソース"),
                ElementoPredefinido.Individual("マカロニ", "グラタン"),
                ElementoPredefinido.Individual("オムレツ", "ジャガイモ"),
                ElementoPredefinido.Individual("ガスパチョ", "トマト"),
                ElementoPredefinido.Individual("サルモレホ", "パン"),
                ElementoPredefinido.Individual("リブアイ", "炭火"),
                ElementoPredefinido.Individual("サケ", "ピンク"),
                ElementoPredefinido.Individual("ツナ", "缶詰"),
                ElementoPredefinido.Individual("タラ", "塩漬け"),
                ElementoPredefinido.Individual("イカ", "リング"),
                ElementoPredefinido.Individual("タコ", "ガリシア風"),
                ElementoPredefinido.Individual("エビ", "鉄板焼き"),
                ElementoPredefinido.Individual("ミートボール", "肉"),
                ElementoPredefinido.Individual("ラザニア", "層"),
                ElementoPredefinido.Individual("カネロニ", "パスタ"),
                ElementoPredefinido.Individual("リゾット", "クリーミー"),
                ElementoPredefinido.Individual("クスクス", "セモリナ"),
                ElementoPredefinido.Individual("フムス", "ひよこ豆"),
                ElementoPredefinido.Individual("ワカモレ", "アボカド"),
                ElementoPredefinido.Individual("ブリトー", "豆"),
                ElementoPredefinido.Individual("ナチョス", "チーズ"),
                ElementoPredefinido.Individual("ケバブ", "肉"),
                ElementoPredefinido.Individual("カレー", "スパイス"),
                ElementoPredefinido.Individual("ラーメン", "スープ"),
                ElementoPredefinido.Individual("飲茶", "蒸気"),
                ElementoPredefinido.Individual("セビーチェ", "レモン"),
                ElementoPredefinido.Individual("アレパ", "トウモロコシ"),
                ElementoPredefinido.Individual("エンパナーダ", "生地"),
                ElementoPredefinido.Individual("キッシュ", "卵"),
                ElementoPredefinido.Individual("クレープ", "甘い"),
                ElementoPredefinido.Individual("ワッフル", "四角"),
                ElementoPredefinido.Individual("チュロス", "油"),
                ElementoPredefinido.Individual("プリン", "カラメル"),
                ElementoPredefinido.Individual("カスタード", "シナモン"),
                ElementoPredefinido.Individual("ライスプディング", "デザート"),
                ElementoPredefinido.Individual("ブラウニー", "チョコレート"),
                ElementoPredefinido.Individual("マフィン", "カップケーキ"),
                ElementoPredefinido.Individual("クロワッサン", "バター"),
                ElementoPredefinido.Individual("バゲット", "フランス"),
                ElementoPredefinido.Individual("プレッツェル", "塩"),
                ElementoPredefinido.Individual("ポップコーン", "トウモロコシ"),
                ElementoPredefinido.Individual("ひまわりの種", "種"),
                ElementoPredefinido.Individual("アーモンド", "ナッツ"),
                ElementoPredefinido.Individual("クルミ", "殻"),
                ElementoPredefinido.Individual("オリーブ", "前菜")
            )
        ),

        // === 5. CATEGORÍA: PROFESIÓN (職業) ===
        ColeccionPredefinida(
            nombre = "職業",
            categoria = "職業",
            elementos = listOf(
                ElementoPredefinido.Individual("医者", "聴診器"),
                ElementoPredefinido.Individual("消防士", "ホース"),
                ElementoPredefinido.Individual("教師", "黒板"),
                ElementoPredefinido.Individual("警察官", "手錠"),
                ElementoPredefinido.Individual("シェフ", "帽子"),
                ElementoPredefinido.Individual("建築家", "図面"),
                ElementoPredefinido.Individual("宇宙飛行士", "重力"),
                ElementoPredefinido.Individual("画家", "キャンバス"),
                ElementoPredefinido.Individual("整備士", "ナット"),
                ElementoPredefinido.Individual("弁護士", "法律"),
                ElementoPredefinido.Individual("音楽家", "楽譜"),
                ElementoPredefinido.Individual("科学者", "顕微鏡"),
                ElementoPredefinido.Individual("写真家", "フラッシュ"),
                ElementoPredefinido.Individual("歯科医", "虫歯"),
                ElementoPredefinido.Individual("パイロット", "操縦室"),
                ElementoPredefinido.Individual("大工", "おがくず"),
                ElementoPredefinido.Individual("裁判官", "木槌"),
                ElementoPredefinido.Individual("獣医", "ペット"),
                ElementoPredefinido.Individual("ジャーナリスト", "インタビュー"),
                ElementoPredefinido.Individual("俳優", "台本"),
                ElementoPredefinido.Individual("農家", "収穫"),
                ElementoPredefinido.Individual("パン職人", "酵母"),
                ElementoPredefinido.Individual("電気技師", "電圧"),
                ElementoPredefinido.Individual("ダンサー", "舞台"),
                ElementoPredefinido.Individual("庭師", "剪定"),
                ElementoPredefinido.Individual("郵便配達員", "郵便受け"),
                ElementoPredefinido.Individual("作家", "小説"),
                ElementoPredefinido.Individual("看護師", "注射"),
                ElementoPredefinido.Individual("心理学者", "セラピー"),
                ElementoPredefinido.Individual("エンジニア", "計算"),
                ElementoPredefinido.Individual("プログラマー", "コード"),
                ElementoPredefinido.Individual("デザイナー", "スケッチ"),
                ElementoPredefinido.Individual("経済学者", "金融"),
                ElementoPredefinido.Individual("考古学者", "化石"),
                ElementoPredefinido.Individual("地質学者", "岩石"),
                ElementoPredefinido.Individual("生物学者", "細胞"),
                ElementoPredefinido.Individual("化学者", "反応"),
                ElementoPredefinido.Individual("物理学者", "原子"),
                ElementoPredefinido.Individual("数学者", "方程式"),
                ElementoPredefinido.Individual("哲学者", "思考"),
                ElementoPredefinido.Individual("歴史家", "過去"),
                ElementoPredefinido.Individual("地理学者", "地図"),
                ElementoPredefinido.Individual("政治家", "票"),
                ElementoPredefinido.Individual("外交官", "大使館"),
                ElementoPredefinido.Individual("軍人", "制服"),
                ElementoPredefinido.Individual("船乗り", "海"),
                ElementoPredefinido.Individual("神父", "スータン"),
                ElementoPredefinido.Individual("彫刻家", "ノミ"),
                ElementoPredefinido.Individual("指揮者", "タクト"),
                ElementoPredefinido.Individual("歌手", "マイク"),
                ElementoPredefinido.Individual("詩人", "詩"),
                ElementoPredefinido.Individual("モデル", "ランウェイ"),
                ElementoPredefinido.Individual("宝石商", "ダイヤモンド"),
                ElementoPredefinido.Individual("時計職人", "歯車"),
                ElementoPredefinido.Individual("靴職人", "靴底"),
                ElementoPredefinido.Individual("仕立て屋", "指ぬき"),
                ElementoPredefinido.Individual("精肉店", "ナイフ"),
                ElementoPredefinido.Individual("鮮魚店", "カウンター"),
                ElementoPredefinido.Individual("青果店", "はかり"),
                ElementoPredefinido.Individual("ウェイター", "トレイ"),
                ElementoPredefinido.Individual("受付係", "電話"),
                ElementoPredefinido.Individual("客室乗務員", "フライト"),
                ElementoPredefinido.Individual("ガイド", "観光"),
                ElementoPredefinido.Individual("司書", "アーカイブ"),
                ElementoPredefinido.Individual("警備員", "アラーム"),
                ElementoPredefinido.Individual("左官", "レンガ"),
                ElementoPredefinido.Individual("配管工", "パイプ"),
                ElementoPredefinido.Individual("塗装工", "刷毛"),
                ElementoPredefinido.Individual("鍵屋", "ピッキングツール"),
                ElementoPredefinido.Individual("鉱夫", "つるはし"),
                ElementoPredefinido.Individual("木こり", "道具"),
                ElementoPredefinido.Individual("漁師", "網"),
                ElementoPredefinido.Individual("猟師", "ライフル"),
                ElementoPredefinido.Individual("清掃員", "ほうき"),
                ElementoPredefinido.Individual("タクシー運転手", "ハンドル")
            )
        )
    )
}