import kotlinx.serialization.Serializable

// --- MODELO COMPATIBLE PARA GUARDAR ---
// (Ya no usamos mutableStateOf aquí porque son datos estáticos de lectura)
@Serializable
data class ColeccionPredefinida(
    val nombre: String,
    val categoria: String,
    val elementos: List<ElementoPredefinido>
)

@Serializable
sealed class ElementoPredefinido {
    @Serializable
    data class Individual(val palabra: String, val pista: String) : ElementoPredefinido()

    @Serializable
    data class Conjunto(val nombreConjunto: String, val palabras: List<Individual>) : ElementoPredefinido()
}

// --- EL GRAN DICCIONARIO PREDETERMINADO ---
// He generado 12 palabras por categoría para demostrar la estructura.
// (El usuario puede añadir más hasta llegar a 50 si lo desea siguiendo este patrón).
object DatosPredeterminados {
    val listasPredeterminadas = listOf(
        // === 1. CATEGORÍA: OBJETO (75 ELEMENTOS) ===
        ColeccionPredefinida(
            nombre = "Objetos Cotidianos",
            categoria = "Objeto",
            elementos = listOf(
                ElementoPredefinido.Individual("Lápiz", "Grafito"),
                ElementoPredefinido.Individual("Espejo", "Reflejo"),
                ElementoPredefinido.Individual("Sábana", "Cama"),
                ElementoPredefinido.Individual("Tenedor", "Puntas"),
                ElementoPredefinido.Individual("Teléfono", "Comunicación"),
                ElementoPredefinido.Individual("Reloj", "Minutos"),
                ElementoPredefinido.Individual("Llave", "Cerradura"),
                ElementoPredefinido.Individual("Gafas", "Lentes"),
                ElementoPredefinido.Individual("Bombilla", "Filamento"),
                ElementoPredefinido.Individual("Mesa", "Tablero"),
                ElementoPredefinido.Individual("Plato", "Cerámica"),
                ElementoPredefinido.Individual("Vaso", "Cristal"),
                ElementoPredefinido.Individual("Martillo", "Clavo"),
                ElementoPredefinido.Individual("Mochila", "Carga"),
                ElementoPredefinido.Individual("Paraguas", "Lluvia"),
                ElementoPredefinido.Individual("Cámara", "Lente"),
                ElementoPredefinido.Individual("Libro", "Páginas"),
                ElementoPredefinido.Individual("Botella", "Líquido"),
                ElementoPredefinido.Individual("Tijeras", "Filo"),
                ElementoPredefinido.Individual("Cartera", "Bolsillo"),
                ElementoPredefinido.Individual("Silla", "Respaldo"),
                ElementoPredefinido.Individual("Almohada", "Plumas"),
                ElementoPredefinido.Individual("Ventilador", "Aspas"),
                ElementoPredefinido.Individual("Batería", "Carga"),
                ElementoPredefinido.Individual("Escoba", "Suelo"),
                ElementoPredefinido.Individual("Calculadora", "Números"),
                ElementoPredefinido.Individual("Diccionario", "Definiciones"),
                ElementoPredefinido.Individual("Peine", "Cabello"),
                ElementoPredefinido.Individual("Cuchara", "Sopa"),
                ElementoPredefinido.Individual("Toalla", "Baño"),
                ElementoPredefinido.Individual("Maleta", "Viaje"),
                ElementoPredefinido.Individual("Cinturón", "Pantalón"),
                ElementoPredefinido.Individual("Guante", "Mano"),
                ElementoPredefinido.Individual("Calcetín", "Pie"),
                ElementoPredefinido.Individual("Gorra", "Cabeza"),
                ElementoPredefinido.Individual("Anillo", "Dedo"),
                ElementoPredefinido.Individual("Collar", "Cuello"),
                ElementoPredefinido.Individual("Pulsera", "Muñeca"),
                ElementoPredefinido.Individual("Pendiente", "Oreja"),
                ElementoPredefinido.Individual("Billetera", "Efectivo"),
                ElementoPredefinido.Individual("Encendedor", "Llama"),
                ElementoPredefinido.Individual("Cenicero", "Ceniza"),
                ElementoPredefinido.Individual("Abanico", "Viento"),
                ElementoPredefinido.Individual("Pila", "Voltaje"),
                ElementoPredefinido.Individual("Mando", "Botones"),
                ElementoPredefinido.Individual("Teclado", "Letras"),
                ElementoPredefinido.Individual("Ratón", "Click"),
                ElementoPredefinido.Individual("Monitor", "Pantalla"),
                ElementoPredefinido.Individual("Auriculares", "Sonido"),
                ElementoPredefinido.Individual("Micrófono", "Voz"),
                ElementoPredefinido.Individual("Altavoz", "Volumen"),
                ElementoPredefinido.Individual("Cargador", "Cable"),
                ElementoPredefinido.Individual("Enchufe", "Corriente"),
                ElementoPredefinido.Individual("Bombilla", "Iluminación"),
                ElementoPredefinido.Individual("Vela", "Cera"),
                ElementoPredefinido.Individual("Alfombra", "Piso"),
                ElementoPredefinido.Individual("Cortina", "Ventana"),
                ElementoPredefinido.Individual("Cuadro", "Pared"),
                ElementoPredefinido.Individual("Florero", "Decoración"),
                ElementoPredefinido.Individual("Cesta", "Mimbre"),
                ElementoPredefinido.Individual("Caja", "Cartón"),
                ElementoPredefinido.Individual("Bolsa", "Plástico"),
                ElementoPredefinido.Individual("Papelera", "Residuos"),
                ElementoPredefinido.Individual("Grapadora", "Oficina"),
                ElementoPredefinido.Individual("Clip", "Sujeción"),
                ElementoPredefinido.Individual("Carpeta", "Documentos"),
                ElementoPredefinido.Individual("Sobre", "Carta"),
                ElementoPredefinido.Individual("Sello", "Correo"),
                ElementoPredefinido.Individual("Pegamento", "Adhesivo"),
                ElementoPredefinido.Individual("Celo", "Cinta"),
                ElementoPredefinido.Individual("Goma", "Borrar"),
                ElementoPredefinido.Individual("Sacapuntas", "Punta"),
                ElementoPredefinido.Individual("Regla", "Medida"),
                ElementoPredefinido.Individual("Compás", "Círculo"),
                ElementoPredefinido.Individual("Pincel", "Óleo")
            )
        ),

        // === 2. CATEGORÍA: LUGAR (75 ELEMENTOS) ===
        ColeccionPredefinida(
            nombre = "Lugares",
            categoria = "Lugar",
            elementos = listOf(
                ElementoPredefinido.Individual("Biblioteca", "Estantería"),
                ElementoPredefinido.Individual("Bosque", "Vegetación"),
                ElementoPredefinido.Individual("Cine", "Butacas"),
                ElementoPredefinido.Individual("Desierto", "Sequía"),
                ElementoPredefinido.Individual("Estación", "Andén"),
                ElementoPredefinido.Individual("Hospital", "Pacientes"),
                ElementoPredefinido.Individual("Museo", "Exposición"),
                ElementoPredefinido.Individual("Playa", "Oleaje"),
                ElementoPredefinido.Individual("Parque", "Columpios"),
                ElementoPredefinido.Individual("Río", "Cauce"),
                ElementoPredefinido.Individual("Teatro", "Telón"),
                ElementoPredefinido.Individual("Zoológico", "Jaulas"),
                ElementoPredefinido.Individual("Aeropuerto", "Terminal"),
                ElementoPredefinido.Individual("Gimnasio", "Pesas"),
                ElementoPredefinido.Individual("Montaña", "Cima"),
                ElementoPredefinido.Individual("Supermercado", "Pasillos"),
                ElementoPredefinido.Individual("Iglesia", "Altar"),
                ElementoPredefinido.Individual("Castillo", "Muralla"),
                ElementoPredefinido.Individual("Estadio", "Gradas"),
                ElementoPredefinido.Individual("Granja", "Corral"),
                ElementoPredefinido.Individual("Volcán", "Magma"),
                ElementoPredefinido.Individual("Isla", "Archipiélago"),
                ElementoPredefinido.Individual("Puerto", "Muelle"),
                ElementoPredefinido.Individual("Restaurante", "Menú"),
                ElementoPredefinido.Individual("Banco", "Cajero"),
                ElementoPredefinido.Individual("Cárcel", "Celdas"),
                ElementoPredefinido.Individual("Escuela", "Aulas"),
                ElementoPredefinido.Individual("Universidad", "Facultad"),
                ElementoPredefinido.Individual("Fábrica", "Producción"),
                ElementoPredefinido.Individual("Taller", "Herramientas"),
                ElementoPredefinido.Individual("Oficina", "Escritorios"),
                ElementoPredefinido.Individual("Farmacia", "Medicamentos"),
                ElementoPredefinido.Individual("Panadería", "Horno"),
                ElementoPredefinido.Individual("Peluquería", "Espejos"),
                ElementoPredefinido.Individual("Gasolinera", "Combustible"),
                ElementoPredefinido.Individual("Hotel", "Recepción"),
                ElementoPredefinido.Individual("Camping", "Tiendas"),
                ElementoPredefinido.Individual("Puerto", "Embarcaciones"),
                ElementoPredefinido.Individual("Mercado", "Puestos"),
                ElementoPredefinido.Individual("Palacio", "Realeza"),
                ElementoPredefinido.Individual("Catedral", "Gótico"),
                ElementoPredefinido.Individual("Cementerio", "Tumbas"),
                ElementoPredefinido.Individual("Jardín", "Flores"),
                ElementoPredefinido.Individual("Terraza", "Vistas"),
                ElementoPredefinido.Individual("Sótano", "Oscuridad"),
                ElementoPredefinido.Individual("Ático", "Techo"),
                ElementoPredefinido.Individual("Garaje", "Coche"),
                ElementoPredefinido.Individual("Cocina", "Fogones"),
                ElementoPredefinido.Individual("Baño", "Ducha"),
                ElementoPredefinido.Individual("Dormitorio", "Descanso"),
                ElementoPredefinido.Individual("Salón", "Sofá"),
                ElementoPredefinido.Individual("Pasillo", "Puertas"),
                ElementoPredefinido.Individual("Balcón", "Barandilla"),
                ElementoPredefinido.Individual("Piscina", "Cloro"),
                ElementoPredefinido.Individual("Plaza", "Fuente"),
                ElementoPredefinido.Individual("Calle", "Asfalto"),
                ElementoPredefinido.Individual("Avenida", "Tráfico"),
                ElementoPredefinido.Individual("Puente", "Río"),
                ElementoPredefinido.Individual("Túnel", "Subterráneo"),
                ElementoPredefinido.Individual("Faro", "Costa"),
                ElementoPredefinido.Individual("Acantilado", "Altura"),
                ElementoPredefinido.Individual("Cueva", "Estalactitas"),
                ElementoPredefinido.Individual("Selva", "Tropical"),
                ElementoPredefinido.Individual("Sabana", "Llanura"),
                ElementoPredefinido.Individual("Pantano", "Lodo"),
                ElementoPredefinido.Individual("Glaciar", "Hielo"),
                ElementoPredefinido.Individual("Cascada", "Salto"),
                ElementoPredefinido.Individual("Valle", "Montañas"),
                ElementoPredefinido.Individual("Pradera", "Pasto"),
                ElementoPredefinido.Individual("Desierto", "Dunas"),
                ElementoPredefinido.Individual("Puerto", "Anclas"),
                ElementoPredefinido.Individual("Estación", "Vías"),
                ElementoPredefinido.Individual("Aeropuerto", "Pista"),
                ElementoPredefinido.Individual("Observatorio", "Estrellas"),
                ElementoPredefinido.Individual("Laboratorio", "Tubos")
            )
        ),

        // === 3. CATEGORÍA: ANIMAL (75 ELEMENTOS) ===
        ColeccionPredefinida(
            nombre = "Animales",
            categoria = "Animal",
            elementos = listOf(
                ElementoPredefinido.Individual("León", "Melena"),
                ElementoPredefinido.Individual("Elefante", "Trompa"),
                ElementoPredefinido.Individual("Jirafa", "Cuello"),
                ElementoPredefinido.Individual("Tigre", "Rayas"),
                ElementoPredefinido.Individual("Oso Polar", "Ártico"),
                ElementoPredefinido.Individual("Panda", "Bambú"),
                ElementoPredefinido.Individual("Delfín", "Inteligencia"),
                ElementoPredefinido.Individual("Ballena", "Soplido"),
                ElementoPredefinido.Individual("Águila", "Garras"),
                ElementoPredefinido.Individual("Canguro", "Bolsa"),
                ElementoPredefinido.Individual("Pingüino", "Frac"),
                ElementoPredefinido.Individual("Koala", "Eucalipto"),
                ElementoPredefinido.Individual("Serpiente", "Veneno"),
                ElementoPredefinido.Individual("Pulpo", "Tinta"),
                ElementoPredefinido.Individual("Lobo", "Aullido"),
                ElementoPredefinido.Individual("Caballo", "Cascos"),
                ElementoPredefinido.Individual("Mono", "Primate"),
                ElementoPredefinido.Individual("Tiburón", "Aleta"),
                ElementoPredefinido.Individual("Abeja", "Colmena"),
                ElementoPredefinido.Individual("Camaleón", "Camuflaje"),
                ElementoPredefinido.Individual("Búho", "Sabiduría"),
                ElementoPredefinido.Individual("Vaca", "Leche"),
                ElementoPredefinido.Individual("Cocodrilo", "Mandíbula"),
                ElementoPredefinido.Individual("Mariposa", "Metamorfosis"),
                ElementoPredefinido.Individual("Murciélago", "Sonar"),
                ElementoPredefinido.Individual("Perro", "Lealtad"),
                ElementoPredefinido.Individual("Gato", "Ronroneo"),
                ElementoPredefinido.Individual("Conejo", "Zanahoria"),
                ElementoPredefinido.Individual("Ratón", "Queso"),
                ElementoPredefinido.Individual("Cebra", "Blanquinegro"),
                ElementoPredefinido.Individual("Hipopótamo", "Río"),
                ElementoPredefinido.Individual("Rinoceronte", "Cuerno"),
                ElementoPredefinido.Individual("Guepardo", "Velocidad"),
                ElementoPredefinido.Individual("Hiena", "Risa"),
                ElementoPredefinido.Individual("Zorro", "Astucia"),
                ElementoPredefinido.Individual("Oso", "Hibernación"),
                ElementoPredefinido.Individual("Ciervo", "Cornamenta"),
                ElementoPredefinido.Individual("Ardilla", "Nueces"),
                ElementoPredefinido.Individual("Castor", "Presa"),
                ElementoPredefinido.Individual("Nutria", "Agua"),
                ElementoPredefinido.Individual("Foca", "Antártida"),
                ElementoPredefinido.Individual("Morsa", "Colmillos"),
                ElementoPredefinido.Individual("Pelícano", "Pico"),
                ElementoPredefinido.Individual("Flamenco", "Rosa"),
                ElementoPredefinido.Individual("Loro", "Habla"),
                ElementoPredefinido.Individual("Pavo Real", "Plumaje"),
                ElementoPredefinido.Individual("Avestruz", "Huevo"),
                ElementoPredefinido.Individual("Cisne", "Lago"),
                ElementoPredefinido.Individual("Cuervo", "Negro"),
                ElementoPredefinido.Individual("Gallo", "Amanecer"),
                ElementoPredefinido.Individual("Gallina", "Corral"),
                ElementoPredefinido.Individual("Pato", "Pico"),
                ElementoPredefinido.Individual("Sapo", "Charca"),
                ElementoPredefinido.Individual("Rana", "Salto"),
                ElementoPredefinido.Individual("Tortuga", "Caparazón"),
                ElementoPredefinido.Individual("Iguana", "Reptil"),
                ElementoPredefinido.Individual("Lagarto", "Cola"),
                ElementoPredefinido.Individual("Escorpión", "Aguijón"),
                ElementoPredefinido.Individual("Araña", "Telaraña"),
                ElementoPredefinido.Individual("Hormiga", "Hormiguero"),
                ElementoPredefinido.Individual("Saltamontes", "Verde"),
                ElementoPredefinido.Individual("Grillo", "Canto"),
                ElementoPredefinido.Individual("Mosca", "Vuelo"),
                ElementoPredefinido.Individual("Mosquito", "Picadura"),
                ElementoPredefinido.Individual("Cucaracha", "Resistencia"),
                ElementoPredefinido.Individual("Cangrejo", "Pinzas"),
                ElementoPredefinido.Individual("Langosta", "Mar"),
                ElementoPredefinido.Individual("Gamba", "Crustáceo"),
                ElementoPredefinido.Individual("Caracol", "Baba"),
                ElementoPredefinido.Individual("Medusa", "Tentáculos"),
                ElementoPredefinido.Individual("Estrella de Mar", "Brazos"),
                ElementoPredefinido.Individual("Caballito de Mar", "Hocico"),
                ElementoPredefinido.Individual("Pez Espada", "Espada"),
                ElementoPredefinido.Individual("Pez Payaso", "Anémona"),
                ElementoPredefinido.Individual("Anguila", "Electricidad")
            )
        ),

        // === 4. CATEGORÍA: COMIDA (75 ELEMENTOS) ===
        ColeccionPredefinida(
            nombre = "Gastronomía",
            categoria = "Comida",
            elementos = listOf(
                ElementoPredefinido.Individual("Pizza", "Porción"),
                ElementoPredefinido.Individual("Sushi", "Wasabi"),
                ElementoPredefinido.Individual("Hamburguesa", "Pepinillo"),
                ElementoPredefinido.Individual("Paella", "Azafrán"),
                ElementoPredefinido.Individual("Taco", "Picante"),
                ElementoPredefinido.Individual("Helado", "Cucurucho"),
                ElementoPredefinido.Individual("Pasta", "Al dente"),
                ElementoPredefinido.Individual("Ensalada", "Vinagreta"),
                ElementoPredefinido.Individual("Chocolate", "Cacao"),
                ElementoPredefinido.Individual("Sopa", "Cuchara"),
                ElementoPredefinido.Individual("Pan", "Miga"),
                ElementoPredefinido.Individual("Queso", "Fermentación"),
                ElementoPredefinido.Individual("Huevo", "Yema"),
                ElementoPredefinido.Individual("Manzana", "Pecado"),
                ElementoPredefinido.Individual("Patata", "Frita"),
                ElementoPredefinido.Individual("Filete", "Punto"),
                ElementoPredefinido.Individual("Croqueta", "Bechamel"),
                ElementoPredefinido.Individual("Yogur", "Bífidus"),
                ElementoPredefinido.Individual("Café", "Cafeína"),
                ElementoPredefinido.Individual("Galleta", "Pepitas"),
                ElementoPredefinido.Individual("Marisco", "Concha"),
                ElementoPredefinido.Individual("Arroz", "Grano"),
                ElementoPredefinido.Individual("Miel", "Dulzura"),
                ElementoPredefinido.Individual("Donut", "Glaseado"),
                ElementoPredefinido.Individual("Sándwich", "Relleno"),
                ElementoPredefinido.Individual("Tarta", "Vela"),
                ElementoPredefinido.Individual("Pescado", "Escamas"),
                ElementoPredefinido.Individual("Pollo", "Asado"),
                ElementoPredefinido.Individual("Lentejas", "Hierro"),
                ElementoPredefinido.Individual("Garbanzos", "Cocido"),
                ElementoPredefinido.Individual("Espaguetis", "Salsa"),
                ElementoPredefinido.Individual("Macarrones", "Gratinado"),
                ElementoPredefinido.Individual("Tortilla", "Patatas"),
                ElementoPredefinido.Individual("Gazpacho", "Tomate"),
                ElementoPredefinido.Individual("Salmorejo", "Pan"),
                ElementoPredefinido.Individual("Chuletón", "Brasa"),
                ElementoPredefinido.Individual("Salmón", "Rosado"),
                ElementoPredefinido.Individual("Atún", "Lata"),
                ElementoPredefinido.Individual("Bacalao", "Salazón"),
                ElementoPredefinido.Individual("Calamares", "Anillas"),
                ElementoPredefinido.Individual("Pulpo", "Gallega"),
                ElementoPredefinido.Individual("Gambas", "Plancha"),
                ElementoPredefinido.Individual("Albóndigas", "Carne"),
                ElementoPredefinido.Individual("Lasaña", "Capas"),
                ElementoPredefinido.Individual("Canelones", "Pasta"),
                ElementoPredefinido.Individual("Risotto", "Cremoso"),
                ElementoPredefinido.Individual("Cuscús", "Sémola"),
                ElementoPredefinido.Individual("Hummus", "Garbanzo"),
                ElementoPredefinido.Individual("Guacamole", "Aguacate"),
                ElementoPredefinido.Individual("Burrito", "Frijoles"),
                ElementoPredefinido.Individual("Nacho", "Queso"),
                ElementoPredefinido.Individual("Kebab", "Carne"),
                ElementoPredefinido.Individual("Curry", "Especias"),
                ElementoPredefinido.Individual("Ramen", "Caldo"),
                ElementoPredefinido.Individual("Dim Sum", "Vapor"),
                ElementoPredefinido.Individual("Ceviche", "Limón"),
                ElementoPredefinido.Individual("Arepa", "Maíz"),
                ElementoPredefinido.Individual("Empanada", "Masa"),
                ElementoPredefinido.Individual("Quiche", "Huevo"),
                ElementoPredefinido.Individual("Crepe", "Dulce"),
                ElementoPredefinido.Individual("Gofre", "Cuadrados"),
                ElementoPredefinido.Individual("Churros", "Aceite"),
                ElementoPredefinido.Individual("Flan", "Caramelo"),
                ElementoPredefinido.Individual("Natillas", "Canela"),
                ElementoPredefinido.Individual("Arroz con leche", "Postre"),
                ElementoPredefinido.Individual("Brownie", "Chocolate"),
                ElementoPredefinido.Individual("Muffin", "Magdalena"),
                ElementoPredefinido.Individual("Croissant", "Mantequilla"),
                ElementoPredefinido.Individual("Baguette", "Francia"),
                ElementoPredefinido.Individual("Pretzel", "Sal"),
                ElementoPredefinido.Individual("Palomitas", "Maíz"),
                ElementoPredefinido.Individual("Pipas", "Girasol"),
                ElementoPredefinido.Individual("Almendras", "Frutos secos"),
                ElementoPredefinido.Individual("Nueces", "Cáscara"),
                ElementoPredefinido.Individual("Aceitunas", "Aperitivo")
            )
        ),

        // === 5. CATEGORÍA: PROFESIÓN (75 ELEMENTOS) ===
        ColeccionPredefinida(
            nombre = "Oficios",
            categoria = "Profesión",
            elementos = listOf(
                ElementoPredefinido.Individual("Médico", "Estetoscopio"),
                ElementoPredefinido.Individual("Bombero", "Manguera"),
                ElementoPredefinido.Individual("Profesor", "Pizarra"),
                ElementoPredefinido.Individual("Policía", "Esposas"),
                ElementoPredefinido.Individual("Cocinero", "Gorro"),
                ElementoPredefinido.Individual("Arquitecto", "Plano"),
                ElementoPredefinido.Individual("Astronauta", "Gravedad"),
                ElementoPredefinido.Individual("Pintor", "Lienzo"),
                ElementoPredefinido.Individual("Mecánico", "Tuerca"),
                ElementoPredefinido.Individual("Abogado", "Código"),
                ElementoPredefinido.Individual("Músico", "Partitura"),
                ElementoPredefinido.Individual("Científico", "Microscopio"),
                ElementoPredefinido.Individual("Fotógrafo", "Flash"),
                ElementoPredefinido.Individual("Dentista", "Carie"),
                ElementoPredefinido.Individual("Piloto", "Cabina"),
                ElementoPredefinido.Individual("Carpintero", "Serrín"),
                ElementoPredefinido.Individual("Juez", "Mazo"),
                ElementoPredefinido.Individual("Veterinario", "Mascotas"),
                ElementoPredefinido.Individual("Periodista", "Entrevista"),
                ElementoPredefinido.Individual("Actor", "Guion"),
                ElementoPredefinido.Individual("Granjero", "Cosecha"),
                ElementoPredefinido.Individual("Panadero", "Levadura"),
                ElementoPredefinido.Individual("Electricista", "Voltaje"),
                ElementoPredefinido.Individual("Bailarín", "Escenario"),
                ElementoPredefinido.Individual("Jardinero", "Poda"),
                ElementoPredefinido.Individual("Cartero", "Buzón"),
                ElementoPredefinido.Individual("Escritor", "Novela"),
                ElementoPredefinido.Individual("Enfermero", "Inyección"),
                ElementoPredefinido.Individual("Psicólogo", "Terapia"),
                ElementoPredefinido.Individual("Ingeniero", "Cálculo"),
                ElementoPredefinido.Individual("Programador", "Código"),
                ElementoPredefinido.Individual("Diseñador", "Boceto"),
                ElementoPredefinido.Individual("Economista", "Finanzas"),
                ElementoPredefinido.Individual("Arqueólogo", "Fósil"),
                ElementoPredefinido.Individual("Geólogo", "Rocas"),
                ElementoPredefinido.Individual("Biólogo", "Células"),
                ElementoPredefinido.Individual("Químico", "Reacción"),
                ElementoPredefinido.Individual("Físico", "Átomo"),
                ElementoPredefinido.Individual("Matemático", "Ecuación"),
                ElementoPredefinido.Individual("Filósofo", "Pensamiento"),
                ElementoPredefinido.Individual("Historiador", "Pasado"),
                ElementoPredefinido.Individual("Geógrafo", "Mapas"),
                ElementoPredefinido.Individual("Político", "Votos"),
                ElementoPredefinido.Individual("Diplomático", "Embajada"),
                ElementoPredefinido.Individual("Militar", "Uniforme"),
                ElementoPredefinido.Individual("Marino", "Océano"),
                ElementoPredefinido.Individual("Sacerdote", "Sotana"),
                ElementoPredefinido.Individual("Escultor", "Cincel"),
                ElementoPredefinido.Individual("Director", "Batuta"),
                ElementoPredefinido.Individual("Cantante", "Micrófono"),
                ElementoPredefinido.Individual("Poeta", "Verso"),
                ElementoPredefinido.Individual("Modelo", "Pasarela"),
                ElementoPredefinido.Individual("Joyero", "Diamante"),
                ElementoPredefinido.Individual("Relojero", "Engranaje"),
                ElementoPredefinido.Individual("Zapatero", "Suela"),
                ElementoPredefinido.Individual("Sastre", "Dedal"),
                ElementoPredefinido.Individual("Carnicero", "Cuchillo"),
                ElementoPredefinido.Individual("Pescadero", "Mostrador"),
                ElementoPredefinido.Individual("Frutero", "Balanza"),
                ElementoPredefinido.Individual("Camarero", "Bandeja"),
                ElementoPredefinido.Individual("Recepcionista", "Teléfono"),
                ElementoPredefinido.Individual("Azafata", "Vuelo"),
                ElementoPredefinido.Individual("Guía", "Turismo"),
                ElementoPredefinido.Individual("Bibliotecario", "Archivo"),
                ElementoPredefinido.Individual("Vigilante", "Alarma"),
                ElementoPredefinido.Individual("Albañil", "Ladrillo"),
                ElementoPredefinido.Individual("Fontanero", "Tubería"),
                ElementoPredefinido.Individual("Pintor", "Brocha"),
                ElementoPredefinido.Individual("Cerrajero", "Ganzúa"),
                ElementoPredefinido.Individual("Minero", "Pico"),
                ElementoPredefinido.Individual("Leñador", "Herramienta"),
                ElementoPredefinido.Individual("Pescador", "Red"),
                ElementoPredefinido.Individual("Cazador", "Rifle"),
                ElementoPredefinido.Individual("Barrendero", "Escoba"),
                ElementoPredefinido.Individual("Taxista", "Volante")
            )
        )
    )
}