package org.example.project.Datos

data class TextosBiblioteca(
    val titulo: String,
    val buscarListas: String,
    val filtroTodas: String,
    val filtroMias: String,
    val filtroDescargadas: String,
    val filtroColaboraciones: String,
    val sinListas: String,
    val sinResultados: String,
    val tituloTutorial: String,
    val descTutorial: String,
    val btnEntendido: String,
    val tituloAbandonar: String,
    val tituloEliminar: String,
    val descAbandonar1: String,
    val descAbandonar2: String,
    val descEliminar1: String,
    val descEliminar2: String,
    val btnAbandonar: String,
    val btnEliminar: String,
    val btnCancelar: String,
    val por: String,
    val porMi: String,
    val pal: String,
    val pulsaAqui: String,
    val jugar: String
)

fun obtenerTextosBiblioteca(idioma: IdiomaSoportado): TextosBiblioteca {
    return when (idioma) {
        IdiomaSoportado.ESPANOL -> TextosBiblioteca(
            titulo = "Mi Biblioteca",
            buscarListas = "Buscar listas...",
            filtroTodas = "Todas",
            filtroMias = "Mías",
            filtroDescargadas = "Descargadas",
            filtroColaboraciones = "Colaboraciones",
            sinListas = "Aún no tienes ninguna lista creada.",
            sinResultados = "No se encontraron resultados.",
            tituloTutorial = "Sigue el tutorial",
            descTutorial = "Para continuar con el tutorial, debes pulsar el botón 'JUGAR' en tu lista para ver cómo se configura una partida.",
            btnEntendido = "ENTENDIDO",
            tituloAbandonar = "¿Abandonar colaboración?",
            tituloEliminar = "¿Eliminar colección?",
            descAbandonar1 = "¿Seguro que quieres dejar de colaborar en '",
            descAbandonar2 = "'? Perderás el acceso a la lista, pero el creador conservará los cambios que hayas hecho.",
            descEliminar1 = "¿Estás seguro de que quieres borrar '",
            descEliminar2 = "'? Esta acción no se puede deshacer.",
            btnAbandonar = "ABANDONAR",
            btnEliminar = "ELIMINAR",
            btnCancelar = "CANCELAR",
            por = "Por",
            porMi = "Por Mí",
            pal = "pal.",
            pulsaAqui = "¡PULSA AQUÍ!",
            jugar = "JUGAR"
        )
        IdiomaSoportado.FRANCES -> TextosBiblioteca(
            titulo = "Ma Bibliothèque",
            buscarListas = "Rechercher des listes...",
            filtroTodas = "Toutes",
            filtroMias = "Miennes",
            filtroDescargadas = "Téléchargées",
            filtroColaboraciones = "Collaborations",
            sinListas = "Vous n'avez encore créé aucune liste.",
            sinResultados = "Aucun résultat trouvé.",
            tituloTutorial = "Suivez le tutoriel",
            descTutorial = "Pour continuer le tutoriel, appuyez sur 'JOUER' sur votre liste pour voir comment configurer une partie.",
            btnEntendido = "COMPRIS",
            tituloAbandonar = "Quitter la collaboration ?",
            tituloEliminar = "Supprimer la collection ?",
            descAbandonar1 = "Voulez-vous vraiment cesser de collaborer sur '",
            descAbandonar2 = "' ? Vous perdrez l'accès, mais le créateur conservera vos modifications.",
            descEliminar1 = "Voulez-vous vraiment supprimer '",
            descEliminar2 = "' ? Cette action est irréversible.",
            btnAbandonar = "QUITTER",
            btnEliminar = "SUPPRIMER",
            btnCancelar = "ANNULER",
            por = "Par",
            porMi = "Par Moi",
            pal = "mots",
            pulsaAqui = "CLIQUEZ ICI !",
            jugar = "JOUER"
        )
        IdiomaSoportado.ITALIANO -> TextosBiblioteca(
            titulo = "La Mia Biblioteca",
            buscarListas = "Cerca liste...",
            filtroTodas = "Tutte",
            filtroMias = "Mie",
            filtroDescargadas = "Scaricate",
            filtroColaboraciones = "Collaborazioni",
            sinListas = "Non hai ancora creato nessuna lista.",
            sinResultados = "Nessun risultato trovato.",
            tituloTutorial = "Segui il tutorial",
            descTutorial = "Per continuare il tutorial, devi premere il pulsante 'GIOCA' sulla tua lista per vedere come impostare una partita.",
            btnEntendido = "CAPITO",
            tituloAbandonar = "Abbandonare collaborazione?",
            tituloEliminar = "Eliminare collezione?",
            descAbandonar1 = "Sei sicuro di voler smettere di collaborare a '",
            descAbandonar2 = "'? Perderai l'accesso alla lista, ma il creatore manterrà le tue modifiche.",
            descEliminar1 = "Sei sicuro di voler eliminare '",
            descEliminar2 = "'? Questa azione non può essere annullata.",
            btnAbandonar = "ABBANDONA",
            btnEliminar = "ELIMINA",
            btnCancelar = "ANNULLA",
            por = "Di",
            porMi = "Da Me",
            pal = "par.",
            pulsaAqui = "PREMI QUI!",
            jugar = "GIOCA"
        )
        IdiomaSoportado.ALEMAN -> TextosBiblioteca(
            titulo = "Meine Bibliothek",
            buscarListas = "Listen suchen...",
            filtroTodas = "Alle",
            filtroMias = "Meine",
            filtroDescargadas = "Heruntergeladen",
            filtroColaboraciones = "Kollaborationen",
            sinListas = "Du hast noch keine Liste erstellt.",
            sinResultados = "Keine Ergebnisse gefunden.",
            tituloTutorial = "Folge dem Tutorial",
            descTutorial = "Um mit dem Tutorial fortzufahren, drücke auf 'SPIELEN' bei deiner Liste, um zu sehen, wie ein Spiel eingerichtet wird.",
            btnEntendido = "VERSTANDEN",
            tituloAbandonar = "Kollaboration verlassen?",
            tituloEliminar = "Sammlung löschen?",
            descAbandonar1 = "Möchtest du die Kollaboration an '",
            descAbandonar2 = "' wirklich beenden? Du verlierst den Zugriff, aber der Ersteller behält deine Änderungen.",
            descEliminar1 = "Bist du sicher, dass du '",
            descEliminar2 = "' löschen möchtest? Diese Aktion ist endgültig.",
            btnAbandonar = "VERLASSEN",
            btnEliminar = "LÖSCHEN",
            btnCancelar = "ABBRECHEN",
            por = "Von",
            porMi = "Von Mir",
            pal = "Wört.",
            pulsaAqui = "HIER DRÜCKEN!",
            jugar = "SPIELEN"
        )
        IdiomaSoportado.CHINO -> TextosBiblioteca(
            titulo = "我的图书馆",
            buscarListas = "搜索列表...",
            filtroTodas = "全部",
            filtroMias = "我的",
            filtroDescargadas = "已下载",
            filtroColaboraciones = "合作",
            sinListas = "您还没有创建任何列表。",
            sinResultados = "未找到结果。",
            tituloTutorial = "跟随教程",
            descTutorial = "要继续教程，您必须在列表上按“开始游戏”来查看如何设置游戏。",
            btnEntendido = "明白了",
            tituloAbandonar = "放弃合作？",
            tituloEliminar = "删除集合？",
            descAbandonar1 = "您确定要停止合作 '",
            descAbandonar2 = "' 吗？您将失去访问权限，但创建者将保留您的更改。",
            descEliminar1 = "您确定要删除 '",
            descEliminar2 = "' 吗？此操作无法撤消。",
            btnAbandonar = "离开",
            btnEliminar = "删除",
            btnCancelar = "取消",
            por = "由",
            porMi = "由我",
            pal = "词",
            pulsaAqui = "点击这里！",
            jugar = "开始游戏"
        )
        IdiomaSoportado.JAPONES -> TextosBiblioteca(
            titulo = "マイライブラリ",
            buscarListas = "リストを検索...",
            filtroTodas = "すべて",
            filtroMias = "マイリスト",
            filtroDescargadas = "ダウンロード済み",
            filtroColaboraciones = "コラボ",
            sinListas = "まだリストを作成していません。",
            sinResultados = "結果が見つかりませんでした。",
            tituloTutorial = "チュートリアルに従う",
            descTutorial = "チュートリアルを続けるには、リストの「プレイ」ボタンを押してゲームの設定方法を確認してください。",
            btnEntendido = "了解",
            tituloAbandonar = "コラボを終了しますか？",
            tituloEliminar = "コレクションを削除しますか？",
            descAbandonar1 = "本当に '",
            descAbandonar2 = "' のコラボを終了しますか？アクセス権は失われますが、作成者はあなたの変更を保持します。",
            descEliminar1 = "本当に '",
            descEliminar2 = "' を削除しますか？この操作は元に戻せません。",
            btnAbandonar = "終了",
            btnEliminar = "削除",
            btnCancelar = "キャンセル",
            por = "作成者",
            porMi = "自分",
            pal = "単語",
            pulsaAqui = "ここを押す！",
            jugar = "プレイ"
        )
        // INGLÉS (Por defecto)
        else -> TextosBiblioteca(
            titulo = "My Library",
            buscarListas = "Search lists...",
            filtroTodas = "All",
            filtroMias = "Mine",
            filtroDescargadas = "Downloaded",
            filtroColaboraciones = "Collabs",
            sinListas = "You don't have any created list yet.",
            sinResultados = "No results found.",
            tituloTutorial = "Follow the tutorial",
            descTutorial = "To continue with the tutorial, you must press the 'PLAY' button on your list to see how a game is set up.",
            btnEntendido = "GOT IT",
            tituloAbandonar = "Leave collaboration?",
            tituloEliminar = "Delete collection?",
            descAbandonar1 = "Are you sure you want to stop collaborating on '",
            descAbandonar2 = "'? You will lose access to the list, but the creator will keep the changes you made.",
            descEliminar1 = "Are you sure you want to delete '",
            descEliminar2 = "'? This action cannot be undone.",
            btnAbandonar = "LEAVE",
            btnEliminar = "DELETE",
            btnCancelar = "CANCEL",
            por = "By",
            porMi = "By Me",
            pal = "wds.",
            pulsaAqui = "CLICK HERE!",
            jugar = "PLAY"
        )
    }
}